### ISSUE TITLE
Support for NTLM proxy protocol on Windows

### ISSUE THREAD

**Issue by akbarmunir** [toggl-open-source/toggldesktop#1150]
The new toggl desktop timer does not support the NTLM proxy on windows. I am using Windows 7 Enterprise in office, which is integrated with Windows infrastructure (Active Directory + Forefront Gateway). The only supported protocol open on our proxy is NTLM authentication. The old version of the desktop timer 6.30 was supporting this, but the new 7.x version does not support this.

Kindly make NTLM compatible protocol for proxy settings for the new v7.x desktop application.

**Comment by tanel** [comment]
If TideSDK supported it, we can lift the relevant source code from TideSDK project.

**Comment by chipbite** [comment]
Ah, I commented on "Use proxy settings from system", #1087

https://github.com/toggl/toggldesktop/issues/1087#issuecomment-136378650

I think the company uses NTLM proxy, so this issue applies.

**Comment by IndrekV** [comment]
We will not look into this at this moment.
