### ISSUE TITLE
Move appcast files to github

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1611]
- [x] Move appcast files to github
- [ ] Change the appcast url inside the app
- [ ] Use the raw url to fetch Appcast

**Comment by skel35** [comment]
I feel like this should get into the next milestone as there is no reason to postpone it.
Benefits of completing this task are:
- Simplified release process, will allow performing releases in GitHub Actions or anywhere else without the need for corporate VPN
- Less load on Toggl servers as the desktop client will be hitting GitHub for the appcast files

The URLs for the appcast files are:
https://toggl.github.io/toggldesktop/assets/releases/darwin_stable_appcast.xml
https://toggl.github.io/toggldesktop/assets/releases/darwin_beta_appcast.xml
https://toggl.github.io/toggldesktop/assets/releases/darwin_dev_appcast.xml
