### ISSUE TITLE
Stopped timer restarts

### ISSUE THREAD

**Issue by fonorobert** [toggl-open-source/toggldesktop#1717]
What happens:
- start tracking time 
- stop the timer 
- the timer stops, then In a few seconds (say 15-30 sec.) the app reloads and continues to track time as if it was never stopped
- stop it again, it stops and remains stopped
- The second bit of time (the one which started by itself) is not really recorded, it's not shown in the web app

case: 217275

**Comment by skel35** [comment]
outdated
