### ISSUE TITLE
When clicking "Add idle time as new entry" two timers run at the same time

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1722]
osx_native_app/7.3.16

> I just came back to my computer from a meeting and clicked ’Add idle time as new entry’. It added an additional time entry but without stopping the previous entry, so the two time entries run in parallel. (See attached image showing screenshots of the two entries.) Could you look into this please

Might be connected to #1676

**Comment by kadrihvl** [comment]
Reported with desk case #226899 (logs included).

**Comment by skel35** [comment]
outdated
