### ISSUE TITLE
Make it possible to create staging builds with buildbots

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1726]
- either it is possible to set parameter that is used when building.
  `Force build` seems to allow setting params
- Or create a clone build bot that uses modified build script for building staging build .

Staging builds should not be uploaded to github as they are for internal use.

**Comment by amulware** [comment]
Alternatively, we could allow connecting to staging with all builds by for example placing a file with a particular name next to the executable. That would not require any fiddling with the buildbots, and would allow for example the obm team to do everything themselves (download dev build, put file next to it, test in staging).

**Comment by IndrekV** [comment]
This can also be solved with adding line to hosts file that redirects all toggl.com traffic to staging. 
Plus is that it needs no development and the testers can just change one line in hosts file to make it work. For that we would need the IP address of staging.

Another way would be to hardcode certain accounts to the app so that with these accounts there is an extra setting to switch to staging.

**Comment by amulware** [comment]
Hardcoding accounts won't work since testing the obm experiments might require the creation of a number of accounts.

I do not think that using the hosts file is a good option either, since it is fairly technical and will make toggl.com mostly unusable on the machine.

**Comment by IndrekV** [comment]
With hosts file it would be activated only when user tests. If not used the rule would be uncommented so toggl.com not being usable would not be an issue.

**Comment by amulware** [comment]
Yes, I understand that. I would personally find this very annoying and complicated. I do not know about other operating systems, but on Windows it rather annoying to edit that file.

**Comment by IndrekV** [comment]
The hosts solution would be the fastest. It shouldn't be too difficult to change that file. Admin rights are probably needed.

As for the hard coded users, we could hard code workspace so that all the users in that workspace would see option.

But I think that separate staging build would probably be best solution in the long run. This need looking into the logic of the buildbot.

**Comment by skel35** [comment]
Will be addressed by #3407
