### ISSUE TITLE
When an activity is stopped on the mobile ap, it continues to go on the desktop

### ISSUE THREAD

**Issue by masumi23** [toggl-open-source/toggldesktop#1810]
This has happened consistently for me for the last few days. 

Whenever I come to my computer, I will see that the Toggl timer on an activity is still going if I had previously stopped it on my phone. If I had logged multiple activities on my phone, then the most recent one will be the one still active on the desktop. 

If I stop the activity on my desktop, then all is well.

**Comment by lucaritossa** [comment]
Mee too... 

A workaround that seems to work: **logout+login from mobile app**

**Comment by IndrekV** [comment]
This seems to be a mobile app specific syncing issue. Not sure we can do anything about it on the desktop app side.

**Comment by skel35** [comment]
old mobile-related issue, not relevant anymore
