### ISSUE TITLE
Add functionality to store arbitrary bool-flags in database

### ISSUE THREAD

**Issue by amulware** [toggl-open-source/toggldesktop#1817]
This would be used to show certain hints for OBM only a single time.

Needs API calls for setting and getting:

```
void toggl_set_obm_flag(flag, bool) // bool could be skipped, but this makes it more flexible
bool toggl_get_obm_flag(flag) // false if not found
```

In the database it could be stored either as tuples of `user, flag` or `user, flag, bool`. In the former case, the entry would have to be removed, instead of set to false, if that functionality is implemented.

We also have to decide whether the flag should be an integer or a string.

This issue is not critical at the moment, but probably needs to be done during the sprint in summer 2016.

**Comment by skel35** [comment]
we're not using OBM anymore and will soon remove it from the codebase entirely
