### ISSUE TITLE
Load more button breaks osx app if pressed after signup

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1857]
Create new account press `load more` the app shows broken window.

<img width="412" alt="screen shot 2016-03-16 at 16 28 12" src="https://cloud.githubusercontent.com/assets/842229/13815753/7de094fa-eb94-11e5-8c19-b210c5db86b2.png">

**Comment by IndrekV** [comment]
Same issue after clear cache.

**Comment by NghiaTranUIT** [comment]
Closed because it's out of date with the new design and I couldn't reproduce it anymore 👍
