### ISSUE TITLE
Linux app seems to be consuming a lot of memory

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1874]
User reports:

> linux app consumes ~1.2G memory on Linux Mint
> _cat /etc/issue_
> Linux Mint 17.1 Rebecca \n \l
> _uname -a_
> Linux layoone 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014
> x86_64 x86_64 x86_64 GNU/Linux

**Comment by kadrihvl** [comment]
Logs with case #274295; description in #274217

**Comment by danfarrow** [comment]
FYI I'm not seeing this issue on Ubuntu

    $ cat /etc/issue
    Ubuntu 14.04.4 LTS \n \l

    $uname -a
    Linux sq-laptop-ub 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by skel35** [comment]
outdated as we fixed multiple memory leak issues since
