### ISSUE TITLE
Memory leak in linux app

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1913]
It seems that the app memory usage increases when timer is running. With longer usage period it can cause the computer to slow down.

More details in: 292318

**Comment by Spurlos** [comment]
Confirming the issue in latest beta release.
![image](https://cloud.githubusercontent.com/assets/667533/23553831/27c18dc0-002b-11e7-91d4-6d2508ea3809.png)

This looks severe for those use cases when system isn't being restarted for long time. Its not the best UX to restart app just to avoid memory trashing.

**Comment by fonorobert** [comment]
also reported in desk case 451290

**Comment by Spurlos** [comment]
Toggl beats any other memory hog on my machine:
![image](https://cloud.githubusercontent.com/assets/667533/26411358/64b16700-40ae-11e7-9a5a-1b1b628dc0a8.png)

Seriously - its time to profile this bug. Almost a year passed since opening this issue.

**Comment by tr00st** [comment]
Possibly the same issue as #1720 - open since late 2015

**Comment by MartinBriza** [comment]
Some memory leaks are fixed now, however if any of the people in this thread (or anybody else of course) experience memory leaks under Linux, please feel free to reopen this report or create a new one, I'll be happy to look into it.

**Comment by hbayindir** [comment]
Hello all,
When using Toggl for Linux under KDE, it causes `kwin`'s memory usage to skyrocket. Approximately 8-9 MBs/sec. I'll add a screenshot as soon as possible.

**Comment by hbayindir** [comment]
Hello all,

I've found out that, toggl Track for Linux causes KDE Plasmashell to leak 8MB of memory every second while tracking a task. I'm using the latest `flatpak` version on Debian `Testing` (Bullseye).

Below is a screenshot from tracking a task for ~13 minutes.

![plasmashell_toggle_memory_leak](https://user-images.githubusercontent.com/479423/105020931-01940880-5a59-11eb-8d75-76ad2c135e4f.png)

It's not possible to get the memory back until logging out and logging in. It's causing a slow death when left unattended.

**Comment by skel35** [comment]
@hbayindir Thanks for reporting the issue. Other KDE users have reported a similar issue here https://github.com/toggl-open-source/toggldesktop/issues/4756. There's no resolution yet, so for now we can just recommend to use Toggl Track's web app and/or browser extension until #4756 is fixed.

**Comment by hbayindir** [comment]
> @hbayindir Thanks for reporting the issue. Other KDE users have reported a similar issue here #4756. There's no resolution yet, so for now we can just recommend to use Toggl Track's web app and/or browser extension until #4756 is fixed.

Thanks @skel35. I'll follow that issue.
