### ISSUE TITLE
Proxy authentication fails with username and password

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1915]
Reported on Windows.

Seem the solution with setting proxy auth to session is not working ok. We should try using `HTTPBasicCredentials` and set the proxy auth to `HTTPRequest`.

http://pocoproject.org/docs/Poco.Net.HTTPBasicCredentials.html#20784

User is seeing errors (case: 292410): 

```
ConfigureProxy:D:Proxy credentials
configured username=test
E:HTTP Exception: Cannot
establish proxy connection: Proxy Authorization Required
```

Some references:
http://stackoverflow.com/questions/1327485/proxy-authentication-in-poco-net-c-library

http://stackoverflow.com/questions/32455309/how-to-use-poco-c-in-proxy-environment-using-httpstreamfactory

**Comment by skel35** [comment]
Multiple proxy issues have been fixed since then.
We'll open new issues if there's user feedback that it's not working.
