### ISSUE TITLE
The Windows App does not deal well with multi-monitor setups.

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1942]
User reports:

> - If you put toggl in full screen mode on a secondary screen, you can't edit the details of an entry. Toggl tries to open the little extra window left to the main window but fails to do so (my main monitor is left to the secondary monitor so I assume toggl can't handle this setup).
> - If you delete entries the little extra window, asking for the confirmation, opens up on the primary monitor instead of the secondary one.

**Comment by nicktoggl** [comment]
case/421120 might be similar, tri-screen setup

**Comment by skel35** [comment]
already mentioned in #2048
