### ISSUE TITLE
Adding TogglDesktop to Login items clears the list

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1950]
User reports:

> On every restart the items in Login itemst list is cleared if Toggl Desktop is set as login item.

Case: 312382

**Comment by Nooba** [comment]
I just experienced this incredibly annoying issue on El Capitan 10.11.6

**Comment by sdjm-tessella** [comment]
This happens to me as well.  The list doesn't clear completely, but somehow when I add Toggl Desktop it launches on the next restart, but is then gone from the login items for the restart after that.  The two other items on the list are unaffected.

**Comment by skel35** [comment]
outdated issue

if you still experience this, please contact support@toggl.com
