### ISSUE TITLE
Autotracker - check browser urls for keywords

### ISSUE THREAD

**Issue by camrodam** [toggl-open-source/toggldesktop#1956]
Since a lot of my work is in online "web-apps", a simple check on what the window name contains is usually not enough detail. What I'd like is to track based on url, so if I'm working in website.com/client1 this can be tracked automatically, and change projects when I start working on otherwebsite.com/client2

**Comment by skel35** [comment]
Not possible to implement in just a desktop app.

It can be potentially done with a browser extension.
