### ISSUE TITLE
Cannot use all modifier keys (⌘⌥^⇧ + Key) AKA Hyper Key for shortcut

### ISSUE THREAD

**Issue by voidl** [toggl-open-source/toggldesktop#1958]
On macOS, when trying to Record a Shortcut for "Show/Hide Toggl" in Preferences, pressing all of the above modifier keys ⌘⌥^⇧ generates an error (below: The key combination ⌘A cannot be used)

![screen shot 2016-07-26 at 1 46 30 pm](https://cloud.githubusercontent.com/assets/7597143/17149011/64b83432-5337-11e6-8f17-303aa2891832.png)

![screen shot 2016-07-26 at 1 41 24 pm](https://cloud.githubusercontent.com/assets/7597143/17148867/c97a21b0-5336-11e6-8a4c-ed2657790c37.png)

More info on why you'd want to use all those keys for a shortcut (bc they're remapped to CapsLock): http://brettterpstra.com/2012/12/08/a-useful-caps-lock-key/

**Comment by skel35** [comment]
I was able to successfully map the Show/Hide Toggl to ⌘⌥^⇧ + A.
So the issue was probably fixed by the underlying library for shortcuts that we're using.
Please reopen if you still experience this issue.

**Comment by voidl** [comment]
Thanks for following up, @skel35!
