### ISSUE TITLE
Desktop app crashes on Ubuntu 16.04

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#1977]
Often, it happens when starting a time entry. But sometimes it happens also
when stopping, or showing the Toggle Desktop, or updating the time entry.

**Comment by miloskroulik** [comment]
I've got the same experience on Linux Mint 17.3 (based on Ubuntu 14.04). How can I provide more useful info?

**Comment by IndrekV** [comment]
It seems we built the latest release with newer version of gcc that is not supported in some older versions of Ubuntu. We will revert this gcc version for the app to be compatible with older versions.

For a faster fix see this issue. #1946

**Comment by stiig** [comment]
I've got the same experience on Xubuntu(based on Ubuntu 16.04)

**Comment by IndrekV** [comment]
Probably outdated. Reopen if this happens on latest stable.
