### ISSUE TITLE
Extreme high CPU usage - drains battery on mac

### ISSUE THREAD

**Issue by rmsj** [toggl-open-source/toggldesktop#1979]
The app keeps jumping from under 1% to 99% of CPU usage and anything in between.

**Comment by RonaldoSantana** [comment]
<img width="461" alt="screen shot 2016-09-08 at 8 17 04 am" src="https://cloud.githubusercontent.com/assets/2113925/18327082/eaa3d600-759c-11e6-9f80-9d4fec5ae096.png">

**Comment by IndrekV** [comment]
Please send feedback from the app and mention it is for Indrek. That way we get logs and additional information about your app.

**Comment by skel35** [comment]
outdated issue
