### ISSUE TITLE
Reminder notifications aren't that explicit

### ISSUE THREAD

**Issue by alexandrevribeiro** [toggl-open-source/toggldesktop#1986]
The reminder notifications aren't that explicit, so most of the time I don't see them. It would be much better if it was more intrusive, and this option could be configurable.

**Comment by IndrekV** [comment]
Could you please specify which platform are you referring.

**Comment by vribeiro-alexandre** [comment]
I

**Comment by vribeiro-alexandre** [comment]
I'm sorry, I forgot to mention it. It's Windows.
![2016-09-16 10_24_59-legalone all - microsoft visual studio](https://cloud.githubusercontent.com/assets/19232271/18587360/f6af3fa0-7bf7-11e6-80de-35158a9a7f21.png)

**Comment by skel35** [comment]
The reminders are now being displayed in a bigger popup with a custom design, so the issue is partially addressed.
We'll consider more intrusiveness and the possibility to configure it separately.
