### ISSUE TITLE
Linux app crashes with multiscreen setup

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2002]
User reports it happening after some time of use. It happens randomly while starting or continuing entry.

syslog output:

```
Oct  3 14:41:21 layoone kernel: [625584.271630] TogglDesktop[3861]: 
segfault at 7f77a409007a 
ip 00007f7822906eee 
sp 00007f77c31f15a8 
error 4 in libc-2.19.so[7f782286f000+1ba000]
```

http://stackoverflow.com/questions/2549214/interpreting-segfault-messages
https://rgeissert.blogspot.com.ee/p/segmentation-fault-error.html
https://ubuntuforums.org/showthread.php?t=2010223

case: 257253

Maybe connected to #1721

**Comment by MartinBriza** [comment]
This is vitually impossible to reproduce now after 4 years (oops) and the crash information is incomplete so I'm closing this as there's insufficient info.
