### ISSUE TITLE
Two-step Introduction for Mac app

### ISSUE THREAD

**Issue by ghost** [toggl-open-source/toggldesktop#2005]
We have a two-step introduction on the Windows app (initially introduced here: https://github.com/toggl/toggldesktop/issues/1819)

As of now no such introduction exists in the Mac app, which is a frustrating new user experience, so we'd like to have the same two-step introduction on Mac. On this vein, it also appears that the Mac app faultily shows a "load more" button instead of an empty state which might need to be addressed as well.

Template images (doesn't have to look exactly like this)

Step 1: 

![image](https://cloud.githubusercontent.com/assets/1181246/19108359/e208b510-8af0-11e6-874d-6803326b6ec6.png)

Step 2:

![image](https://cloud.githubusercontent.com/assets/1181246/19108366/e5d37bee-8af0-11e6-8ab0-95b0546183c7.png)

**Comment by IndrekV** [comment]
Needs merge and release.

**Comment by skel35** [comment]
outdated issue
the purpose of this one is achieved by the Mac onboarding project https://github.com/toggl-open-source/toggldesktop/projects/15
