### ISSUE TITLE
Make the size of the mini-timer less.

### ISSUE THREAD

**Issue by alexaandrov** [toggl-open-source/toggldesktop#2009]
Hello. Please make the size of the mini timer is less, it is too big! Or, provide the opportunity to make it smaller (I use: Windows Desktop Toggle App). Thank you!

**Comment by tusksupport** [comment]
Can you make the mini mode integrated into taskbar, mini mode is useful but causes issues sometimes when it overlaps other windows.

**Comment by IndrekV** [comment]
Thank you for the suggestions. We'll take it under consideration. Making the minitimer part of the taskbar is a bigger task. Making it resizable seems like the way to go.

**Comment by ADTC** [comment]
I would like to ask for this as well. Could be reduced to just the timer and a narrow red/green strip on the right (instead of the full width button).
![togglminilesswidth](https://user-images.githubusercontent.com/6047296/32420602-d3c88c96-c2b2-11e7-8f57-31cb69f71ee2.png)

**Comment by andreasmischke** [comment]
+1 for this feature request!

If it's not easy to integrate the mini timer into the task bar, making it the same height would already help a lot. Then it could at least be dragged there and does not overlap with other windows.

I like ADTCs design a lot! Maybe there could also be the project (color) displayed aside. Would be essential for me. Or even show/hide depending on the width I resized it? That would be fancy!

**Comment by garyng** [comment]
Any updates on this?

**Comment by garyng** [comment]
> 
> 
> Any updates on this?

I just hacked a shorter version of the timer, pretty ugly though.

![image](https://user-images.githubusercontent.com/4453664/47192117-bcfefb80-d37d-11e8-91aa-89b545004af0.png)

![image](https://user-images.githubusercontent.com/4453664/47192163-08190e80-d37e-11e8-9c12-ea30c6a01264.png)

**Comment by VijayaSankarN** [comment]
Is there any update on this? 

Best - Integrate in the windows taskbar, so no standalone application
Better - Atleast taskbar size bar - I use small task bar. Can it stay on top even though I change the workspace? Yes I use 4-5 workspaces in windows

**Comment by xmnovotny** [comment]
+1 for this feature request!

**Comment by nidarasheed** [comment]
[Additional user request](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23714678227)

**Comment by IndrekV** [comment]
We've started the windows app redesign process and will take this into account when updating design. Most probably we'll make it possible to resize the minitimer to smaller size. Keeping the current size as the maximum.

**Comment by skel35** [comment]
The new design for the mini timer is implemented and will be released when we finish updating the design for the rest of the application. 

As for the request to integrate mini timer into the taskbar, there is a separate issue for it #3142, no updates here yet.
