### ISSUE TITLE
Pomodoro break time additional settings

### ISSUE THREAD

**Issue by phandox** [toggl-open-source/toggldesktop#2035]
Can I request a feature, which will take in account setting Pomodoro break? So far, after 25 minutes time is stopped and you have to manually resume it. Taking basic Pomodoro in account, after one Pomodoro there should be 5 minute break, after 4 consecutive Pomodoros, there should be long break - 15 minutes.

It would be nice to have this break time implemented, ideally with custom short break and long break timers.

**Comment by IndrekV** [comment]
@phandox  Let me get this straight.

What you are asking is to add additional Pomododo Break settings like:

* Pomodoro timer Break (on/off)
* Pomodoro short break (minutes)
* Pomodoro long break (minutes)
* Pomodoro long break after (number) of Pomodoros

**Comment by phandox** [comment]
Yes, that's right. Plus, having automatic start of break and starting new pomodoro after break time is elapsed would be nice too.

**Comment by IndrekV** [comment]
Thank you for the details. We'll consider adding this to our todo list.

**Comment by unmultimedio** [comment]
Those options sound actually really cool! Although I've found it's really hard to track what's the 1st, 2nd, and nth pomodoro, if you break just one. It'll start all over.

I think I could start helping on this sometime next month :)

**Comment by sojusnik** [comment]
Would really nice to have!

**Comment by panhartstuff** [comment]
Any progress on this feature?

**Comment by IndrekV** [comment]
No progress on this. We have not added this to our current development plan so this will not happen in near future.

**Comment by skel35** [comment]
Pomodoro Break has been implemented.
The long break feature is requested in #4518.
