### ISSUE TITLE
Feature: add 'Disable reminder until next day'

### ISSUE THREAD

**Issue by fdriessen** [toggl-open-source/toggldesktop#2053]
Hi,

Sometimes, when I have a day off for example, the desktop app keeps reminding me to log my time. 
A context menu (when using windows, don't know about other platforms) would suffice for me, where I can choose to disable the reminder for an hour or until the next working day.

This idea is mainly stolen from f.lux. See attachement.

![image](https://cloud.githubusercontent.com/assets/2244135/20349240/d8df3da8-ac09-11e6-8aa6-6e135456827f.png)

**Comment by skel35** [comment]
closing as a duplicate in favor of #3568
