### ISSUE TITLE
Double-clicking the title bar icon doesn't close the app

### ISSUE THREAD

**Issue by vedr4n** [toggl-open-source/toggldesktop#2055]
Double-clicking the app icon in the title bar closes most Windows applications. However, TogglDesktop just opens Summary reports. The same thing happens when you single-click the icon.

![screen shot 2016 11 21 at 08 38 16](https://cloud.githubusercontent.com/assets/19473351/20474231/eb5025d2-afc5-11e6-804d-ab0bce79646c.png)

**Comment by skel35** [comment]
the titlebar icon is not present in the new design, so the issue is invalid
