### ISSUE TITLE
OSX - idle dialog opens even if the clock is running

### ISSUE THREAD

**Issue by kadrihvl** [toggl-open-source/toggldesktop#2064]
osx_native_app/7.3.337
Basically, I&#39;m getting the idle prompt even when not idle. It always starts at 3 minutes.
Logs: #39340
Similar case was reported not too long ago:

> I recently upgraded my Apple OS to Sierra, and now my Toggle Desktop keeps popping up the idle dialog, even when I&#39;m working.

**Comment by skel35** [comment]
outdated

Please report a separate issue or contact support@toggl.com if you experience a similar problem
