### ISSUE TITLE
Per monitor DPI support

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2066]
>I have two monitors with different DPI (high DPI screen on laptop and low dpi external screen). When I launch Toggle on one monitor and drag it to another, the font becomes blurry.

Microsofts solution:
https://msdn.microsoft.com/en-us/library/windows/desktop/ee308410(v=vs.85).aspx

**Comment by kadrihvl** [comment]
Also reported with desk case #413725

**Comment by skel35** [comment]
https://github.com/microsoft/WPF-Samples/blob/master/PerMonitorDPI/readme.md
new simpler instructions from MS, need to verify the solution doesn't break anything on older Windows versions, and whether bump up to .NET 4.6.2 is needed.

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481301377125)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481304668883)
