### ISSUE TITLE
Linux app crashing

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2079]
>Running from the command line prints the following error. The taskbar icon doesn&#39;t close though but the window does and I can&#39;t re-open it until I quit from the taskbar icon. 
```
QXcbConnection: 
XCB error: 148 (Unknown), 
sequence: 14500, 
resource id: 0, 
major code: 140 (Unknown), 
minor code: 20 
```
```
QXcbConnection: 
XCB error: 148 (Unknown), 
sequence: 14508, 
resource id: 0, 
major code: 140 (Unknown), 
minor code: 20 
```

MIght be connected: https://forum.qt.io/topic/30791/qxcbconnection-xcb-error-165-unknown/2

**Comment by MartinBriza** [comment]
@IndrekV Do we have context for this? What environment did this happen in?

**Comment by MartinBriza** [comment]
Could be related to running in an old Xorg implementation, I think something similar happened to me with XMing under Windows (which is totally an unsupported environment from our side). The link in this report mentions Ubuntu 12.04 which is again absolutely ancient. I'm closing this report but as with the other ones, we're open for reports if this happens to anybody else.
