### ISSUE TITLE
Issues with edit window on secondary screen

### ISSUE THREAD

**Issue by kadrihvl** [toggl-open-source/toggldesktop#2081]
windows_native_app/7.3.337 Logs: case #398096

> The right panel where you type the task name and select the project/client... is not working in the fullscreen mode, i have to change to the small size in order to change the task.
> The problem with the panel shows in secondary screens that i have plug to my laptop, i guess is due to the difference of resolutions, or that mi secondary screen's resolution is to low, i am able to use the panel, but only in the laptop's screen. about the behavior of the panel when it doesn't work, it shows but oddly, the inputs are not shown and it says something about the las update, in the request I attached a picture of the problem.

<img width="640" alt="2016-12-15_14h29_31" src="https://cloud.githubusercontent.com/assets/12407134/21421603/6941a090-c83c-11e6-92b0-18434d3dbffe.png">

**Comment by skel35** [comment]
can't reproduce on the new design
