### ISSUE TITLE
Feature Request: add timeline display to Toggl Desktop

### ISSUE THREAD

**Issue by ssafron** [toggl-open-source/toggldesktop#2121]
I would like to be able to see if I have time entries that cover the whole day, or if I forgot to track my time for certain periods.  Therefore it would be helpful to see a small timeline display on the Toggl Desktop application.  Alternatively there could be an option to display the start/end times instead of the total time for each row.  I know all those views are available on the website but having it right on the desktop app would be convenient.

-Sean

**Comment by IndrekV** [comment]
We like this idea. Could you please state what operating system you are using.

**Comment by ssafron** [comment]
I am running the Toggl desktop app on Windows 7.  Though this feature would be useful on all platforms.

**Comment by jayvdb** [comment]
Timeline is a feature that is critical for me in deciding which tool to use, I'm not seeing any timeline data in the webapp, and I am at a loss as to why ...

https://support.toggl.com/timeline/ says
> Timeline will not be available on the first day after signing up in Toggl – it will be enabled on the second day.

Second day came and went, no improvement.

I can only guess why Toggl doesnt provide Timeline support on the first day, and I am pretty sure the reasons are reasonable.

However that makes evaluation of the tool .. difficult to say the least, especially if it doesnt work after the second day.

If there was some visualisation of the timeline on the client side, I would feel more comfortable that the feature does work properly, and I could better evaluate the results in the client while I am waiting for it to appear on the website.

Currently building the app to see what is going on behind the scenes...

**Comment by jayvdb** [comment]
I see log events to the timeline API endpoint, but it is hard to believe they might be screenshots due to the content-length.  Perhaps an interim measure would be to report in the UI, in a status bar?, that `x` screenshots were sent and `y` other timeline data items were sent to the server.

**Comment by IndrekV** [comment]
Timeline only tracks the focused app titles. Tiemline does not take screenshots.

**Comment by jayvdb** [comment]
Thanks for the clarification; that helps my evaluation. ;-)  Created https://github.com/toggl/toggldesktop/issues/2280

**Comment by skel35** [comment]
Already implemented on macOS and planned for Windows
