### ISSUE TITLE
Dark colored project names not clearly visible on running TE, in Windows

### ISSUE THREAD

**Issue by fonorobert** [toggl-open-source/toggldesktop#2146]
see example from user:

![toggl-test](https://cloud.githubusercontent.com/assets/6963710/24004203/f85ac20a-0a65-11e7-8d34-61ab85c504e0.jpg)

**Comment by nidarasheed** [comment]
User report for MacOS 7.4.484

![image](https://user-images.githubusercontent.com/49634673/63570880-fc970500-c597-11e9-922e-a53aa99ac2ed.png)

**Comment by NghiaTranUIT** [comment]
@tanel I guess we can use the logic in https://github.com/toggl/toggldesktop/pull/3199 for reference. Or we can support dark/light adaptable color in library as well, so we get free on Linux

**Comment by skel35** [comment]
@NghiaTranUIT If we invert the colors on Windows timer then it would mean different colors on Timer vs Time entry list / Edit view / Autocomplete which have a white background. Maybe only inverting black color and only in the timer could be a temporary solution for Windows.
Overall it is a design flaw that we will address in a new design, as we did in macOS version.

**Comment by IndrekV** [comment]
I think doing any alterations for project colors is dangerous as it we have dark theme only in desktop apps, but what about web or Toggl Button. Things won't match. One way to go about it is to make the project a rounded label similar to tags in the edit view. So we make the background ligther so the color is properly visible.

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2931915/conversations/23490328203)

**Comment by skel35** [comment]
will be addressed by https://github.com/toggl-open-source/toggldesktop/projects/16
