### ISSUE TITLE
[Windows 10 64 bit] Toggl desktop not showing / stays minimized in tray

### ISSUE THREAD

**Issue by Kiailandi** [toggl-open-source/toggldesktop#2172]
After opening toggl I only get the grey icon in the system tray. 

Right and left clicking on it have no effect.

Have to kill process (strange thing it says "toggl 32 bit" when the download was advertised as 64 bit only).

Tried to delete folder and install again, same result.

Tried to launch as administrator, same result.

**Comment by skel35** [comment]
outdated issue

if you still experience this, please contact support@toggl.com
