### ISSUE TITLE
Issue with manual entry on Windows 7.4.31

### ISSUE THREAD

**Issue by epagnini** [toggl-open-source/toggldesktop#2184]
When selecting a project for a manual entry the program stops and also the start- and endtime are specified without calculating the duration. 

Windows version 7.4.31

Case 478278

**Comment by epagnini** [comment]
Similar as well to issue reported in case 479002

**Comment by Kevin-Deason** [comment]
For the last +-2 weeks I have been having a lot of issues with toggl desktop application. Seems they made an API change that really messed things up for us. We are now considering an alternative as it sometimes takes up to 5 tries to change fields in the desktop application.

**Comment by zdericnina** [comment]
@Kevin-Deason Please try changing the app version to the latest stable or download from this link: https://github.com/toggl/toggldesktop/releases/download/v7.4.47/TogglDesktopInstaller-7.4.47.exe 
This should resolve the issue.

**Comment by skel35** [comment]
outdated issue, seems to be fixed a while ago
