### ISSUE TITLE
"Host not found" when having a proxy configured

### ISSUE THREAD

**Issue by lindeskar** [toggl-open-source/toggldesktop#2204]
Toggl Desktop behind a proxy is not working well for me at one of the locations I'm working at.

It's working intermittently, but when it stops I can observe the following in _toggldesktop.log_:
```TogglClient:D:Sending request to https://desktop.toggl.com/api/v8/me?app_name=windows_native_app&with_related_data=true ..
ConfigureProxy:D:Proxy configured  host=proxy.company.com port=8080
ConfigureProxy:D:Proxy credentials configured username=myUserName
ServerStatus:D:UpdateStatus status_code=0
ui:E:Host not found: desktop.toggl.com
context:D:Got networking error Host not found: desktop.toggl.com will attempt offline login
```

We **can't resolve external DNS-records directly** at this location. All lookups need to go through the proxy.

I've seen other users solving the problem by adding records to /etc/hosts, but it feels like a temporary hack.

Is there some part of Toggl Desktop not looking up hostnames through the proxy?

**Comment by IndrekV** [comment]
Please send feedback from the app, that way we get the full log and can see on which request the error occurs. Mention the log is for Indrek.

**Comment by lindeskar** [comment]
@IndrekV 
Restarted the app and logged out/in a couple of times. This made communication start working again. Tomorrow it might be broken again. This is basically my experience with the app. :smile: 

Sent feedback via the app and mentioned your name.

**Comment by IndrekV** [comment]
logs in case 495477

**Comment by skel35** [comment]
outdated issue.
if still relevant, please reopen the issue with steps to reproduce or send your feedback to support.
