### ISSUE TITLE
Proxy settings not working all the time

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2206]
It seems that the issue is with `v8/me` request and the `ga statistics` request.

There does not seem to be clear logic why this happens but at some point the proxy stops working.

logs in case: 491798

**Comment by chipbite** [comment]
See also #1513, which says closed, but has to my knowledge never been fixed/working (toggl desktop has not worked behind proxies of any of the multinationals where I work regularly). 
And also #1150.

**Comment by skel35** [comment]
outdated issue, has probably been fixed with other proxy-related bug fixes.
