### ISSUE TITLE
Time not stopping on Windows desktop app

### ISSUE THREAD

**Issue by Ridge-IT** [toggl-open-source/toggldesktop#2214]
Hi.

I seem to have a problem stopping the time on toggl for Desktop, but when I log in on the website, it has stopped. I can't seem to start a new task because of this issue. It isn't even synchronizing but the connection is running super fast.

Thanks.

![toggl desktop issue](https://user-images.githubusercontent.com/8385845/27795560-e5b0d9c2-6006-11e7-9537-f16863d7ff3a.PNG)

**Comment by nicktoggl** [comment]
Hi there,

Could you contact us at support@toggl.com and send us your toggldesktop.db file from the C:\Users\Users\AppData\Local\TogglDesktop folder. Please make sure you send the .db file, not the .db-shm or db.wal file.

It may be a corrupt entry that can be resolved with a clearing of the cache but we want to have a backup of your database in case clearing the cache clears your entries. The cache can be cleared via the desktop app cogwheel menu.

Thanks!

**Comment by skel35** [comment]
haven't been able to reproduce it

please reopen if you still experience this bug
