### ISSUE TITLE
Graphical suggestion

### ISSUE THREAD

**Issue by rifton007** [toggl-open-source/toggldesktop#2227]
The preference window merges with the Toggl Desktop interface.
It would be nice to add an aspet to differentiate the two windows.

![image](https://user-images.githubusercontent.com/2601347/28718729-79c2e084-73a7-11e7-85a0-6898bfef4fb5.png)

Like this for example
![toggl-example](https://user-images.githubusercontent.com/2601347/28719097-ffea70ea-73a8-11e7-9917-149c43957e95.jpg)

**Comment by IndrekV** [comment]
Can you please specify your Windows version.

**Comment by rifton007** [comment]
Hi @IndrekV 
My version is the last, 7.4.52 on Windows

**Comment by IndrekV** [comment]
@rifton007 What I meant was the version Windows not the version of the app. This issue seems to be specific for certain windows versions.

**Comment by skel35** [comment]
In the new design, there is more contrast between the modal windows and the main window + the border shadow of the modal windows.

Darkening/blurring the main window will be under consideration in the future design updates.
