### ISSUE TITLE
Autotracker functionality improvements

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2234]
Feature request:
>Option to export Autotracker triggers. Also, in addition to exporting, it would be nice if there was a way to edit the list of terms & projects

**Comment by skel35** [comment]
Editing the list of terms & projects is already under development for Windows as a part of [Autotracker Update MVP](https://github.com/toggl-open-source/toggldesktop/projects/14) project and will probably be brought to macOS and Linux in the future as well.

Exporting the triggers relates to the problem of sharing the settings in general and not specific to Autotracker.
