### ISSUE TITLE
Windows tray icon minimises app instead of bringing it in front of other apps.

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl-open-source/toggldesktop#2238]
When clicking on the Toggl Desktop icon in the tray even if the Toggl desktop window is behind other windows it minimises the app.

Expected behaviour would be to bring the app to the front and then minimise on a second click as others behave.

case/522171

**Comment by skel35** [comment]
Other apps either always bring the app to front and do not minimize on a second click, or do the same as Toggl Desktop does, as it is hard to detect whether which app was in focus right before clicking the icon.

The behavior described here is the behavior of our "Show/Hide Toggl" global shortcut, so I'd advise users who want to avoid an extra click to use this shortcut instead.
