### ISSUE TITLE
TogglDesktop Install Ubuntu 17.04 64bit

### ISSUE THREAD

**Issue by oliverbienert** [toggl-open-source/toggldesktop#2242]
Hi,

this is a Ubuntu 17.04 64bit running the Budgie Desktop.

- When installing from deb, the toggle icon is not shown in systray, instead, a default box icon is shown. Menu entries work so far.
- When running from tar.gz, the issue arises as well.

I fixed it by adding:
```"$XDG" = "Budgie:GNOME"```
to the second `if`-test in `TogglDesktop.sh` script.

However, then the menu does not honour system layout.
The quit entry (from the dropdown of systray button) does not work or only sometimes. Or, like now, TogglDesktop stopped working but the widget and the systray icon are still visible. Couple of minutes later, I get an OS message: '"ToggleDesktop" is not responding' and asking if I want to force quit the program. Doing so kills it and I can start it again.

I also tried to compile but got stuck when running `make run`:
```
./src/ui/linux/TogglDesktop/build/release/TogglDesktop: error while loading shared libraries: libPocoXML.so.31: cannot open shared object file: No such file or directory
```
which is strange because the file is here:
```
src/lib/linux/TogglDesktopLibrary/build/release/libPocoXML.so.31
```
As a side note, I also had to install:
- libqt5x11extras5-dev
- qtbase5-private-dev

By the way, I like toggl, especially the idle time detection!

Regards Oliver

**Comment by IndrekV** [comment]
It seems as the Poco has not been built properly.

I would try to rebuild dependencies.

```
make clean
make deps
```

**Comment by skel35** [comment]
outdated issue
