### ISSUE TITLE
Windows app crashing

### ISSUE THREAD

**Issue by kadrihvl** [toggl-open-source/toggldesktop#2243]
This issue has been reported by few users.
Current case: user has tried both latest stable and beta versions, both crashing. Is using the latest Framework ver. 

> Last week there was a Windows 10 update and it seems it created a problem
> with toggl. Toggl, the app, keeps crashing about a minute after start up.
> 

Logs with case #528498

![image 1](https://user-images.githubusercontent.com/12407134/29316666-8447686c-81d1-11e7-8c4e-6252d3ebee48.png)

![image](https://user-images.githubusercontent.com/12407134/29316611-5fb8c22a-81d1-11e7-9063-2e06dda9f039.png)

**Comment by skel35** [comment]
oudated issue
