### ISSUE TITLE
User Receiving "Offline/no network" message

### ISSUE THREAD

**Issue by Michelle112** [toggl-open-source/toggldesktop#2245]
The user reports they were able to use the desktop app fine until a few days ago.
They were asked to check possible firewall, proxy, and antivirus conflicts and also uninstalled/reinstalled the app but nothing resolved the issue.

Log file attached to case: 528592

**Comment by oliver-gramberg** [comment]
Is this the "Login fails. Are you online?" message? I get that, too, in a network where "https://toggl.com/" is whitelisted and the website works perfectly. Seems only the desktop app is affected.

**Comment by oliver-gramberg** [comment]
May be it's not that message. See #1513.

**Comment by teresaholfeld** [comment]
I have that message as well. Running the desktop app on Mac 10.14.6.
First I get a little toast "Offline, no network", and then the notification box gets big and shows as text:
```
<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I certainly have network, I am logged in, and I didn't change any proxy settings. It used to work, but some time after the upgrade to 7.4.1012 I got these errors.

**Comment by Artishock88** [comment]
> I have that message as well. Running the desktop app on Mac 10.14.6.
> First I get a little toast "Offline, no network", and then the notification box gets big and shows as text:
> 
> ```
> <html>
> <head><title>429 Too Many Requests</title></head>
> <body>
> <center><h1>429 Too Many Requests</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> ```
> 
> I certainly have network, I am logged in, and I didn't change any proxy settings. It used to work, but some time after the upgrade to 7.4.1012 I got these errors.

You will even see, that the timer is synchronised to the Website and App, but every entry has an exclamation mark and persistent error message.

**Comment by paulagoes** [comment]
This started happening for me yesterday with the new version. I have just updated to 7.4.1022 and issue persists.

**Comment by jafacakes2011** [comment]
I am also having this issue on version 7.4.1023 on macOS 10.14.6

**Comment by vadimreutskiy** [comment]
> I am also having this issue on version 7.4.1023 on macOS 10.14.6
> 
> Edit: I have managed to fix this so far by going into Preferences > Proxy and making sure that "Do not use proxy" was checked.

Experienced the same issue. Your solution helped to solve the problem.

Thank you, Cameron!

**Comment by skel35** [comment]
Multiple issues with proxy were fixed since then.
