### ISSUE TITLE
Desktop editing bug

### ISSUE THREAD

**Issue by nicktoggl** [toggl-open-source/toggldesktop#2258]
case/548265

Toggl Desktop app for Mac (via app store) won't save multiple changes to an entry at the same time. Example: If i change the description, the time, and the tag, it'll only save the first thing I change. I have to make a change, close it, reopen, make a change, close it, etc. Extremely annoying and a productivity killer.

**Comment by skel35** [comment]
outdated the UI was rewritten and multiple related bugs were fixed since then
