### ISSUE TITLE
User not able to log in to Win app

### ISSUE THREAD

**Issue by kadrihvl** [toggl-open-source/toggldesktop#2259]
> 7.4.523 not working on windows 10. reset a few times and same password can logon to windows 10. symantec or firewall not blocking. Tested over 3 locations, 3 networks, same PC. I think it might be a windows 10 configuration?, not sure though.

Logs with case #543544

![image](https://user-images.githubusercontent.com/12407134/30289861-3995e35a-9736-11e7-8b25-90a625e2d035.png)

**Comment by skel35** [comment]
Outdated as it's hard to reproduce and refers to the old support system to which we don't have access anymore. If it still happens, please create a new issue with more information.
