### ISSUE TITLE
Moving mini timer freezes computer

### ISSUE THREAD

**Issue by nicktoggl** [toggl-open-source/toggldesktop#2263]
Please find video in case /case/549161

**Comment by vedr4n** [comment]
The user has the latest version of the Windows app installed - windows_native_app/7.4.58-obm-87-obm-98-obm-99-obm-101

**Comment by TheSoloJake** [comment]
Clearing cache does not solve the problem.

**Comment by IndrekV** [comment]
@TheSoloJake We need more data. Ask user for local database file and then forward it to me. Something fishy is going on.

**Comment by TheSoloJake** [comment]
@IndrekV Requested db files, will update ticket when response received

**Comment by skel35** [comment]
closing the issue as no response from the user received and we were unable to reproduce the issue
