### ISSUE TITLE
Lost access to the last workspace

### ISSUE THREAD

**Issue by vedr4n** [toggl-open-source/toggldesktop#2269]
This issue is present in the latest (Windows) dev release (7.4.62). As soon as you upgrade you see this
![toggl](https://user-images.githubusercontent.com/19473351/30739591-40db285e-9f8e-11e7-8ea1-d28a0819a934.png)

**Comment by IndrekV** [comment]
This is untested development version and is no way usable. Please only use beta or stable channel.

**Comment by vedr4n** [comment]
The reason I mentioned it is because 2 users complained about the problem. They likely updated to the dev reason by accident. 

Just thought you should know...

**Comment by IndrekV** [comment]
It's good that you created this issue as it pointed out one flaw in the logic. I was just trying to point out that using dev channel is very dangerous as data can be lost and thing are broken a lot.

**Comment by skel35** [comment]
not relevant anymore
