### ISSUE TITLE
Connection Issues Through Desktop Client

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#2326]
User is experiencing issues and is receiving errors when trying to connect and use the Toggl desktop client. 

Desk case/588883 includes all information and error notes.

**Comment by vedr4n** [comment]
The user asked me to bump this. They are really anxious to get their desktop app working again.

**Comment by alrayyes** [comment]
Having the same issue. Logfile says:

```
2017-12-25 16:03:05.706 [4629 4]:Analytics:E:SSL Exception: Cannot create SSL_CTX object: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers
2017-12-25 16:03:05.709 [4629 0]:ui:D:DisplayProjectAutocomplete
2017-12-25 16:03:05.710 [4629 1]:websocket_client:D:Shutdown
2017-12-25 16:03:14.159 [4629 0]:ServerStatus:D:UpdateStatus status_code=0
2017-12-25 16:03:14.159 [4629 0]:ui:E:SSL Exception: Cannot create SSL_CTX object: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers
2017-12-25 16:03:14.159 [4629 0]:ui:D:DisplayOnlineState no network
2017-12-25 16:03:14.160 [4629 0]:ui:E:Login failed. Are you online?
```
Using Arch Linux, encountering the issue with toggldesktop & toggldesktop-bin packages. Worked fine until a few weeks ago.

**Comment by douglascaetano** [comment]
Same issue here, also on Arch Linux. Got the problem after upgrading from 7.4.61.

**Comment by ApocalypticFish** [comment]
case/612731

**Comment by fishhead108** [comment]
Same issue with Arch.

**Comment by Kamilcuk** [comment]
Same here with Arch.
This bug may be not upstream fault, but related to packaging or openssl.
Some interesting posts can be found in Arch AUR discussion: https://aur.archlinux.org/packages/toggldesktop/

**Comment by fishhead108** [comment]
@ApocalypticFish any news?

**Comment by fishhead108** [comment]
Temporary solution

1) git clnone https://aur.archlinux.org/toggldesktop.git 
2) cd toggldesktop/ 
3) curl https://gist.githubusercontent.com/phi-mah/e597bb7b70ebcab9d3ae8152850cf864/raw/23114fe3887ab782a86e3934a12809d3444348f6/diff_to_aur | git apply

> (When I do this, I get some errors of the type: <stdin>:64: trailing whitespace, just ignore them)</stdin> to make all the changes that are mentioned in the gist file.
> After that, just run makepkg. This way I got a working pkg. Lets hope that it will work as well in your case!
4) makepkg
5) sudo pacman -U toggldesktop-7.4.76-1-x86_64.pkg.tar.xz

Thx for @phi-mah

**Comment by swalladge** [comment]
These patches have now been added to the aur package. If you're on Archlinux, please update to the latest aur package and hopefully it will work fine. :) https://aur.archlinux.org/packages/toggldesktop/

**Comment by MartinBriza** [comment]
This seems like an issue with a third-party package, so I'm closing it but please feel free to reopen in case there is an issue like this with our official packages.
