### ISSUE TITLE
Signing in on Toggle Desktop Version 

### ISSUE THREAD

**Issue by jacquesjqt** [toggl-open-source/toggldesktop#2334]
Hi,

Love your app!!! However when signing in on the desktop version, I get the following error message:

'I/O error: Permission denied'

Please have a look.

Thanks,

Jacques

**Comment by IndrekV** [comment]
The error suggests that the app is unable to write to a certain file location.

Please share more details about your operating system and how you have installed the app.

**Comment by skel35** [comment]
outdated issue as no info was provided
