### ISSUE TITLE
Improve client add functionality

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2378]
When user types in client name that does not exist currently empty dropdown is shown. We should show item with text `Create client named "client name"`

![screen shot 2018-02-01 at 10 14 30](https://user-images.githubusercontent.com/842229/35668089-ba4a8998-0738-11e8-89f7-8055e12f5e56.png)

This removes the need to click "add client" and then type in client name.

Other solution would be to copy text from combobox to textfield when user clicks "Add client" button.

**Comment by skel35** [comment]
this has been improved in the new design
