### ISSUE TITLE
Do not suppress all duplicate errors

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2384]
Currently we do not show errors that happen multiple times in a row. We should be more specific about this. Sync errors might be ok to suppress but not when a user is trying to create a project with duplicate data. This would not give any feedback on what's happening.

User actions based errors should be always shown. Background errors that are generated multiple times in a row can be hidden.

Also we should maybe detect if an error happens in a certain time period. Like 30 seconds or so then we don't show.

**Comment by skel35** [comment]
login errors are not suppressed anymore
