### ISSUE TITLE
Add the "Group similar time entries" setting to Preferences

### ISSUE THREAD

**Issue by ohare93** [toggl-open-source/toggldesktop#2398]
![image](https://user-images.githubusercontent.com/1471350/36303993-ff1e7272-1305-11e8-949d-f3548fa04250.png)

Grouping Tasks with the same name and project is forced, and is completely ruining my experience of using the Toggl Desktop Client. In the screenshot above I went to sleep twice, and had downtime 5 times in this day. I simply wish to see these in the order they took place in.

E.g: Sleep -> Downtime -> Gaming -> Downtime -> Cycle -> Work -> Downtime -> Work -> Cycle -> Downtime -> Sleep

Instead this shows as:
Sleep (2), Downtime (4), Cycle(2), Work(2), Gaming

**Please make this an option in the preferences**, I simply wish to see what I did at a glance _in order_, and the forced grouping is honestly making me not want to use the Desktop Client any longer.

**Comment by IndrekV** [comment]
This feature is configurable from the webapp "profile settings" page. Just change the setting from web and log out from desktop app and then login again. 

Untick this setting.
![screen shot 2018-02-16 at 17 06 16](https://user-images.githubusercontent.com/842229/36313886-c03c6308-133b-11e8-97ec-f92af137a375.png)

**Comment by jimjamO** [comment]
@IndrekV thank you, that worked. 

**However,** any editable config settings which effect how the application works should be editable in the application itself.
