### ISSUE TITLE
Toggl Desktop for Mac insists that there's no network connection

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#2416]
CASE #661623

A user is reporting that the desktop app is not syncing data for over a week now, constantly telling him that there's no network connection. 

We've tried with uninstalling the app, clearing out local data and re-installing but it made no difference. 

The user claims that there are no network/port restrictions. 

The user sent over the ".log" files from the Kopsik directory

Let me know if you need anything else. 

Thanks

**Comment by IndrekV** [comment]
Logs show that user has proxy configured. TogglDesktop does not work well with certain proxies and this is probably the cause of the issue.

**Comment by VeljkoTN** [comment]
Thanks! I'll get back to the user.

**Comment by VeljkoTN** [comment]
Feedback from the user after I suggested they should apply the "use system proxy settings" setting: 

Hi Veljko,
indeed, proxy settings seem to be a culprit here. However:
- I've been using this proxy and those settings for ages and it used to work
- it only starts to work when I disable proxy and contact toggl.com
directly (contrary to your advice. it was set to ‘’Use system proxy
settings’’ all the time)
FYI the proxy I use is privoxy 3.0.26 on my local host. It must be
interfering with your service somehow.
Thanks for your help!
Francis

Can you help me understand this for future reference, what happened considering he used the same setting for years? 

Thank you!

**Comment by leealexey** [comment]
Having same problem, I don't use proxy, Toggl just stopped to sync today.
ver. 7.4.129

**Comment by IndrekV** [comment]
It seems that there was an issue on the server side for deskop apps (a few hours ago for a short period of time).  Everything should be working now.

**Comment by leealexey** [comment]
Yes, now it works.

**Comment by skel35** [comment]
outdated issue
