### ISSUE TITLE
Windows App not Playing Notification Sounds

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#2442]
Users are reporting that notification sounds are not playing for the desktop app (most recent stable build), even after double-checking settings and volume. 

(NOTE: For any other agents posting case numbers, please list build version and OS for reference)

**Comment by TheSoloJake** [comment]
case/664788 (most recent stable build, Windows 10)

**Comment by sterid** [comment]
I have the same issue with Windows 10. You have to enable Sound Scheme -> Asterisk in Control Panel.

**Comment by TheSoloJake** [comment]
Closing because of age of issue and rebuilding of Windows app
