### ISSUE TITLE
Project and Tags one line autocomplete

### ISSUE THREAD

**Issue by sarneeh** [toggl-open-source/toggldesktop#2445]
It would be awesome to be able to enter into the "What are you working on?" input something like: `styling header component #SomeCompany` where it would autocomplete not only the description, but also the project name after `#`.

This feature is really lacking as it's very frustrating to click around on the UI all the time while you're working with many clients.

**Comment by IndrekV** [comment]
We actually have something similar in mind. Similar to our mobile apps we'd like to give users the possibility to enter the whole data in one input line in format `description @project #tag #tag2`

**Comment by sarneeh** [comment]
@IndrekV Exactly! It's something that I'm really missing as I'm the "keyboard shortcuts" maniac 😄 Do you have this kind of feature somewhere on the roadmap?

**Comment by IndrekV** [comment]
Yes, we have in the list of plans for next 3 months.

**Comment by sarneeh** [comment]
@IndrekV That's awesome! Unfortunately I don't have time right now to help implement this feature, but I can surely help in some testing! Can't wait 😄 If you have already some other issue with this feature, feel free to close this one.

**Comment by bernhof** [comment]
@IndrekV It's been some time now; still not seeing the ability to use hashtags or @mentions in the Windows app. Is this still on the roadmap? In either case, I'd like to add here that this is a feature that I'd really like to see :)

**Comment by AndrewVebster** [comment]
This functionality was implemented in #4436 and #4438 and now is available in Beta - v7.5.347 🎉
