### ISSUE TITLE
Tags not refreshed in client when it updated via API

### ISSUE THREAD

**Issue by popstas** [toggl-open-source/toggldesktop#2513]
Tags not refreshed when it updated externally, via [API ](https://github.com/viasite/planfix-toggl-server) (compared to https://www.toggl.com/app/timer).

Project using HTTP API, `/time_entries/123, { tags: ['tag1', 'tag2'], tag_action: 'add' }`

- Sync not helps
- If I clean cache and relogin, tags refreshing
- If I change tags in web app, tags in client for changed item refreshing

Bug was appeared in 2-9 days before, between Jun 26 and Jul 3.
I think that something changed in API, but in fact data changing and web app show actual data.

toggldesktop 7.4.184, 7.4.197
Tested on Windows 10 and Windows 7

**Comment by EricAlderman** [comment]
I am also seeing this, started happening in last few weeks.  I see a tool to synchronize Toggl entries to Quickbooks Online, and when synced it adds a tag.  These tags are no longer syncing back to Toggl Desktop.  If I Clear Cache, then they all show up again, but then going forward they don't appear.

**Comment by popstas** [comment]
Possible it related to new Android app.

**Comment by stranljip** [comment]
I can also confirm this for the MacOS app version 7.4.221 I am using a Python tool to extract entries from Toggl and write them to JIRA. After success the tool updates the time entry in Toggl with a tag so that it will not be processed again. Setting the tag works fine and it appears in the web application and in the mobile application but not in the desktop app.

**Comment by alphaleonis** [comment]
We're still seing this problem with the latest version (7.4.252).

**Comment by tomvanrossom** [comment]
Same issue here! Tags are not synced :(

**Comment by IndrekV** [comment]
I've looked into this issue and it seems that it's connected to API version v8. Two possible ways to fix this is upgrading the tools that submit tags to API v9 or updating the desktop app to API v9.

Upgrade to API v9 is in the plans for the desktop app, but it means a big syncing rewrite and will take time. This works ok on web app as webapp already uses API v9.

Thank you, everybody, for sharing your feedback on this issue.

**Comment by alphaleonis** [comment]
API v9? The only documentation I can find is for v8, where is the documentation for v9?

**Comment by IndrekV** [comment]
Although a lot of our apps already use v9 it is not publicly advertised. If you have any questions about specific requests let me know and I'll try to help you out.

**Comment by stranljip** [comment]
@IndrekV - can you give an update on the progress with API v9? I was looking into this in order to update my own application but there is nothing available in terms of documentation.

**Comment by popstas** [comment]
Confirm, upgrade to API v9 solved my problem, tag changes in desktop app when I change it from API.
https://github.com/popstas/go-toggl/commit/812cf83b2caaa99cb675b586db2343d167716d52

v9:
```
PATCH https://toggl.com/api/v9/time_entries/123456

[{"op": "remove", "path": "/tags", "value": ["sent"]}]
```
