### ISSUE TITLE
Project Autocompelete open button input needs padding to the right

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2524]
Can be done similarly to this
https://github.com/toggl/toggldesktop/commit/6d8e78b303b238869a88f2adeae90873643d7303

**Comment by IndrekV** [comment]
This needs to re-evaluated with new design iteration.

**Comment by skel35** [comment]
I suppose this is not needed anymore, right @IndrekV ?

**Comment by IndrekV** [comment]
Fixed with new design
