### ISSUE TITLE
Application does not close properly

### ISSUE THREAD

**Issue by KironaDragryph** [toggl-open-source/toggldesktop#2557]
When closing TogglDesktop - right-clicking the icon in the taskbar and selecting "exit" - a few seconds pass and then I get two alerts statying that TogglDesktop has stopped working.  On occasion it only comes up once or not at all, but most often it pops up twice in rapid succession.

This is on Windows 8.1

![image](https://user-images.githubusercontent.com/31082532/44965418-bfeb7d00-aef2-11e8-8647-c0c24dbb4d78.png)

**Comment by IndrekV** [comment]
Might be connected to #2532

**Comment by skel35** [comment]
No issues like this reported lately, so I assume this has been fixed, probably by #2730.
