### ISSUE TITLE
Confusing label "Change duration when changing start time" (EndTime gets updated by itself)

### ISSUE THREAD

**Issue by unmultimedio** [toggl-open-source/toggldesktop#2574]
So, I was about to file an issue because the EndTime gets modified when changing the StartTime, let's say this happens:

- I have my pomodoro set to last 30min
- At 10:00 I start working, but forgot to start tracking
- At 11:00 I remember to start tracking my time (I've been working for 60min)
- I start tracking, and while the tracker is running I set the StartTime to be at 10:00
- The tracker stops (as it should), but the EndTime gets updated to 10:30 (which is not true)

So I started digging in the settings and found the option **Change duration when changing start time**, which does the trick, in the previous scenario the tracker stops but the EndTime is the current time... but the issue is that **Checking it** is what sets the EndTime to *don't* change, so this is very confusing.

My suggestion is, rename that label to something like **Force pomodoro length when changing the start time**. When checked, the EndTime gets updated to meet the lenght of the Pomodoro, and when not, the EndTime remains unchanged.

**Comment by skel35** [comment]
We agree the wording could be improved, but the setting is not specific to Pomodoro entries.
In the new Windows app design, we have tweaked the wording to be more clear and will consider doing it for other platforms as well.
![image](https://user-images.githubusercontent.com/16451391/82919011-25608680-9f7e-11ea-97eb-b247488bd036.png)
