### ISSUE TITLE
Right-click context menu appearing on improper location

### ISSUE THREAD

**Issue by ricotheque** [toggl-open-source/toggldesktop#2591]
When right-clicking on the red Stop button on Windows desktop 7.4.252 beta, the context-menu appears on the wrong location:

![image](https://user-images.githubusercontent.com/5687885/46991134-30fb9280-d137-11e8-93fc-7b4049c4bfe7.png)

On Windows 10

(/conversation/19012965366)

**Comment by skel35** [comment]
same as #3464

**Comment by skel35** [comment]
this particular issue is not relevant for the new design, other positioning issues should be covered by #3464.
