### ISSUE TITLE
Tags With Commas Separate in Desktop App

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#2694]
### 💻 Environment

Platform: MacOS
OS Version: MacOS 10.14
Toggl Version: 7.4.299

### 🐞 Actual behavior
Assigning a tag with a comma inside of it will separate the tag into two tags (pre-comma and post-comma) 

### 💯 Expected behavior
Assigning a tag should assign just one tag. 

### 🔨 Steps to reproduce

1. Edit time entry in app
2. Add a tag with a comma
3. Watch the separation

### 📦 Additional info

![screen shot 2018-12-12 at 6 08 09 pm](https://user-images.githubusercontent.com/25573455/49906910-8e5f4780-fe39-11e8-9a26-4911325d67b6.png)

**Comment by skel35** [comment]
Not happening anymore, verified on macOS 7.5.123, Windows 7.5.146
