### ISSUE TITLE
Archived Projects show up on Project selector

### ISSUE THREAD

**Issue by ricotheque** [toggl-open-source/toggldesktop#2744]
### 💻 Environment
Platform: All desktop platforms

### 📒 Description
When a Project is archived on the web app, this doesn't show up on the desktop app's Project selector, unless the user logs out then logs back in.

### ⭐️ Why do you want this?
Ensures that desktop app users have a seamless experience with the web app.

**Comment by IndrekV** [comment]
This is fixed.
