### ISSUE TITLE
Bundle ToggleDesktop's third-party as submodule on macOS

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#2759]
### 📒 Description
Currently, macOS Toggl project is still depending heavily on 3rd-party libraries, which are bundled directly into source code. 

For instance, MAShortcut, GTM, MKPopoverColorWell, Bugsnag.

I would be great if we move it out from ToggleDesktop's Project and bundle them as submodule project, like Sparkle, CrashReporter do.

It's a macOS part of #2736 

### 💻 Environment
Platform: macOS

### ⭐️ Why do you want this?
- macOS Project is more cleaner and neater 💯 .

**Comment by skel35** [comment]
won't do because we're using CocoaPods
