### ISSUE TITLE
Toggl Desktop MacOS 7.4.330 - Pomodoro/Manual mode issue 

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#2778]
### 💻 Environment

Platform: macOS
OS Version: MacOS Mojave 10.14.2.
Toggl Version: 7.4.330 (stable)

### 🐞 Actual behavior
Similar to #2773 users are not able to create TEs in manual mode or edit a TE while it's running to adjust the duration so that it's longer than the Pomodoro interval. 

Intercom case: 20602902845

### 💯 Expected behavior
The Pomodoro timer should not be triggered by manual edits or time entries created in manual mode. 

### 🔨 Steps to reproduce

1. Pomodoro timer = ON (20min intervals)
2. Start timer
3. While the timer is running change the start time to 45 minutes ago

Instead of changing the start time only, because Pomodoro is ON the end time will change as well to be exactly 20 minutes after the new start time.

**Comment by nidarasheed** [comment]
[case reference](https://support.toggl.com/en/articles/2220803-project-time-estimates)
