### ISSUE TITLE
Archived projects are not displayed in tasks while scrolling down in the tasks list

### ISSUE THREAD

**Issue by cperezabo** [toggl-open-source/toggldesktop#2812]
### 💻 Environment
Platform: macOS
OS Version: 10.14.3
Toggl Version: 7.4.330

### 🐞 Actual behavior
Archived projects are not being displayed in task items.

### 💯 Expected behavior
Archived projects names should be displayed like in a normal task, because it doesn't mother if the project is archived. If the task is being displayed in tasks list, the project name have to be displayed also.
In fact, it works well in web app and in mobile.

### 🔨 Steps to reproduce
1. Create a task with a project.
2. Archive that project.
3. Go to tasks lists. No project info.

### 📦 Additional info
<img width="352" alt="screen shot 2019-02-15 at 10 17 13" src="https://user-images.githubusercontent.com/3604722/52859233-ed2b9080-310a-11e9-903f-5ea6d21cc6c9.png">

**Comment by cperezabo** [comment]
I've noticed project is also empty in task edit view, but it works well in web app and mobile app

**Comment by NghiaTranUIT** [comment]
Thank for this report. We're going to solve this problem soon since the Mobile and Web version are already done 👍 

For Desktop team: [Conversation](https://toggl.slack.com/archives/C029WCX0T/p1550237971079500)

**Comment by NghiaTranUIT** [comment]
Duplicated with https://github.com/toggl/toggldesktop/issues/2335 and https://github.com/toggl/toggldesktop/issues/2744

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23779567872)

**Comment by NghiaTranUIT** [comment]
Sorry, but I couldn't reproduce it anymore. 

Here are my steps:
1. Start a new TE and create a new Project.
2. Start and stop a couple of time to create more TEs
3. Go to Web Dashboard and archive this project
4. Go back to the app, and try to sync, log-out, login, clear cache, and login back to this account
5. The archived projects are still associated with TimeEntries

- On the other hand, I checked the local database, and the active value of this project is 0 -> Mean it marks as an archived project

In fact, I couldn't reproduce in the very old build 7.4.330 and the latest 7.4.1012.

<img width="650" alt="Screen Shot 2019-09-25 at 15 29 07" src="https://user-images.githubusercontent.com/5878421/65583604-b7585f80-dfa9-11e9-9e6c-3b73a7d130d1.png">
<img width="324" alt="Screen Shot 2019-09-25 at 15 29 44" src="https://user-images.githubusercontent.com/5878421/65583606-b7585f80-dfa9-11e9-952f-6221cacca8d6.png">

## Summary
I suppose that I'm missing some steps to trigger this bug.

**Comment by IndrekV** [comment]
This has been fixed for some time now.
