### ISSUE TITLE
Look into possibility of adding HomeBrew Cask for distribution

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2830]
### 💻 Environment
Platform: macOS

### 📒 Description
It would be another way to distribute our mac app

**Comment by IndrekV** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by skel35** [comment]
It is being distributed via homebrew cask already (3rd party supported) https://formulae.brew.sh/cask/toggl-track.
If taking ownership of updating the cask makes sense for us, we'll consider it separately.
