### ISSUE TITLE
Yubikey Google login doesn't work

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#2835]
I appear that a similar issue existed in 2015 related to the windows app #1361

### 💻 Environment

Platform: Linux x86_64
OS Version: waiting to get a confirmation of what version of Ubuntu he's on, he said he just had a fresh install to try on a different laptop so it could be latest, didn't see that info in the log file
Toggl Version: linux_native_app/7.4.122

### 🐞 Actual behavior
The user is no longer able to log in after clearing cache in the app. Their credentials work fine with the web app.

### 📦 Additional info
Logs can be found in **[the Intercom case 🔗](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/20926903023)**

**Comment by MartinBriza** [comment]
This is actually an issue with Google not supporting Yubikey login with any other browser than Chrome directly. We're embedding a "custom browser" (actually QtWebengine - Blink renderer) with the desktop app that handles Google login for us (without actual full support for all the features of Google login)

**Comment by ricotheque** [comment]
Hey @MartinBriza thanks for the update!

Is there any workaround the user can try in the meantime?

**Comment by MartinBriza** [comment]
I think the workaround for this is using an app-specific password for Toggl in the Google account. I can't tell for sure though.

**Comment by skel35** [comment]
should be fixed by #4298, please reopen if it's not the case
