### ISSUE TITLE
Add releasing to Homebrew Cask to the stable release flow

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2871]
### 💻 Environment
Platform: macOS

### 📒 Description
Seems to be an easy and comfortable way to also distribute Toggl Desktop to our users

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/toggl.rb

**Comment by skel35** [comment]
It is being updated automatically by 3rd party https://formulae.brew.sh/cask/toggl-track.
Let's revisit it when we think that taking ownership of updating it makes sense for us.

**Comment by shulter** [comment]
https://formulae.brew.sh/cask/toggl-track is not listed anymore. Please maintain a brew fomulae, it would make deployment on a large set of devices much easier.
