### ISSUE TITLE
App slows down after longer usage

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#2912]
### 💻 Environment
Platform: macOS
Toggl Version: 7.4.365

### 🐞 Actual behavior
App should not slow down no mater how much usage

### 💯 Expected behavior
After longer use without restart (few days) all the actions in the app start to slow down.

### 🔨 Steps to reproduce

1. Do a lot of actions (write a script that does it). Check out command `make uitest` that does use the scripting to do UI actions
2. Detect if app slows down

### 📦 Additional info
[Intercom case 🔗](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2214719/conversations/21500838265)

>the slowing feels like it accumulates over time. If i quit the app and restart it, the slowness disappears, but builds up over a few days

The issue can be connected to some memory leaks that make the app slow down over time.
We should probably create a testing script that does a lot of actions and tracks the time that it takes for the actions to execute.

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26856269279)

**Comment by skel35** [comment]
The original issue referred to some old memory leaks that are not relevant anymore.
@nidarasheed The recent one is the same as #4019 and is now fixed in the latest 7.5.123 beta.
