### ISSUE TITLE
Blurry Text

### ISSUE THREAD

**Issue by Michelle112** [toggl-open-source/toggldesktop#2935]
### 💻 Environment

Platform:  Windows

OS Version: 

windows_native_app/7.4.345-obm-87-obm-98-obm-99-obm-101 
Toggl Version:  Version: 7.4.345

### 🐞 Actual behavior

Certain lines of text appear blurry.

### 💯 Expected behavior

Text appears clear

### 📦 Additional info

Case: /conversation/21775004221
<img width="1039" alt="Blurring" src="https://user-images.githubusercontent.com/19910107/56790270-be482f80-67c9-11e9-9956-fb434cde0ec0.png">

**Comment by skel35** [comment]
Unfortunately, the fix introduced other side-effects.
Reverted the fix in master.
Reopening the issue until a better fix is found.
