### ISSUE TITLE
Mac Sync issue

### ISSUE THREAD

**Issue by nicktoggl** [toggl-open-source/toggldesktop#3049]
As per https://toggl.slack.com/archives/C029WCX0T/p1561608764280900

### 💻 Environment
Platform: macOS
OS Version: 
Toggl Version: 

### 🐞 Actual behaviour
"The mac software does not sync after it wakes. I have to quit the app and then it will sync. Forcing sync in the menu and/or waiting does not help.

It happens every time for me. I leave the app open and so a timer is often running. When I wake the computer the old timer is running and the app will not sync. I have deleted and reinstalled the app, but no change.'

### 💯 Expected behaviour
Data should sync immediately

### 🔨 Steps to reproduce
I haven't been able to replicate but;

1. run desktop app with timer and leave so computer goes to sleep
2. wake from sleep and check syncing
3. if it fails, try to close app and reopen, does it now sync?

### 📦 Additional info
[Initial Case and logs](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/22609146420)

**Comment by skel35** [comment]
Can't reproduce anymore.
Please reopen if this is still an issue.
