### ISSUE TITLE
Google Login claims invalid password in Linux Mint

### ISSUE THREAD

**Issue by MartinBriza** [toggl-open-source/toggldesktop#3095]
### 💻 Environment
Platform: Linux
OS Version: Linux Mint Tessa (19.1)
Toggl Version: toggldesktop_7.4.459_amd64.deb

### 🐞 Actual behavior
When logging in with a Google account, the app claims the email or password is wrong.

### 📦 Additional info
There's probably a window with more information for a split second.
https://app.intercom.io/a/apps/ayixs927/conversations/22667832385

**Comment by lise-toggl** [comment]
[linking again](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/22667832385) so intercom will track this

**Comment by IndrekV** [comment]
Unable to reproduce the login issue. Maybe user has to re-enable the Google login from webapp.

**Comment by MartinBriza** [comment]
This seems like a problem that is resolved by clearing the cache and cookies in the embedded browser we have inside our Linux app. I had an issue with the dialog showing for a split second too and it has disappeared after that fix. I'm adding this issue to the Google Login PR that contains the commit in question.

**Comment by MartinBriza** [comment]
I'm convinced this issue is now fixed. I have tested the app on Linux Mint Tessa with Cinnamon and it works as expected.
