### ISSUE TITLE
Apps get tracked twice on Windows [Timeline]

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3099]
### 💻 Environment
Platform: Windows
OS Version: Windows 10.0.17763
Toggl Version: 7.4.451

### 🐞 Actual behavior
Looking at my recorded timeline data, I can see that some 15-minute intervals contain more than 15 minutes of tracked time, approx. up to 30 min. When looking at entries in detail you can guess that there are duplicate entries, with a few seconds of difference in duration. 
![image](https://user-images.githubusercontent.com/16451391/61468182-8a724580-a985-11e9-8c3e-bd11624c7b2f.png)

### 💯 Expected behavior
Each 15-minute interval should not contain more than 15 minutes of tracked data. There should be no duplicates.

### 🔨 Steps to reproduce
Check "Record timeline".
Happens occasionally and, I think, on both x86 and x64 versions (though I might've gotten auto-updated from x64 to x86 without noticing).

I thought it might be happening due to launching the app both installed one and from IDE many times during the day, but I've noticed it happened even when I don't have any development environment open.

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26815065282)

**Comment by atsvirchkova** [comment]
I don't know how this happens. But our activity tracker is lying badly (Windows for sure, not sure about other platforms). Here is the screens for the same chunk, first - right after activity tracking, second - after app restart.
