### ISSUE TITLE
App does not switch edit view color mode

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3160]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14
Toggl Version: master 

### 🐞 Actual behavior
Most of the app is updated but the Edit view is not

### 💯 Expected behavior
Edit view should also re-render based on the selected theme

### 🔨 Steps to reproduce

1. Open app
2. Change them (light/dark)
3. Check that the whole app has been changed but the edit popup background is the same as before

### 📦 Additional info

In the screenshot, I switched from Dark->Light and the edit view is still dark

![Screenshot 2019-07-30 at 07 27 08](https://user-images.githubusercontent.com/842229/62100800-c10c6200-b29b-11e9-81b6-3ef97855d6f7.png)

**Comment by NghiaTranUIT** [comment]
I tried couple approach to fix it but it's not easy at all.

## Reason
By default, the NSPopover will use Vibrant Appearance for all Appearance of sub-views (Including the TextFields) and we're use custom background.
This combination results in weird issue like this photo:
<img width="322" alt="Screen Shot 2019-08-14 at 18 51 41" src="https://user-images.githubusercontent.com/5878421/63019128-ba4d3400-bec4-11e9-9086-85748e103403.png">

## Current Solution
Technically, I'm intentionally overriding the Appearance of NSPopover in [NoVibrantPopoverView](https://github.com/toggl/toggldesktop/blob/master/src/ui/osx/TogglDesktop/Feature/TimeEntryEditor/NoVibrantPopoverView.swift) to make sure that VibrantLight and VibrantDark is not use.
However, this approach leads to this issue, which is the Appearance doesn't change when the System's changed

## Alternative
I suppose that we **shouldn't** override the NSAppearance from NSPopover and find the way to disable Vibrant for all subclass (https://developer.apple.com/documentation/appkit/nsview/1483793-allowsvibrancy)

**Comment by IndrekV** [comment]
I just tested it once more. If you restart the app the colors are correct. I don't think we need to do an override to disable Vibrant. Do you think there is a way to just re-initialize the edit popup when the theme change event is triggered. Similar how the popup window is initialized on app start.

**Comment by NghiaTranUIT** [comment]
yes, it's possible. I have take a look on this approach 👍

**Comment by nicktoggl** [comment]
[user case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/27303278030)

**Comment by skel35** [comment]
[case link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/27525024948)

**Comment by edtamayo** [comment]
[Case link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/27525024948)

**Comment by edtamayo** [comment]
[Case link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481300012437)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481303543855)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481304663674)

if the macOS is set to Auto, the app itself is in the dark mode but the edit view remains in the light mode
