### ISSUE TITLE
Record activity toggle UI

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3185]
### 💻 Environment
Platform: macOS

### 📒 Description
Implement a nice-looking toggle switch for Record activity (design details in Zeplin)
![image](https://user-images.githubusercontent.com/16451391/62618690-8353ad00-b91d-11e9-82e8-6c3f0e30a843.png)

**Comment by NghiaTranUIT** [comment]
We decided to not implement the new UI Switcher on the Timeline since it's non-standard control in term of macOS and iOS. Ref: https://toggl.slack.com/archives/C029WCX0T/p1567580700003500?thread_ts=1567577862.001600&cid=C029WCX0T
