### ISSUE TITLE
parsing time "null" ... cannot parse "null"

### ISSUE THREAD

**Issue by claytonrcarter** [toggl-open-source/toggldesktop#3201]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.13.6
Toggl Version: 7.4.484

### 🐞 Actual behavior

When I open the TogglDesktop client, the app displays an error message reading: `parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"`. The error can be dismissed and the app continues to work w/o issue, but this message is shown everything time the app is started. (ie closing the window and reopening it will not show the error, but closing the whole app and relaunching it will show the error.)

This is not new, it's been happening for quite a while (many months). I assume that at some point in the past, I was able to save an invalid time entry, but I don't see any way to find and fix that entry. In the interim, the app tells me about it every time I open it. 😄 

Here is a screenshot:
![Screen Shot 2019-08-12 at 6 45 12 AM](https://user-images.githubusercontent.com/1420419/62860240-878d1b00-bccd-11e9-8688-d82892001de7.png)

### 💯 Expected behavior

No error message, or if there is corrupt/incorrect data somewhere, a link to fix the bad entry.

### 🔨 Steps to reproduce

Well, *I* can reproduce it just by closing and relaunching the app. I'm not sure how someone else would go about reproducing it, though.

### 📦 Additional info

*None*

**Comment by IndrekV** [comment]
I'd say contact the support and then send the local database that way we can see what entry is broken and how it could have happened.

**Comment by lise-toggl** [comment]
[file received](https://toggl.slack.com/archives/C029WCX0T/p1567046337037500)

**Comment by claytonrcarter** [comment]
Clarification: not sure how I got this wrong, but I was running 7.4.373 when I filed this report, not 7.4.484. That said, I just upgraded to 7.4.484 and it is still happening. Thank you.

**Comment by claytonrcarter** [comment]
Sorry to pester, but after the update to 7.4.484, this has gotten worse. In 7.4.373, the prompt would show up once and then would stay gone after I closed it. Now, in 7.4.484, it pops up every time I start **and** stop a timer. (ie when I press the red "stop" button on a current timer and then press the green "play" button on a previous timer)

**Comment by claytonrcarter** [comment]
Hi again. I just updated to 7.4.1092 and the error message has changed to "Data that you are sending is not valid/acceptable". As I mentioned above, it is displayed at all times and if the error id dismissed, it comes right back if I take any action. (start/stop timer, etc)

![Screen Shot 2019-12-20 at 11 04 21 AM](https://user-images.githubusercontent.com/1420419/71267547-d6505e80-2318-11ea-98b4-eccd41d5e6d2.png)

**Comment by claytonrcarter** [comment]
FWIW, one of the recent UI updates seems to have exposed the entry causing this issue by floating it at the bottom of the toggl window. This allowed me to select it and delete it. So ... fixed! Thanks!
