### ISSUE TITLE
Add support for Apple login

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3249]
### 💻 Environment
Platform: macOS

### 📒 Description
When using third party authentication Apple wants us to also add appleID based login.

https://developer.apple.com/documentation/authenticationservices. 

It’s only supported for macOS 10.15+, which is really bad.
The potential solution for all desktop platform is that we use webview-based  https://developer.apple.com/documentation/signinwithapplejs

Main discussion in https://github.com/toggl/discussions/issues/70

**Comment by NghiaTranUIT** [comment]
All done at https://github.com/toggl-open-source/toggldesktop/pull/3879
