### ISSUE TITLE
Project colors change intermittently 

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#3282]
### 💻 Environment

Platform:  MacOS
OS Version:  OS X 10.14.6
Toggl Version:  Dev, 7.4.527

### 🐞 Actual behavior

The user has set dark blue as the color for a project and it shows as light blue sometimes. Pics below. 
![image](https://user-images.githubusercontent.com/49634673/64322884-d41dfa80-cfdc-11e9-8ba2-bf7781f5afb7.png)
![image](https://user-images.githubusercontent.com/49634673/64322893-d6805480-cfdc-11e9-843f-5b7b5e066e5b.png)

### 💯 Expected behavior

In dark mode, a color should change to make it easier to view since some colors are illegible on dark mode, but shouldn't change back and forth on it's own once set. 

### 🔨 Steps to reproduce

N/A

### 📦 Additional info

[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/21917711663)

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24745135774)

**Comment by NghiaTranUIT** [comment]
Close ticket since the revamp Project Color feature is on progress
