### ISSUE TITLE
Timeline UI improvements - visual time tracking

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3288]
### 💻 Environment
Platform: macOS

### 📒 Description

When testing the timeline in multiple times I felt like I wanted to create time entries right in the vertical time entries view of the timeline tab. How would it work?

When you click on an empty space in the vertical list of entries the edit popup opens with start time set as the point where you click. We can round it by 15 minutes.

This is the first implementation idea and should be implemented with the first release of the Timeline UI

Second part would be the drag functionality where user can drag the size of the item they want. This will be done later as a separate development.

**Comment by NghiaTranUIT** [comment]
Done Part 1 of this ticket 🌮

**Comment by skel35** [comment]
Split into more specific issues:
#3832
#4111

And more to come as a result of the cross-team Visual Time Tracking project
