### ISSUE TITLE
Create a New project button is blurred on external monitor

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#3313]
### 💻 Environment

Platform:  MacOS

### 📒 Description

When using an external monitor (benq 22" 1080p), the Create a New Project button for Toggl Desktop is blurry for the user. Screenshot attached.
![image](https://user-images.githubusercontent.com/49634673/64844987-8465b180-d622-11e9-88f2-256d3b63a8e9.png)

I sent him a screenshot of the app on my macbook pro, and he says his laptop shows it fine too, it’s just the external monitor that blurs it (probably because it’s higher res?). Wanted to let you guys know in case it’s something you weren’t aware of.  
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23629326919)

**Comment by IndrekV** [comment]
Similar issue with "Add new tag" for some reason with some length of text it is blurry and when removing a character it's not blurry anymore. Maybe something to do with the alignment logic or constraints.

![mac-tag-select-blurry](https://user-images.githubusercontent.com/842229/66465861-555c2780-ea8a-11e9-8252-5f381d62c3a8.gif)
