### ISSUE TITLE
Dark mode on Windows

### ISSUE THREAD

**Issue by archmunky** [toggl-open-source/toggldesktop#3319]
### 💻 Environment
Platform: Windows

### 📒 Description
Are there any plans to implement a dark mode feature in Windows?

### ⭐️ Why do you want this?
I use dark mode as much as I can due to health issues (migraines).  So a dark mode could be considered an accessibility feature.   Having a dark mode for this app would also match other programs on desktop.

**Comment by IndrekV** [comment]
We're doing a redesign of the windows app and dark mode is planned. We plan to release new design in the last quarter of 2019.

**Comment by Abdulbaqi-Alshareef** [comment]
> 
> 
> We're doing a redesign of the windows app and dark mode is planned. We plan to release new design in the last quarter of 2019.

Good news, But I couldn't find its repo or branch because I may give feedback or contribute some code

**Comment by IndrekV** [comment]
It's in the very beginning. Designers are gathering ideas and we'll kick it off next week. No results on it yet.
