### ISSUE TITLE
Projects dropdown empty on Mac

### ISSUE THREAD

**Issue by lise-toggl** [toggl-open-source/toggldesktop#3324]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14
Toggl Version: 7.4.1000

Laptop with external monitor.

### 🐞 Actual behavior
When the Toggl app is on the laptop screen, the projects dropdown is empty ([video in ticket](https://app.intercom.io/a/apps/ayixs927/inbox/conversation/23712046035#part_id=comment-23712046035-3764903313)). When the app is on the external monitor, it is populated ([video](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/23712046035#part_id=comment-23712046035-3764908156))

### 💯 Expected behavior
The projects dropdown should show the correct projects all the time.

### 🔨 Steps to reproduce

Please see video links above.

### 📦 Additional info
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/23712046035)

**Comment by VeljkoTN** [comment]
[user report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23708029360)

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24132452082)

**Comment by skel35** [comment]
Not yet clear whether #3504 fixed the issue. To be verified.

**Comment by nidarasheed** [comment]
[Case Reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24652534331)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24860002265)

**Comment by cmheisel** [comment]
Tested this on 7.4.1092 beta and it's still occuring

**Comment by NghiaTranUIT** [comment]
After preliminary investigation, this issues would be addresses in https://github.com/toggl-open-source/toggldesktop/pull/3627

**Comment by skel35** [comment]
Fixed by #3627
