### ISSUE TITLE
When selecting tag the focused item selection should not jump to top

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3334]
### 💻 Environment

Platform: macOS

### 🐞 Actual behavior
When I select a tag by pressing Enter it selects the tag and moves the focused item to the top.

### 💯 Expected behavior
When tag is selected the focused element should remain the same so the user can continue moving around in the list in the same position.

### 🔨 Steps to reproduce

1. Open tag dropdown
2. select any tag with keyboard (By pressing enter)
3. Press Down to continue down
4. See that the selection jumped to top and you have to start all over again

### 📦 Additional info
![mac-tag-select](https://user-images.githubusercontent.com/842229/65245346-2428b100-daf5-11e9-9300-b8283795df57.gif)

**Comment by NghiaTranUIT** [comment]
Related to https://github.com/toggl-open-source/toggldesktop/issues/3485
