### ISSUE TITLE
Excessive Reminders

### ISSUE THREAD

**Issue by Spurlos** [toggl-open-source/toggldesktop#3368]
### 💻 Environment

Platform: Linux
OS Version: Ubuntu 19.04
Toggl Version: 7.4.528

### 🐞 Actual behavior

Leaving toggl running for a while produces multiple reminders to track time.
![image](https://user-images.githubusercontent.com/667533/65773153-5f099500-e144-11e9-8657-ca96d7a0c940.png)

### 💯 Expected behavior

Only one reminder is enough if it wasn't dismissed
![image](https://user-images.githubusercontent.com/667533/65773209-83657180-e144-11e9-8205-207aafeefa0c.png)

### 🔨 Steps to reproduce

1. Set reminders to track time (ex. 10 mins)
2. Leave the PC for 30 mins
3. When you return you will get 3 reminder windows stacked one atop another and would required to dismiss each individually
(BTW two buttons "Ok" and "Cancel" are redundant - there is nothing to cancel - its a reminder, a simple "Dismiss" would be enough) 

### 📦 Additional info

Using Unity 7 as DE, if that somehow affects the messages.

**Comment by skatkov** [comment]
Reproduced the same issue in Arch Linux (manjaro)

**Comment by MartinBriza** [comment]
Now tracking reminders are sent as regular notifications so this is probably fixed now.

**Comment by Spurlos** [comment]
Yep. I have since moved to Gnome and Toggl notification here works nicely.

**Comment by MartinBriza** [comment]
Thanks for confirming it's working fine for you! :)
