### ISSUE TITLE
Website works but desktop app can't connect

### ISSUE THREAD

**Issue by TomDobbelaere** [toggl-open-source/toggldesktop#3379]
### 💻 Environment

Platform:  Windows
OS Version:  Windows 10 1809
Toggl Version:  7.4.1015

### 🐞 Actual behavior

In the middle of tracking time, Toggl Desktop suddenly stopped syncing and gave me a little exclamation mark next to the time entry. If I clicked the sync button, it would just spin forever. I have internet, I went on toggl.com to go to the timer and it all works, just not in Toggl Desktop.

I uninstalled and reinstalled the latest Toggl 7.4.1015 but now I can't even login, I get this:
![image](https://user-images.githubusercontent.com/13522621/65968279-3397ea80-e463-11e9-9a35-202c7a03ff9c.png)

I allowed Toggl through the firewall, this hasn't been an issue until now, which is odd. 

### 💯 Expected behavior

Logging in should work, tracking time should sync.

### 🔨 Steps to reproduce

1. Be me

**Comment by IndrekV** [comment]
We've temporarily blocked the desktop apps as we discovered a sync issue with put a lot of stress to the backend. We're working on a fix and will resume the normal behavior soon. Thank you for reporting.

**Comment by liamvictor** [comment]
I have the same issue with Windows 10 desktop, 7.4.10.15 build. 

Please let me know if you need logs or anything. Thanks.

Future suggestion - have a mechanism to provide bespoke error messages as I'm sure many of us have spent quite some time trying to log in and out before seeing this thread. C'est la vie. I still love toggl!

**Comment by AshenCZ** [comment]
This really does need more visibility. I have just spent 30 minutes trying to discover the issue, deleting the local db file, reading the log file on both computers and re-installing the application.

**Comment by vedr4n** [comment]
Sorry about that @AshenCZ! 

At the moment, the best we can do is announce problems such as this on [Twitter](https://twitter.com/toggl/status/1179020089380749313). In the future, we're hoping to have/create a proper Status page that lists the availability of all services.

**Comment by francisprovost** [comment]
@vedr4n I think it's more the way the error message is written that cause the confusion. The "Are you online?" make me think that maybe there's a problem on my end. "Can't reach the server" would be better in my opinion. 

Anyway good luck with the fix!

**Comment by vedr4n** [comment]
@francisprovost Seems like this is client-specific. macOS app displays this message. 
![Screen Shot 2019-10-01 at 17 22 10](https://user-images.githubusercontent.com/19473351/65976226-1ae20180-e470-11e9-931a-7adf9f98860e.png)

PS: **Desktop sync service has been restored with rate limiting**. Logging in and syncing should work, just slower than usual (for now).

**Comment by liamvictor** [comment]
> Sorry about that @AshenCZ!
> 
> At the moment, the best we can do is announce problems such as this on [Twitter](https://twitter.com/toggl/status/1179020089380749313). In the future, we're hoping to have/create a proper Status page that lists the availability of all services.

Twitter is blocked on my computer (as are all social websites).

**Comment by Pytlicek** [comment]
Still not syncing :/
I see only these 2 messages :

![Screenshot_2019-10-01_21 00 28](https://user-images.githubusercontent.com/1430522/65992033-b2eee380-e48e-11e9-9409-241d347144a0.png)
![Screenshot_2019-10-01_21 01 28](https://user-images.githubusercontent.com/1430522/65992035-b2eee380-e48e-11e9-8d91-036bce3d0f88.png)

**Comment by NghiaTranUIT** [comment]
@Pytlicek let try the hotfix  [7.4.1022](https://toggl.github.io/toggldesktop/#mac). This limit issues will be removed soon as soon as we carefully investigate it.

**Comment by kapooostin** [comment]
I just installed 7.4.1022, still `492` and 
![image](https://user-images.githubusercontent.com/467097/65994801-dde03400-e49c-11e9-87ad-f6750f89a2c9.png)

**Comment by mynameisbogdan** [comment]
The same here with `7.4.1022`.

<img width="420" alt="Screen Shot 2019-10-01 at 22 54 57" src="https://user-images.githubusercontent.com/707714/65995614-8f339980-e49e-11e9-9531-25c19a6d30dc.png">
<img width="243" alt="Screen Shot 2019-10-01 at 22 54 39" src="https://user-images.githubusercontent.com/707714/65995631-96f33e00-e49e-11e9-928a-583fe430fb37.png">

**Comment by sean-mystyle** [comment]
Any updates?  

I have not been making lots of requests at all.  If I try to "sync" my timelog toggle desktop error notification comes back with "429 Too Many Requests" like others have noted here. 

 It's 1PM Pacific Time, in the middle of the work day, so we're relying on time tracking as usual.  Maybe the weekend would have been a better time to disable the API?

**Comment by kapooostin** [comment]
chrome extension works fine

**Comment by 23tux** [comment]
Still not working... all our devs are using the desktop app, and entries from the last 18h or so aren't synced. 

@IndrekV do you have an idea when it will be working again? If it's taking longer we have to switch to the web app and sync the data by hand, so that we can create our invoices based on that times

**Comment by IndrekV** [comment]
We're keeping desktop apps rate limited as long as we have enough users updated to latest version. The previous version had an issue that made it re-sync all the time even when there was no need for it. This overloaded our servers and we decided to block desktop apps so all other apps could work without problems. We released a fixed version (7.4.1022) yesterday within about 2 hours of detecting the issue and are pushing everyone to update so we can remove the faulty version from the market so to say.

Rate limited means that if certain sync requests are done within a minute it will delay the sync by one minute. So sync works it's just delayed. 

We are constantly monitoring the situation and will remove the rate limit the moment it is possible.

Thank you everyone for the reports, feedback and most of all patience with this unfortunate situation.

**Comment by tumb1er** [comment]
@IndrekV FYI: current linux deb version on [website](https://support.toggl.com/en/articles/2410832-toggl-desktop-for-linux) is still 7.4.528. How to get latest?

**Comment by IndrekV** [comment]
For Linux version 7.4.528 is the latest, we did not release the version with issues on Linux. Rate limiting in the backend is being removed step by step so everything should return to normal soon.

**Comment by skel35** [comment]
Closing the issue as it relates to a specific incident during October 1st-3rd.
More info here https://toggl.com/blog/toggl-desktop-issue-october-2019.
