### ISSUE TITLE
Timeline UI improvement

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3380]
### 💻 Environment
Platform: macOS - Timeline branch

### Acceptance Criteria
- [x] Hover state on tabs - only text color should change (no background change, it looks very outdated)
- [ ] ~Toggle for record activity has completely different styles~ -> Use default \NSSwitch
- [x] + and - buttons should appear only on hover (important).
- [x] Spacing in calendar button feels odd - depending on the date spacing between characters is different. As if there was predetermined space for it :thinking_face:
- [x] Text in the empty timeline 'Turn on the activity...' should be centered at all times (when resizing the window)
- [ ] ~There is some kind of bug in the calendar button - sometimes when I click on it, text gets highlighted and I cannot neither outclick nor open the date picker :face_with_monocle:~ -> It's correct behavior https://github.com/toggl/toggldesktop/issues/3380#issuecomment-538350933
- [x] Date picker has different styling - when it comes to width (should be as wide as button), pointer (no pointer needed, should be flat), button active state
Please, see this screen in zeplin for details:
https://zpl.io/bPPXQKM
- [ ] ~Styles on TE on hover are totally not in sync with designs (please, see Zeplin for reference https://zpl.io/VOdw4kj)~ -> Use default NSPopover

**Comment by NghiaTranUIT** [comment]
## Notes
1. Styles on TE on hover are totally not in sync with designs (please, see Zeplin for reference https://zpl.io/VOdw4kj)
- Design
<img width="301" alt="Screen Shot 2019-10-04 at 15 16 15" src="https://user-images.githubusercontent.com/5878421/66192124-03965480-e6ba-11e9-8501-55670fd895a2.png">

- macOS default NSPopover
<img width="392" alt="Screen Shot 2019-10-04 at 15 16 06" src="https://user-images.githubusercontent.com/5878421/66192125-03965480-e6ba-11e9-8a0a-0c0b4ce7a4e2.png">

Both UI controls are totally different, but it's same concept -> To present a data without disrupting the users's thought by opening the Hover view. 

I would like to elaborate what is pros/cons in order to build this views:

## Use default NSPopover 
### Pros
- It's a default macOS control, and it makes the users feel like their home (https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/popovers/)
- Arrow to know which Time Entry is being selected.
- We have a plenty of free features:
For instance:
- Less code
- The Hover windows has a lot of built-in feature: Able to scroll to the selected item, present on left / right / up / down direction depend on the space, Visual Background View (Blur background), animation, click outside to dismiss, ...

### Cons
- Impossible to customize the appearance (Ex: remove the corner, shadows, arrow, border color, ...)
- Not 100% match the design

## Implement our own Popover Windows
### Pros
- 100% match the design

### Cons
- A lot of works and error-prone
- Have to implement all free features from NSPopover

## Question 1: 
We should decided which approach we should do: Keep it as it is (NSPopover) or implement our control?

**Comment by IndrekV** [comment]
Let's keep NSPopover. Thank you for all the details.

**Comment by NghiaTranUIT** [comment]
The same with Calendar Popover too.

- Popover
<img width="360" alt="Screen Shot 2019-10-04 at 17 32 49" src="https://user-images.githubusercontent.com/5878421/66201226-08183880-e6cd-11e9-8268-9c31e855a82b.png">

- Design
<img width="326" alt="Screen Shot 2019-10-04 at 17 32 23" src="https://user-images.githubusercontent.com/5878421/66201232-11a1a080-e6cd-11e9-90af-86df136b6f41.png">

## NSPopover
- There is no way to hide the arrow button.

**Comment by NghiaTranUIT** [comment]
> There is some kind of bug in the calendar button - sometimes when I click on it, text gets highlighted and I cannot neither outclick nor open the date picker :face_with_monocle:

When we select a day or month or year, the user could quickly type the number that want, so we shouldn't present the Calendar Popover. The Date Text Field is actually a [default control of Date Picker ](https://developer.apple.com/design/human-interface-guidelines/macos/selectors/date-pickers/).

The only way to open the Calendar is that we click on The Day name label.

Therefore, it's correct behavior 👍 

![2019-10-04 17 51 58](https://user-images.githubusercontent.com/5878421/66202582-567b0680-e6d0-11e9-9a90-eda43be579d6.gif)

**Comment by NghiaTranUIT** [comment]
## Bug Report
- [ ] Timeline Entry is overlap incorrect way when two TE have near Start / End time (https://toggl.slack.com/archives/CH7DV7VSR/p1570433380004900)
- [ ] Change the start Time of TE make it moves to yesterday (https://toggl.slack.com/archives/CH7DV7VSR/p1570434885007300)

**Comment by NghiaTranUIT** [comment]
- [ ] Can't open the Editor in a running TimeEntry if we are in Timeline tab

**Comment by NghiaTranUIT** [comment]
All done 👍
