### ISSUE TITLE
Colors in text field on Linux

### ISSUE THREAD

**Issue by donquixote** [toggl-open-source/toggldesktop#3385]
### 💻 Environment

Platform: Linux
OS Version: Ubuntu MATE 18.04
Toggl Version: 7.4.528

### 🐞 Actual behavior
Colors as in the screenshot
![toggl-colors-linux](https://user-images.githubusercontent.com/150032/66033990-ac04b700-e508-11e9-8e4b-b6cd2ecb9fb9.png)

### 💯 Expected behavior
Fully white background of the text field

### 🔨 Steps to reproduce
Open TogglDesktop
Perhaps the color scheme on Linux MATE might play a role.
But the Toggl app should be independent of the color scheme.

### 📦 Additional info
This was ok in a previous version.

**Comment by MartinBriza** [comment]
This is very likely to be fixed by #3421 that got in the current beta release (v7.4.1102)
