### ISSUE TITLE
Idle detection doesn't kicks in

### ISSUE THREAD

**Issue by Spurlos** [toggl-open-source/toggldesktop#3390]
### 💻 Environment

Platform:  Linux
OS Version:  Ubuntu 19.04 (Unity 7)
Toggl Version:  7.4.528 deb

### 🐞 Actual behavior

Previous stable version of deb package had this popup with idle detection and 4 options on what to do with the idle time. Now its not popping up and the timer continues to go for the active record. This greatly hinders the workflow with Toggl. (running out for a lunch, without stopping the time record, just to find out that it still ticks when you're back)

### 💯 Expected behavior

Expected to work just like in previous version - popup when idle time detected:
![image](https://user-images.githubusercontent.com/667533/66127513-8ce35380-e5f4-11e9-816d-34355059544f.png)

### 🔨 Steps to reproduce

1. Set Idle detection in Preferences to 5 mins
2. Start tracking a record.
3. Leave computer idle for time set in step 1.
4. Notice that even after 5 mins there is no popup with actions to take on the idle time tracked (Discard and stop\Discard and continue\Continue\Add as a new record)

**Comment by MartinBriza** [comment]
There's no popup at this point but a regular notification and the notice about when you left gets rendered right in the main window. This should be fixed at this point (or at least from my point of view it seems to work fine) however please feel free to reopen this bug if it still doesn't work as expected on your setup (and please make sure to report what distribution, desktop environment and display server - Xorg/Wayland you use). Thank you.

**Comment by o771e** [comment]
I have the same issue.
