### ISSUE TITLE
Editor window - selected task not shown beside project name

### ISSUE THREAD

**Issue by cyress** [toggl-open-source/toggldesktop#3393]
### 💻 Environment
Platform: macOS
OS Version: macOS 10.14
Toggl Version: 7.4.1023

### 🐞 Actual behavior
Edit an time-entry in the editor window, click on the "Select project"-field and select a task below a project, the task-name is not shown after after the selection.

### 💯 Expected behavior
The selected project- and task-name will be shown in the editor window.

### 🔨 Steps to reproduce
1. Create a new task for a project
2. Edit an time-entry in the editor-window and select a this task
3. Only the project-name will be displayed but not the task-name.

### 📦 Additional info
![toggl-select-task](https://user-images.githubusercontent.com/363412/66192711-5871a500-e691-11e9-95a5-98b52d422cee.png)

**Comment by NghiaTranUIT** [comment]
Thank for the report. I'm able to reproduce it too. I'm going to put this bug in next milestone 👍
