### ISSUE TITLE
Better UX for auto-update on Windows

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3403]
### 💻 Environment
Platform: Windows

### 📒 Description
Right now the button to Restart&Update the app is very hidden (under About section) and a regular user has no way of knowing how to update the app if an update is available.
Pretty sure a lot of users don't even know that the app has an auto-update functionality.

I have no specific UI in mind, but in modern Win32 apps there is an `update` button somewhere on the main view or there is some icon/mark pointing to such button on the menu. E.g. Google Chrome, Telegram Desktop.

### ⭐️ Why do you want this?
Benefits:
- In the case of "teapotting", it should be clear for the user how to update the app without visiting the Toggl website.
- The user will have the possibility to receive the latest update if he/she wants to. Otherwise, the users who don't restart the app or PC that often and don't know about the "Restart" button in the About view do not have this possibility.
- For us, this will mean the updates will be propagated faster (as more users will be clicking to update) and we'll receive faster feedback.

**Comment by IndrekV** [comment]
👍

**Comment by skel35** [comment]
Will be implemented in #4304, #4305, #4306
