### ISSUE TITLE
Login / Sign up with Google via Google Chrome

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3425]
### Problem
We have to enter email/password and 2factor code every single time we have to login/sign-up with Google in Linux version. This steps are really complicated, thus we have to find better approach to select the Google Account from the default browser (If they're already logged-in).

The latest macOS (https://github.com/toggl/toggldesktop/pull/3326) and Windows version are already adopted new solution to mitigate this procedures.

### Why do we need?
- Save time. We can select the logged-in Google Account in Chrome. 
- Acquire more users.

### 💻 Environment
Platform: Linux

**Comment by MartinBriza** [comment]
Referencing #3629

**Comment by skel35** [comment]
done in #4298
