### ISSUE TITLE
Difficult to visually recognize items when grouped entries are expanded

### ISSUE THREAD

**Issue by cypressious** [toggl-open-source/toggldesktop#3430]
### 💻 Environment

Platform: Windows

### 📒 Description
Consider adding some indentation for the expanded sub items of a grouped item. Here is a quick concept:

![grafik](https://user-images.githubusercontent.com/1191816/66834177-74145f80-ef5d-11e9-831b-a0c6fcd04c60.png)

### ⭐️ Why do you want this?
This would improve readability (which groups are expanded, which items are sub items, ...)

**Comment by skel35** [comment]
I agree that it's now difficult to visually distinguish between groups, sub-items, and normal items.
We're going to address it in an upcoming Windows design update by making the time entry grouping look similar to Web and Mac apps.

**Comment by donquixote** [comment]
Linux here. Same problem.
We actually need to distinguish 4 different types of items:
- Group header, collapsed.
- Group header, expanded.
- Item in group (only visible if group header is expanded).
- Item outside of any group.

There could be some color and other appearance difference in addition to just indentation.

**Comment by skel35** [comment]
Fixed for the Windows app.
This will be addressed for the Linux app as well in the new design https://github.com/toggl-open-source/toggldesktop/pull/3618
