### ISSUE TITLE
[BUG] Incorrect Project group in Auto Completion View

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3433]
### 💻 Environment
Platform: macOS - Timeline build

### 🐞 Actual behavior
- Those Time Entries don't group properly
Image: https://files.slack.com/files-pri/T029WRP5G-FP24MSR3L/screenshot_2019-10-16_at_07.28.43.png

### 💯 Expected behavior
- TEs are in same group with a shared project.

### 🔨 Steps to reproduce

1. Login to testing account from Timeline build
2. Search project in Timer Bar

**Comment by NghiaTranUIT** [comment]
Unfortunately, I couldn't reproduce this bug.

## An attempt:
1. Get a latest Timeline build from https://github.com/toggl-open-source/toggldesktop/pull/3032#issuecomment-563163263
2. Play around and try to create some projects and time entries, which are associated to the same projects
3. Try to search on Timer AutoComplete View

## Result
- Couldn't reproduce the screenshot.

**Comment by IndrekV** [comment]
When looking at the screenshot I think the issue is with tasks (only paid plans support tasks) not time entries. Every task creates a new project item in the list and does not add the task under one project as it should. Did you test the issue with tasks?

**Comment by NghiaTranUIT** [comment]
Thank for the hint. I'm investigating on this approach 👍

**Comment by IndrekV** [comment]
Happens when the filter in text field filters the project that has tasks under it. For some reason, the projects are added for every task in that case.
