### ISSUE TITLE
Clicking  Play (Continue) just created a  0 second time entry

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#3470]
### 💻 Environment

Platform:  MacOS Catalina
OS Version:  10.15
Toggl Version: 7.4.1023

### 🐞 Actual behavior
Sometimes, when I click play on an existing time entry, instead of starting a new timer, a new 0 second time entry is created. 

![image](https://user-images.githubusercontent.com/49634673/67563561-623f7300-f73a-11e9-9861-eda882574ac6.png)

### 💯 Expected behavior
Expect a new time entry to get started 

### 🔨 Steps to reproduce
To reproduce: 
1. Do not have a running timer, but be in timer mode
2. Click play button on an existing solo time entry.
3. No new  timer will start but new 0 second time entry is created. 
(these reproduction steps by support team) 

### 📦 Additional info
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24259062638)

**Comment by TheSoloJake** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/24267101521)

**Comment by IndrekV** [comment]
This usually happens when "Manual mode" is enabled. On the screenshot is seems that it is not but somewhere in the code it looks like the logic works like in manual mode.

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24308205095)

**Comment by nidarasheed** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24310334817)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24310892078)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24506807766)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24506757510)

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/24543706550)

**Comment by ApocalypticFish** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/24717151584)

**Comment by nidarasheed** [comment]
[Case referrence](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24842504428)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24850924180)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24860543592)

**Comment by NghiaTranUIT** [comment]
Done in https://github.com/toggl-open-source/toggldesktop/pull/3582
