### ISSUE TITLE
Autocomplete dropdown opens and cannot be closed

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#3471]
### 💻 Environment

Platform:  MacOS
OS Version:  OS X 10.14
Toggl Version:  7.4.1023

### 🐞 Actual behavior
The autocomplete dropdown opens and does not close, hiding user time entries. 

### 💯 Expected behavior
The autocomplete should close when you click enter? 

### 🔨 Steps to reproduce
User Video [here](https://toggl.slack.com/files/UHVETTGTW/FPDV8T2BC/toggl_where_are_my_time_entries.mp4)

### 📦 Additional info
[User  Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24256231973)

**Comment by IndrekV** [comment]
When the user has selected a project from autocomplete and the timer now has 2 fields then when the user opens autocomplete the ESC won't close it and only clicking outside the autocomplete will close it. Also when you remove focus from timer it (SHIFT+DOWN) to focus listing it should also still trigger autocomplete close when pressing ESC.

<img width="366" alt="Screenshot 2019-11-04 at 12 51 35" src="https://user-images.githubusercontent.com/842229/68098798-2b1f4d80-ff02-11e9-817d-5b14b55fd05e.png">

**Comment by zdericnina** [comment]
[user report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/24507300203)

**Comment by nidarasheed** [comment]
[Case Reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24652534331)

**Comment by NghiaTranUIT** [comment]
Closes by #3507
