### ISSUE TITLE
App is unusable on Wacom pen tablet

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#3476]
### 💻 Environment

Platform: MacOS
OS Version:  10.13.6
Toggl Version: 

### 🐞 Actual behavior

I have to use my keyboard to use it: Like closing the edit field on the little cross after just starting a new entry (not if it’s running already). [Video for this here](https://toggl.slack.com/archives/C029WCX0T/p1572350184143100?thread_ts=1571997326.096500&cid=C029WCX0T).

Or: When starting a toggle, you enter for instance a project name, and then I try to click the suggested project name but it doesn’t react.

### 💯 Expected behavior

The desktop app should work on the tablet without needing keyboard. 

### 📦 Additional info

[User  Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24258905851)

**Comment by IndrekV** [comment]
We have not plans to explicitly work on Wacom tablet support. If our Windows version works it is great, but we can not guarantee it and do not test our Windows desktop app on pen tablets.

**Comment by IndrekV** [comment]
Looking at this closely it seems that the issue was not connected directly to pen tablet. There was an issue with closing edit popup in general that was fixed later on, so we should be all good.
