### ISSUE TITLE
Scrollbar design update

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3487]
### 💻 Environment
Platform: Windows

### 📒 Description
Implement the scrollbar based on the new design update.

![image](https://user-images.githubusercontent.com/16451391/71973632-13bd5300-3218-11ea-9c8c-756b4fba1d67.png)

width=2px, rectangular, color=#ff2d55 (`Toggl.SecondaryAccentColor`), no buttons on the top/bottom

Suggested implementation details:
Create a ResourceDictionary file `Scrollbar.xaml` in `ui\Resources\DesignUpdate`, add it to `ui\Resources\DesignUpdate\Controls.xaml`.
In `Scrollbar.xaml` create a style for the `ScrollViewer` with overridden `ControlTemplate` (see examples in other files in that folder).

UPD:
1. The work is being done in `feature/winui/master`. So branch off of this branch when implementing the ticket".
2. There is an old scrollbar style in `ui\Resources\ScrollBarStyles.xaml`. Remove that file as it won't be needed anymore (you can use it as a starting point if you like, not sure if it will work out fine).
3. The width of the scrollbar should increase to 4px when hovered over.

**Comment by CalumMunro** [comment]
Hi @NghiaTranUIT,

Is anyone currently working on this, because I'd like to give it a go if not.

Cheers,
Calum

**Comment by NghiaTranUIT** [comment]
Hi @CalumMunro, feel free to kick start this ticket 👍

**Comment by CalumMunro** [comment]
Great, thanks@NghiaTranUIT.

**Comment by skel35** [comment]
@CalumMunro I've updated the ticket with some additional information. Let me know if anything's unclear. (Currently, the code itself might be a mess at times 😄 as we're moving from an old to the new design).

**Comment by CalumMunro** [comment]
@skel35 👍 I certainly will, looking forward to it! Thanks

**Comment by skel35** [comment]
Picking this one up as we're nearing the end of our design update and I would like to implement this.
Next time I'll try to find something simpler to mark with `good first issue` 😄

**Comment by CalumMunro** [comment]
Hi Taras,

Really sorry I didn't get this prioritised. I appreciated the effort in helping me get to it, I did get as far as getting things running locally and was feeling fine about progressing. Sadly however, I have actually been sick, and ultimately never prioritised it enough, I can only apologise. If you come across any other tasks, I'd be grateful for the chance to help out. 

Thanks,
Calum
