### ISSUE TITLE
[BUG] Couldn't present the past timeline events

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3500]
### Description
The Timeline doesn't present the events (end_time < now()) in the Timeline View.

### 💻 Environment
Platform: macOS
OS Version: macOS 10.15
Toggl Version: Timeline master Branch

### 🐞 Actual behavior
- There are no events in the past
- start_time and end_time in the past are accidentally updated and they are equal.

### 💯 Expected behavior
- The past events should be presented properly.
- start_time and end_time in the past events shouldn't update

### 🔨 Steps to reproduce
1. Download Timeline version with pre-populated data (https://github.com/toggl/toggldesktop/pull/3333)
2. Help -> Import Timeline Event data
3. Open the local database by TablePlus and open the timeline_events table
4. Make sure in first 100 events: the start_time and end_time aren't equal. -> Duration > 0
5. Open the app
6. There is no Timeline event in the pass
7. Open the database again
8. First 100 events were updated: start_time is now equal to end_time

**Comment by skel35** [comment]
Fixed in #3501
