### ISSUE TITLE
Request Screen Recording permission for the Timeline Recorder on Catalina

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3515]
### 📒 Description
We already supported the Lite Timeline Recorder version in #3445, it's time to implement the full feature, which includes:
- Request the Screen Recording permission  
- Get the windows title properly

### 💻 Environment
Platform: macOS 10.15.0

### ⭐️ Acceptance Criteria
- [ ] Request permission properly when enabling the Timeline at the first time
- [ ] Present informative guideline to help the user to enable it
- [ ] Make sure Timeline Recorder is capable of getting the Window Title

**Comment by ApocalypticFish** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/24124282001)
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/24541149661)
