### ISSUE TITLE
Touch Bar should show the recent entries list also when timer is focused

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3520]
### 💻 Environment

Platform: macOS

### 📒 Description
Currently when you stop a timer the recent entries list will disappear.

**Comment by NghiaTranUIT** [comment]
Basically, this issues is related to the known-issues in https://github.com/toggl-open-source/toggldesktop/pull/3424#issuecomment-540995289.

I will investigate and try to fix it 👍

**Comment by NghiaTranUIT** [comment]
Look like this Private API would help us 

https://github.com/a2/touch-baer/blob/419a5cb828048fee8cd634de8ea0d1c51b49e99a/TouchBarTest/AppDelegate.m#L44-L45

It allows the TimeEntry Touch bar will appear regardless of any selection, which mean it overrides the Rich Text Touch Bar when we focus on the Project Text Fields in the Editor.

I will attempt this approach.
