### ISSUE TITLE
UI on Windows is very glitchy

### ISSUE THREAD

**Issue by TomDobbelaere** [toggl-open-source/toggldesktop#3523]
I tried restarting Toggl entirely (so it was gone from the systray) and that didn't help. I have yet to try restarting my entire OS

### 💻 Environment

Platform: Windows
OS Version: Windows 10 Pro 1809 (build 17763.805)
Toggl Version: 7.4.1023

### 🐞 Actual behavior

The side panel as well as context menus just completely disappear, and only the currently selected character/item is drawn, as can be seen in the gif below:

![glitchyui](https://user-images.githubusercontent.com/13522621/69058800-a578c300-0a14-11ea-80da-3a974c775c93.gif)

### 🔨 Steps to reproduce

1. 
2. 
3.

**Comment by IndrekV** [comment]
We are on progress of totally redoing the windows UI and this will probably be addressed with new UI. 

Thank you for taking the time to write to us and just be patient new UI is already in the oven.
