### ISSUE TITLE
Time format `8.30` should be considered the same as `8:30`

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3536]
### 💻 Environment
Platform: macOS/Windows/Linux/Library

### 📒 Description
we should be able to detect all most common formats:
8.30/8:30/830 all should be treated the same

**Comment by skel35** [comment]
invalid issue, as 8.30 can mean decimal

we're planning on unifying the format input for all platforms in scope of "Timer input unification" project.
