### ISSUE TITLE
App syncing issues after coming back from sleep

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3537]
### 💻 Environment

Platform: Windows

### 🐞 Actual behavior
The app does not sync

### 💯 Expected behavior
The app should sync and get the current state

### 🔨 Steps to reproduce

1. Put the computer to sleep
2. Start timer from some other Toggl App
3. Wake computer
4. Open Toggl Desktop and see if it sync the running timer

### 📦 Additional info
Reported in Go Desktop Week

Might be connected to #3049

**Comment by skel35** [comment]
Reopening as #3553 was reverted
