### ISSUE TITLE
If timer is stopped from another app the timer is not cleared properly

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3539]
### 💻 Environment
Platform: macOS

### 🐞 Actual behavior
timer is not cleaned

### 💯 Expected behavior
timer should return to default view with everything cleared

### 🔨 Steps to reproduce

1. Have a running timer
2. Open up desktop app
3. Stop timer in another app (web app for example)
4. See the sync happening and the state it updates the timer to

### 📦 Additional info

Similar issue to #3463

<img width="514" alt="timer" src="https://user-images.githubusercontent.com/842229/69304459-5b1c5f80-0c29-11ea-8abb-464d56b0c2f3.png">

**Comment by IndrekV** [comment]
I was unable to replicate this issue. It might be that it is already fixed with #3563

Please close this issue if you can't replicate @NghiaTranUIT

**Comment by NghiaTranUIT** [comment]
Confirmed that I couldn't reproduce it anymore in the latest DEV 7.4.1043.
