### ISSUE TITLE
Create and upload app installers as artifacts in GitHub Actions branch builds

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3552]
### 💻 Environment
Platform: Windows

### 📒 Description
Currently only `master` builds produce installers that are getting uploaded to GitHub Releases. For branch builds we should not upload installer to GitHub Releases, but saving them as [artifacts](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts) makes sense. 
The version should be set to `7.0.0` so that it looks like our local builds.

This would be very useful for testing purposes both within our team, as the tester would not need to build an app locally, and outside our team if we want someone else to try out the branch build (this will be needed quite a few times during Windows new UI development).

**Comment by MartinBriza** [comment]
I guess this doesn't apply to just Windows but all platforms but considering the (slight, in some cases, more severe especially on macOS where the situation is already pretty bad) build time increase, we should also invest some time in making caching work, too. I'll open an issue for it so we don't forget.
