### ISSUE TITLE
Our CI/CD workflow doesn't handle PRs opened from a forked repository

### ISSUE THREAD

**Issue by MartinBriza** [toggl-open-source/toggldesktop#3560]
### 🐞 Actual behavior
There are no checks ran on PRs opened from a fork of our repo, like #3554 for instance.

### 💯 Expected behavior
Run at least the basic check suite on PRs like that.

### 📦 Additional info
We'll probably have to create a special branch in the current workflow or a whole new one because we can't rely on the contents of foreign forks, our secrets could get leaked if we're not careful, for instance.

**Comment by skel35** [comment]
closing as a duplicate of #3971 which contains more info
