### ISSUE TITLE
Crash with OverflowException of x64 app when receiving horizontal scroll messages from the mouse

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3561]
### 💻 Environment
Platform: Windows
Toggl Version: 7.4.1023, 64-bit

### 🐞 Actual behavior
Crash with `OverflowException` which happens when `WindowChrome` receives `WM_NCHITTEST ` message (Logitech mice configured with SetPoint known to send these messages). Also seems that it requires either app going fullscreen, or some multi-screen setup. Crash is caused by the bug in WPF https://github.com/dotnet/wpf/issues/1269.

### 💯 Expected behavior
No crash.

### 🔨 Steps to reproduce
See https://developercommunity.visualstudio.com/content/problem/167357/overflow-exception-in-windowchrome.html.
https://stackoverflow.com/questions/50282355/why-does-my-wpf-application-crash-when-i-bump-my-mousewheel/50282356#50282356

**Comment by skel35** [comment]
TODO: check whether MahApps.Metro's `MetroWindow` implemented a workaround for this bug, as we'll be switching to it as a base class for our windows. Consider submitting them a PR with a workaround for this issue.

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24726664226)

**Comment by dianetoggl** [comment]
Hey @skel35 any updates on this one? 😊

**Comment by skel35** [comment]
@dianetoggl The fix is going to be available with the release of the new design.

The `MetroWindow` implementation has it fixed:
https://github.com/ControlzEx/ControlzEx/blob/develop/src/ControlzEx/Behaviors/WindowChromeBehavior.MessageHandling.cs#L438
https://github.com/ControlzEx/ControlzEx/blob/45ddf61998019e9eae74fe88acae474a4eec038b/src/ControlzEx/Microsoft.Windows.Shell/Standard/Utilities.cs#L132
