### ISSUE TITLE
Issue with editing a running TE

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#3562]
### 💻 Environment

Platform: MacOS
OS Version: OS X 10.15.1
Toggl Version: 7.4.1036

### 🐞 Actual behavior

The details pane sometimes will close as soon as it opens, making it impossible to change the project of the currently running task. It seems that if I click on the project name in the window, I get the behaviour I described in my report. Clicking on other regions of the current running timer appear to operate as expected. Here is a video that shows the behaviour: **[video link](https://drive.google.com/open?id=13GTkiJy46HBaAL8imJ8UyH3H4DF2VLKj)**

### 💯 Expected behavior
The edit view should not disappear like that no matter where you click to edit a running TE. 

### 🔨 Steps to reproduce

1. Start a running time entry with a project
2. Click on the project part/area of the running entry to edit the entry
* If you click anywhere else everything works fine, you have to click on the project to reproduce the issue. 

[Case reference. ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/24715500366)

**Comment by nidarasheed** [comment]
I can reproduce this as well.

**Comment by NghiaTranUIT** [comment]
This is fix in BETA 7.4.1080 along with #3596
