### ISSUE TITLE
Better separation of hours in timeline view (WIP)

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3565]
### 💻 Environment
Platform: 

### 📒 Description
Currently it's hard to be sure where an hour ends.

This is WIP as it will be discussed with designers and product people to come up with best solution

Possible solutions:
- Alternate gray backgrounds
- Border at the hour point and lighter line at the half hour point

**Comment by AlicjaSuska** [comment]
@IndrekV Designs are ready - background changes hour by hour. It must have been skipped during the initial implementation.

Please, see the designs:
https://app.zeplin.io/project/5c4ac9dcb253c8bfd5e7c13d/dashboard?seid=5d10e9d905c4ff70bbf5dd8f
