### ISSUE TITLE
Add today button to the date selection in timeline view or separate button near it

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3566]
### 💻 Environment
Platform: macOS

### 📒 Description
It is a very common work flow to dig around in different dates and then wanting to jump into Today at the end. It works the same in calendar apps where there is a separate button for it.

This needs more input on the specifics.

**Comment by AlicjaSuska** [comment]
@IndrekV Designs are ready - background changes hour by hour. It must have been skipped during the initial implementation.

Please, see the designs:
https://app.zeplin.io/project/5c4ac9dcb253c8bfd5e7c13d/dashboard?seid=5d10e9d905c4ff70bbf5dd8f
