### ISSUE TITLE
Update releases.json and upates.json with new dev release after build

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3574]
### 💻 Environment
Platform: GH Actions

### 📒 Description
Should happen with builds executed in `master` branch

**Comment by skel35** [comment]
List of files which should be kept in the new repo location and moved from `gh-pages` to `master`:
- `releases.json`
- `updates.json` (will require adding a redirect to it, not sure how to do it)
- `darwin_*_appcast.xml` - not yet used but will be in the near future
- installer download link redirects? (not sure how to do it)
- changelog json files (`_data` folder)
Other files can be simply removed together with the `gh-pages` branch.
