### ISSUE TITLE
Allow to set the "meta" (/windows) key as shortcut on Linux

### ISSUE THREAD

**Issue by xdmx** [toggl-open-source/toggldesktop#3588]
### 💻 Environment

Platform:  Linux
OS Version:  Arch
Toggl Version:  7.4.1020

### 🐞 Actual behavior

I want to set meta/win key + T to show toggl

### 💯 Expected behavior

It's setting the shortcut just as "T"

### 🔨 Steps to reproduce

1. Go to settings
2. Set shortcut to win+T
3. It only saves "T"

### 📦 Additional info

This should have been fixed by #1568, but it's not working on Linux/Arch. I haven't tried on other OS

**Comment by MartinBriza** [comment]
Works for me in Fedora with KDE. It's possible your WM/DE is blocking this.
What is your environment? How did you install Toggl Desktop?
I'll go ahead and guess you're in GNOME, probably under Wayland, is that correct?

**Comment by xdmx** [comment]
I installed it through Arch AUR (using yaourt), and I'm also using KDE under X11 :thinking: 

I don't think it's blocked as I can use it for other things (eg. I have a win+c shortcut set in the kde configs to send a dbus message)

This is what it shows when I set the shortcut and press the "win" key, if I then press "t" it only shows "t" as the shortcut:
![Screenshot_20191205_173355](https://user-images.githubusercontent.com/115298/70254484-6d4be100-1785-11ea-82ad-e8ed444db64f.png)

**Comment by MartinBriza** [comment]
Can you try setting that shortcut in a different Qt app?  I suspect this could be related to the packaging of Qt in Arch, then.
Also, which AUR package do you use? I think there are two and the one that actually builds the app from source should be the better one.

**Comment by xdmx** [comment]
I'm already using the compiled one (toggldesktop). You're right... I've just tried to set a shortcut on Kate (meta + p) and this is what it shows:
![Screenshot_20191217_003202](https://user-images.githubusercontent.com/115298/70951804-b729a680-2064-11ea-8677-f5f5ffe267be.png)
It doesn't show the shortcut correctly and it's not working as well, even though I got it sometimes, but not always. I'll upstream this as a QT bug on Arch
Thank you
