### ISSUE TITLE
App no longer works on Mac OS 10.11

### ISSUE THREAD

**Issue by evanwarner** [toggl-open-source/toggldesktop#3590]
### 💻 Environment
Platform: OSX 10.11.6 El Capitan

### 📒 Description
As of v7.4.1041, Toggl Desktop no longer opens in El Capitan. It instantly crashes, logging the following error to Console:
`com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000006.TogglDesktop[3458]) Service exited due to signal: Trace/BPT trap: 5`

The detailed crash report contains the following:
```
Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
  Referenced from: /Applications/TogglDesktop.app/Contents/MacOS/TogglDesktop
  Reason: image not found
```

I've also tried beta v7.4.1065 and it results in the same error. Reverting back to v7.4.1036, the app opens and works as expected.

**Comment by IndrekV** [comment]
`DFRFoundation` is used for TouchBar support we added from 7.4.1041. We should make it conditional for older MacOs.

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24893751042)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/24920189843)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24973634616)

**Comment by NghiaTranUIT** [comment]
Hi @evanwarner,

This crash is resolved in https://github.com/toggl-open-source/toggldesktop/pull/3593 and it's released in a latest DEV build (7.4.1106).

You can download at https://github.com/toggl-open-source/toggldesktop/releases/download/v7.4.1106/TogglDesktop-7_4_1106.dmg

We will push to BETA and Stable channel soon 👍

**Comment by evanwarner** [comment]
Awesome, thanks all!

**Comment by evanwarner** [comment]
Confirmed, beta version works without crashing.
