### ISSUE TITLE
GDPR violation: Terms of service and privacy policy links do not work during sign-up process

### ISSUE THREAD

**Issue by digitalethics** [toggl-open-source/toggldesktop#3595]
I was about to test Toggle Desktop on Linux, however ToS and privacy policy links do not work during the sign-up process. Please fix this asap as this is a direct violation of GDPR. 

Toggl Version: 7.4.528 on GNU/Linux-based OS

#2452

**Comment by MartinBriza** [comment]
They do work for me in Fedora with KDE. When clicking the links, the app opens a browser for me. Can you be please more specific on your environment?

**Comment by MartinBriza** [comment]
Considering there's been no answer for 9 months, I'm closing this but if you (or anybody else for that matter) have a clear reproducer for this behavior, please reopen the issue and post it here.
