### ISSUE TITLE
.deb install file not linked in README.md

### ISSUE THREAD

**Issue by sojusnik** [toggl-open-source/toggldesktop#3600]
Was the .deb file, that is mentioned in the [Linux support page](https://support.toggl.com/en/articles/2410832-toggl-desktop-for-linux), purposely omitted in the README.md, or is this project going to support only taballs and flatpaks in the future?

**Comment by MartinBriza** [comment]
Yes, in a distant future, we don't intend to support .deb packages. The .deb is kept in the support page mostly for backwards-compatibility but people visiting the Github page (who are more technical usually) will get pointed to the Flatpaks.
Anyway, if you open the Releases section on this page, you'll see we're still building .debs and you are free to download and test them of course.

**Comment by MartinBriza** [comment]
I closed the issue but feel free to ask any followup questions, be it here or in a different thread.
