### ISSUE TITLE
Toggl Desktop crashes everytime on startup

### ISSUE THREAD

**Issue by franciscojun** [toggl-open-source/toggldesktop#3604]
Windows Log:
Application: TogglDesktop.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.DllNotFoundException at TogglDesktop.Toggl.toggl_set_log_path(System.String) at TogglDesktop.Toggl.InitialiseLog() at TogglDesktop.BugsnagService.Init() at TogglDesktop.Program.OnBeforeStartup() at TogglDesktop.SingleInstanceManager`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnStartup(Microsoft.VisualBasic.ApplicationServices.StartupEventArgs) at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel() at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(System.String[]) at TogglDesktop.Program.Main(System.String[])

**Comment by skel35** [comment]
Thanks for the report @franciscojun and sorry for the inconvenience this caused to you.
We've reverted the latest beta release so you can now download the previous version here https://toggl.com/toggl-desktop/ (7.4.1023) and use it normally.

**Comment by franciscojun** [comment]
Thanks, @skel35!

**Comment by skel35** [comment]
Version: 7.4.1079.
Issue: missing `vcruntime140_1.dll` in a 64-bit application installer.

**Comment by skel35** [comment]
Fixed with f95fd823d60ae0929e7f9dd4502fa65dcf109b85.

**Comment by mgdreamingstar** [comment]
I have this issue with the latest version and the v7.5.65.

**Comment by skel35** [comment]
Hi @mgdreamingstar!
Please share the logs so that we could investigate the error that happens in your case.
You can send them to support@toggl.com.

As a general recommendation, performing a full reinstall and then a clean install should solve your issue. But I'd like also like to have a look at what causes the issue in your case to make sure we can prevent it for the future.

**Comment by mgdreamingstar** [comment]
Hi, I've sent the log file in the folder. I'm now using the client installed from Win10 Store.

**Comment by dianetoggl** [comment]
[Log file](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/26053035713)
