### ISSUE TITLE
Billable icon shows for a second in timer when creating a new project

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3622]
### 💻 Environment
Platform: Windows

### 🐞 Actual behavior
Shows billable flag in timer for a second

### 💯 Expected behavior
It should not show billable flag when project is created

### 🔨 Steps to reproduce
- Edit running timer.
- Add project
- After pressing `save` on the add project form the project name is added to the timer but also a billable icon is added 
- A second later the billable icon is removed

(This was done in a free account that does not have billable flag functionality at all)

### 📦 Additional info

![win_billable](https://user-images.githubusercontent.com/842229/70624947-14b79080-1c2a-11ea-87bf-822d8c8b61ae.gif)

**Comment by skel35** [comment]
same as #3792
