### ISSUE TITLE
Project  color changes on MacOs

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#3628]
### 💻 Environment

Platform:  MacOS
OS Version:  OS X 10.14.6
Toggl Version:  7.4.1041  stable.

### 🐞 Actual behavior
The project's color is orange in webapp but shows as brown on desktop. 

### 💯 Expected behavior
The colors should be consistent with webapp. 

### 📦 Additional info
[Case Reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24990226193)

**Comment by TheSoloJake** [comment]
@MartinBriza Have a user [reporting](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/26720490266) this on 7.5.85

**Comment by MartinBriza** [comment]
@NghiaTranUIT is the guy to ask about macOS, I just added a tag so it's obvious "from the outside" of the bugreport

**Comment by NghiaTranUIT** [comment]
We have a cross-team project to unify the project color across all Toggl's platforms. We will come back later when we have any result 👍

**Comment by TheSoloJake** [comment]
@NghiaTranUIT Understood. So for the time being the best explanation I can give the user is that the colors are app-generated, and we're working on a process to unify them across apps?

**Comment by skel35** [comment]
The project color adaptation is implemented on macOS and is consistent with other platforms.
