### ISSUE TITLE
Blurred icon app in OS X 10.12

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3633]
There are some reports that the icon app is blurred in macOS 10.12.

### 💻 Environment
Platform: macOS
OS Version:  macOS 10.12
Toggl Version: BETA 7.4.1106

### 🐞 Actual behavior
- The icon app is blurred in macOS 10.12

### 💯 Expected behavior
- The icon app should not be blurred

### 🔨 Steps to reproduce
1. Run the latest build in 10.12

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/25021085746)
