### ISSUE TITLE
Clicking on the idle detection notification bubble should open the app

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3637]
### 💻 Environment
Platform: Linux

### 🐞 Actual behavior
Clicking on the bubble does nothing

### 💯 Expected behavior
Clicking on the idle detection notification bubble brings the app in focus so the user can select the correct option and handle their idle time.

### 🔨 Steps to reproduce

1. set idle time to 1 minute 
2. wait 1 minute
3. See idle popup and click on it
4. Noting happens and app is not brought to focus.
5. To handle the idle time you need to open the app and then see the idle time choices.

[report](https://toggl.slack.com/archives/C029WCX0T/p1576608411021200)

**Comment by MartinBriza** [comment]
This was fixed by 86674dc5662312de5b0c3264040615bc03eb0853 .
