### ISSUE TITLE
[BUG] Timeline Recording is enabled after restart the app 

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3656]
### 💻 Environment
Platform: macOS
OS Version: Timeline build

### 🐞 Actual behavior
The timeline record is automatically enabled after laughing the app

### 💯 Expected behavior
The setting should be persisted

### 🔨 Steps to reproduce
1. Try to disable Timeline Recording in Preference, Menu or Switcher
2. Re-start the app
3. Observe the setting

**Comment by NghiaTranUIT** [comment]
## Results
It looks like a bug from Backend.

- Save data to the server as soon as we change the Record Timeline option
<img width="921" alt="Screen Shot 2019-12-25 at 16 05 12" src="https://user-images.githubusercontent.com/5878421/71441314-954eb480-2733-11ea-95cf-9ca432250f9d.png">

- The database is updated properly.

However, when the app launches, the server responses with `record_timeline=true` 
<img width="923" alt="Screen Shot 2019-12-25 at 16 05 38" src="https://user-images.githubusercontent.com/5878421/71441296-836d1180-2733-11ea-9c39-2884f17a2263.png">

As a result, it will override the Timeline Record option in Preference and make it's impossible to turn it OFF.

**Comment by NghiaTranUIT** [comment]
@IndrekV It seems that this bug hasn't fixed from the Backend yet.

I still encounter it in the latest Production build. Turn OFF (Verified that `record_timeline`=false in the database) -> Quit and Open app -> The database shows it's `true`.

Same result when debugging from Proxyman.

**Comment by IndrekV** [comment]
If it's not fixed please create an issue in backend and ask if they can double-check the workings of this specific endpoint.

**Comment by NghiaTranUIT** [comment]
Verified that this issue only happens in Staging, but it works fine in Production.

## How I verify
1. Start the latest Production build
2. Try to turn ON and OFF the Timeline Switcher
3. Each action, let double check the value `record_timeline` in `users` table in the production database. Verify:
- The boolean is correspond with the state of the switcher
4. Turn it OFF and quit the app
5. Re-lauch and open the Preference
6. Verify that the `record_timeline` still is OFF.

=> In production build, it's we expect
=> In Staging build -> `record_timeline` is `true`, but the Switch is OFF when the Sync is done
