### ISSUE TITLE
Crash when displaying in-app notification when window height is NaN

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3668]
### 💻 Environment
Platform: Windows
Toggl Version: 7.4.1092

### 🐞 Actual behavior
Crash with `System.ArgumentException`: `'NaN' is not a valid value for property 'To'.`

### 💯 Expected behavior
No crash

### 🔨 Steps to reproduce
TBD.
See [Bugsnag link](https://app.bugsnag.com/toggldesktop/toggldesktop/errors/5cf4fd06ef073500199b3bf2?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=%27NaN%27&filters[search][1][type]=eq&filters[search][1][value]=is&filters[search][2][type]=eq&filters[search][2][value]=not&filters[search][3][type]=eq&filters[search][3][value]=a&filters[search][4][type]=eq&filters[search][4][value]=valid&filters[search][5][type]=eq&filters[search][5][value]=value&filters[search][6][type]=eq&filters[search][6][value]=for&filters[search][7][type]=eq&filters[search][7][value]=property&filters[search][8][type]=eq&filters[search][8][value]=%27To%27.)

**Comment by nidarasheed** [comment]
[Case  reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/25024072265)
