### ISSUE TITLE
Autotracker issue on MacOS

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#3678]
### 💻 Environment

Platform: macOS
OS Version: Intel Mac OS X 10_15_2 (as shown by Intercom)
Toggl Version: 7.4.1092

### 🐞 Actual behavior
The user added "slack" as a keyword for the Autotracker but it's not triggering the notification when the "slack" app is started. I asked Vedran to reproduce this and he got the same behavior. 

To get full context please check out this [Slack thread 🔗](https://toggl.slack.com/archives/C029WCX0T/p1578317461062600) 

### 💯 Expected behavior
The Autotracker notification should be triggered when a corresponding app is started.

### 🔨 Steps to reproduce

1. Add a keyword for the Autotracker and save the change ('slack' for example)
2. Start the Slack app
3. See if the notification shows

### 📦 Additional info
[Case link 🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/25276544669)

**Comment by VeljkoTN** [comment]
@NghiaTranUIT it might work on the latest Beta, Vedran just tried it

**Comment by IndrekV** [comment]
We should add similar icon and link to autotracker settings view so it's clear when app needs more permissions to work correctly. Similar to the solution in this PR  #3751
