### ISSUE TITLE
No ESC key when "What are you doing" is in focus

### ISSUE THREAD

**Issue by vedr4n** [toggl-open-source/toggldesktop#3684]
MacBooks with a Touch Bar don't display the **esc** key when inputting a time entry description. 

### 💻 Environment

Platform: macOS
OS Version: 10.15 Catalina
Toggl Version: 7.4.1106

### 🐞 Actual behavior
Touch bar removes the Escape key in favor of recent time entries
![IMG_1426](https://user-images.githubusercontent.com/19473351/71910100-8fb09000-3171-11ea-816f-283540b45745.JPG)

### 💯 Expected behavior
There should be an ESC key on the far right side of the touch bar.

**Comment by NghiaTranUIT** [comment]
Basically, we're using private API to facilitate how we present/dismiss a global Touch Bar and there is a bug that the ESC key is dismissed unexpectedly 💣 

It seems Pock app (https://github.com/pigigaldi/Pock) handles it well. I'm looking on their implementation and let see how we tackle it 👍

**Comment by IndrekV** [comment]
Looking at other tools like Zoom for example. They also hide the ESC key when the app is in focus. As the research showed there is no easy way to bring this back with the current functionality. Also there is no function for ESC key when description input is focused. 

I think we should just leave it as it is and close this issue.

**Comment by vedr4n** [comment]
As a workaround, could we create a new button called "Close edit popup" or something similar that essentially does the same thing as hitting ESC?

**Comment by IndrekV** [comment]
I tested it again and it makes sense to add a static button ESC to the left that will trigger edit popup close. If it's missing there is no way to close time entry edit popup with the keyboard. Thanks for the clarification @vedr4n
