### ISSUE TITLE
Timeline not showing data

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#3688]
### 💻 Environment

Platform:  MacOS
OS Version: OS X 10.14.6
Toggl Version:   7.4.1092 

### 🐞 Actual behavior

Timeline is not showing app names. Screenshots are in this [chat](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/25303984601)

### 💯 Expected behavior

Timeline should show app names

### 🔨 Steps to reproduce
Not reproduced yet. 

### 📦 Additional info
[Slack](https://toggl.slack.com/archives/C029WCX0T/p1578479239024400)

**Comment by NghiaTranUIT** [comment]
Confirmed that the Timeline is still working without any Permission on macOS 10.14.6 Parallel machine.

![Screen Shot 2020-01-09 at 15 31 58](https://user-images.githubusercontent.com/5878421/72051209-5e60cd00-32f5-11ea-9c1a-17015e07d52e.png)

I will investigate further why it wont work in the user's case 👍

**Comment by skel35** [comment]
@NghiaTranUIT is this still relevant?

**Comment by NghiaTranUIT** [comment]
We can close since it's done and there is no report further 👍
