### ISSUE TITLE
Project selection does not work in 7.5.4 on Linux

### ISSUE THREAD

**Issue by wizonesolutions** [toggl-open-source/toggldesktop#3714]
I have cleared cache.

To reproduce...start a timer (or edit an existing entry) and try to select a project. The click does not register. It does not work with the keyboard either. Apologies if this was already fixed later on. I will try to update the AUR if so.

**Comment by wizonesolutions** [comment]
I'm now running 7.5.24 and encountering the same issue. Is there some specific information I can provide to help debug this?

**Comment by IndrekV** [comment]
Thank you for pinging on this. I've checked the release you referred and there is indeed some bug. Items are visible in the list but selecting any project will not update the project field.

**Comment by IndrekV** [comment]
My tests show that in dev mode everything works but after a release build package things get broken. Somewhere in the build process somehow it breaks. We're looking more into this.

**Comment by sque89** [comment]
Any news on this issue? It is very annoying as the desktop app is basically useless without this function. I need to got to the online tool anyway to set the projects. Thanks a lot!

**Comment by wizonesolutions** [comment]
Still happening on 7.5.50 Linux.
