### ISSUE TITLE
Can't log in after token reset

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#3734]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.4.1112 (64-bit)

### 🐞 Actual behavior
After resetting my API token I was logged out and couldn't log back into the app. After clicking to log in the UI would show for a second and the same page would load again. It was also telling me that I lost access to my latest WS and that I should create a new one which is misleading. 

### 💯 Expected behavior
I should be able to simply log back in after using the correct credentials 

### 🔨 Steps to reproduce

1. Reset token on the Profile Settings page
2. Start the desktop app
3. Try logging in

### 📦 Additional info
![cant log in TD](https://user-images.githubusercontent.com/36152180/72436417-a0c85500-37a0-11ea-9140-22d5070c39f6.gif)

After removing the app along with clearing it's local data I was able to log in.

**Comment by skel35** [comment]
Fixed in the new UI as there is now a "log in with a different account" link which logs you out without the need to clear cache:
![image](https://user-images.githubusercontent.com/16451391/76427177-a7480700-63b4-11ea-8514-b96f3bb2f912.png)
