### ISSUE TITLE
Cmd-Left/Right doesn't work for entry description editing when in Timeline tab

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3755]
### 💻 Environment
Platform: macOS
Toggl Version: 7.5.16

### 🐞 Actual behavior
Cmd-Left/Right doesn't work for entry description editing when in the Timeline tab.
It switches the dates in the calendar which is something I don't want to do when I'm editing the time entry.

### 💯 Expected behavior
Cmd-Left/Right should move my cursor to the beginning/end of the line when I'm editing the time entry description.

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/25709690985)

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/25671820622)
