### ISSUE TITLE
Native notification for restarting the app for a new build

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3756]
### Problem
The users are not aware that they need to restart the app in order to make the downloaded build take effective unless they go to Toggl Menu -> About.

Even though the update is downloaded, but it could take couple days until the quit the app. Some users keep the app alive for a week.

### Proposal
- Determine if there is a new build, which is already downloaded 
- Use native notification and gratefully present the notification.

### 💻 Environment
- Platform: macOS, Windows and Linux

### ⭐️ Acceptance Criteria
- [ ] Properly determine if there is a new build
- [ ] Present the native popup
- [ ] Make sure the sound is following the System Setting

**Comment by skel35** [comment]
Idea - Telegram-like UX.
Add an "Update Toggl" button to the main window so that the app can be updated with just 1 click.

**Comment by IndrekV** [comment]
This has been implemented for mac with #3988 
There is a separate issue for windows #4001
Not sure with our current solution in Linux this is possible.

Closing this as there are other issue addressing the same thing.
