### ISSUE TITLE
High memory usage on MacOS app

### ISSUE THREAD

**Issue by kadrihvl** [toggl-open-source/toggldesktop#3766]
### 💻 Environment

Platform: macOS
OS Version: OS X 10.14.6
Toggl Version: osx_native_app/7.5.16 

### 🐞 Actual behavior

User reports noticing Toggl desktop hogging up memory on Mojave. He killed a Toggl process w/1.2 gigs of memory usage.
Additional comment: This started after I upgraded from 10.13, but I might've upgraded the Toggl app as well.

### 🔨 Steps to reproduce

1. 
2. 
3. 

### 📦 Additional info

[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3724360/conversations/25499235386)

**Comment by astrochun** [comment]
I've seen this issue as well.  Here's a screenshot from the Activity Monitor showing nearly 7GB of RAM use.  I've seen it on Mac OSX and macOS. A restart brings it back to <70MB.  Perhaps a memory leak as I often have Toggl running for some time?  I'm using 7.5.13 on macOS 10.14.6.

<img width="794" alt="Screen Shot 2020-01-26 at 8 55 24 PM" src="https://user-images.githubusercontent.com/20305734/73149406-6c954400-407e-11ea-82ac-b0646608649b.png">

**Comment by astrochun** [comment]
I'm fairly sure this is a memory leak.  It's now over 200MB and continues to rise.

Note: I had not upgraded this specific Mac from an older OS.  It has had Mojave since the beginning.

**Comment by skel35** [comment]
Thanks for the report @astrochun, that does look like a memory leak, we will have a closer look at this issue soon.

**Comment by skel35** [comment]
After using 7.5.16 Windows version for half a day with "Record timeline" `on` I haven't noticed any signs of memory leak. Memory usage never got above 100 Mb and it wasn't increasing when just tracking time + recording activity in the background.
So I'd assume this is a MacOS-specific issue and we should continue the investigation there.

**Comment by astrochun** [comment]
A few clarify points to hopefully track down the leak:
1. I do not have "Record Timeline" on.
2. This is seen on Mac OSX 10.11 and macOS 10.14.6.
3. This is seen in version 7.5.16 (Mac OSX) and 7.5.3 (macOS Mojave)

**Comment by TheSoloJake** [comment]
User [responded](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25599498648) with log files if needed for investigation

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/25637470629)

**Comment by kadrihvl** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3724360/conversations/25686801372) on OS X 10.15.3

**Comment by Stvad** [comment]
Have the same issue:  
macOS - 10.14.6
toggl: 7.5.16

**Comment by NghiaTranUIT** [comment]
All done at #3791. Please update the 7.5.42 BETA build 🙌

**Comment by astrochun** [comment]
I've been testing 7.5.42 beta.  When I started, it was using 60MB this morning.  After several hours it's around 135MB.  I'll continue to monitor, and see what it does after several days.  I do believe that the high memory leak is gone, but I wonder if there is a second minor leak as I've seen the memory use slowly creep up.  I won't re-open this ticket until I'm certain after a few days with the application running continuously.

Testing was performed on macOS 10.14.6 and Mac OSX 10.11.6.  The numbers that I reported here are for the macOS set-up.  Just looking at my Mac OSX case, it's been active for about 7 hours and it's at 62.7MB.

**Comment by liuyigh** [comment]
I am using 7.5.85 on macOS10.15.4 still uses 589M ram.

**Comment by toszcze** [comment]
@liuyigh I can confirm that the issue has been fixed in 7.5.123 (see #3813).

**Comment by liuyigh** [comment]
@toszcze I didn't realized the close is in a different issue #3813 . Sorry for my redundant report. Thanks!

**Comment by sonthomsen** [comment]
I am still experiencing this issue this in Mojave 10.14.6 and ToggleDesktop 7.5.123 - was up to 32GB of RAM just now

**Comment by NghiaTranUIT** [comment]
Thanks for the port @sonthomsen I'm conducting the memory leak investigation about some parts of XIBs on Timeline and Color Picker, which is reported from the Profile tool. Will notify you when we have a new build 👍

**Comment by cappypopp** [comment]
Yep same here, over 20GB consistently.

**Comment by vytautasgimbutas** [comment]
@toszcze Toggl 7.5.123 over 1GB RAM usage :/

**Comment by scmrus** [comment]
Toggl 7.5.123 over 7GB RAM usage

**Comment by tux255** [comment]
Toggl 7.5.441 it was 55MB RAM usage after started app in the morning and over 300MB RAM usage in the middle of the day
