### ISSUE TITLE
Re-test and Re-evalute our Linux releases.

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3775]
### 💻 Environment
Platform: Linux

### 📒 Description
We have a very general description of Linux support in our public articles. We should test and have a very specific description so users know what release supports what version of Linux before downloading an installer.

Test all the releases on all LTS versions of Ubuntu.

Example:
**User is on Ubuntu 16.04**

Deb package does not work with Ubuntu 16.04 because it has a dependency of newer Qt that does not support Ubuntu 16.06. The tar package works fine with Ubuntu 16.04 for example and would be a good solution for that user.

**Comment by MartinBriza** [comment]
Fixed
