### ISSUE TITLE
Double check that the Timeline Events are cleared after 7 days

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3783]
### Description
In the old build, those Timeline Events are cleared from the local database after 7 days, but from what we introduce a new Timeline feature, which has some Library changes. We're not sure whether or not this functionality work.

We should double check it.

### 💻 Environment
Platform: macOS
Toggl Version: Timeline build

### Acceptance Criteria
- [ ] Double check that this 7 days func is working. If not, let fix it

**Comment by lastobelus** [comment]
It would be great if this was configurable. I just discovered the timeline feature, and I love it. I can see myself wanting to keep the record of activity around a lot longer than a week -- for example, when debugging an issue it would be enormously helpful to see the record of google searches from when something was originally developed. Also in the (rare) event of needing to explain to a client what I was doing with my time, which is much more likely to happen at the end of a month or quarter then at the end of a week.

**Comment by NghiaTranUIT** [comment]
Confirmed that this feature is still working, but instead of 7 days, it's 9 days.

Ref: https://github.com/toggl-open-source/toggldesktop/blob/35f578ce901b7bf8ecccfe1d16f511b67cdb44d8/src/database.cc#L97-L102

----------------------
@lastobelus Thank for the feedback, but we don't have any intention to make this option configurable. FYI, the 9 days is applied only for the local Desktop, not the Backend or Front End Dashboard. Each platforms could have different expirations.
