### ISSUE TITLE
When starting timer from Autotracker notification billable icon is show for a second

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3792]
### 💻 Environment

Platform: macOS

### 🐞 Actual behavior
When starting a timer from Autotracker notification billable icon is shown for a second and after sync it is removed. The project is not billable.

### 💯 Expected behavior
No billable icon should be shown if project is not billable

### 🔨 Steps to reproduce

1. Go to preferences and Autotracker tab
2. Enable Autotracker
3. Setup item with name "Slack" and a project that is not billable
4. Make sure timer is not running and focus slack
5. A notification appears, start the timer and see that billable icon is shown for about a second in the timer

**Comment by skel35** [comment]
Probably related to #3622. Looks like the issue is somewhere in the library.

**Comment by skel35** [comment]
Looks like the backend is sending `projects_billable_by_default: True` for free workspaces:

![image](https://user-images.githubusercontent.com/16451391/73857156-2c348380-483f-11ea-938f-e6596a39d093.png)

![image](https://user-images.githubusercontent.com/16451391/73857215-4706f800-483f-11ea-8ea0-376fad656b47.png)
