### ISSUE TITLE
Total time for the day not being displayed in a decimal format (unlike web app and mobile app)

### ISSUE THREAD

**Issue by zdericnina** [toggl-open-source/toggldesktop#3795]
### 💻 Environment

Platform:  macOS
OS Version: OS X 10.15.3
Toggl Version: 7.5.16

### 📒 Description

Total time for the day will be displayed in a classic format (HH:MM) even if the user has decimal format selected in the settings, this causes users to think there are discrepancies between web app and desktop app.

**Web app**
<img width="372" alt="Screenshot 2020-02-09 at 10 37 13" src="https://user-images.githubusercontent.com/19727123/74099843-27feb380-4b28-11ea-8685-ad6574326672.png">

**Desktop app**
<img width="578" alt="Screenshot 2020-02-09 at 10 39 30" src="https://user-images.githubusercontent.com/19727123/74099885-8deb3b00-4b28-11ea-8aad-1fbcd01a159e.png">

**Comment by skel35** [comment]
will be addressed in #3996
