### ISSUE TITLE
Do not drag move the mini timer when start/stop button is pressed

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3815]
### 💻 Environment
Platform: Windows

### 📒 Description
Sometimes there can be difficulties to click the start/stop button in the mini timer because if the mouse is moved even a little bit during a click then it would be registered as a drag move instead.
A solution to this is to disable drag move when pressing the start/stop button.

**Comment by TheSoloJake** [comment]
[User case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/25780331769)
