### ISSUE TITLE
Clicking on timeline will stop running time entry

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3827]
### 💻 Environment
Platform: macOS

### 🐞 Actual behavior
If you have a running TE and then click on an empty space in timeline the time entry is stopped and new time entry is created. This is happening because the click creates a new entry and with the old list view creating new one always stopped the old one. In the timeline it should not happen as it is not expected.

### 💯 Expected behavior
Clicking on empty space in timeline should not stop running entry.
New time entry should be created but running entry should not be touched with this action.

### 🔨 Steps to reproduce

1. Start timer
2. Open timeline view
3. Click on an empty space
4. New time entry is created and running entry is stopped.

**Comment by NghiaTranUIT** [comment]
It looks like that Toggl Library unexpectedly stops the running TE when we create new TE. I will dig into the library and see how we overcome it 👍

**Comment by skel35** [comment]
How about replacing a click to create a time entry with a double-click?
I think everyone can agree that it's way too easy to click accidentally. Personally, I had to delete those accidentally created time entries a lot of times, and I've heard similar feedback from others.

**Comment by IndrekV** [comment]
I agree that the single click to create an entry is too easy, but I also think that creating an entry in the timeline should not affect running entry.

I'm not too on board with double click. For the click to add entry we could change it to drag. So that user has to click and drag to create an entry. It would feel more user friendly as it would allow dragging the correct size and not need to change duration in edit popup.

**Comment by NghiaTranUIT** [comment]
For now, I would focus to fix this bug, which is "The running is stop when creating new TE" by click.

```
For the click to add entry we could change it to drag. So that user has to click and drag to create an entry. It would feel more user friendly as it would allow dragging the correct size and not need to change duration in edit popup.
```
I will open separated ticket, since it significantly change the behavior of the current Drag and Drop, which we already implemented it 👍
