### ISSUE TITLE
Create new TE from Timeline doesn't work properly

### ISSUE THREAD

**Issue by kadrihvl** [toggl-open-source/toggldesktop#3829]
### 💻 Environment

Platform: macOS 
OS Version: 10.14.3
Toggl Version: 7.5.16 and 7.5.42

### 🐞 Actual behavior

1. Create a new entry from the Timeline 
2. Add a new project 
3. Add a new tag (“Language”) to the project 
4. No response from the "create new tag“ button 
5. Try "No." for a couple times 
6. Esc 
7. Timeline entry was added 
8. Open entry and see multiple “Language” tags added

Tested on my desktop app and got a similar result. Only in my case the TE was created without a Project nor a tag when checking database. Plus app showed "Data you are sending..." error (probably cause I'm not an admin in WS I was testing with). 
![Screenshot 2020-02-18 at 17 42 56](https://user-images.githubusercontent.com/12407134/74753539-efbe4a00-5278-11ea-8fa7-9f0adb136a0b.png)
![Screenshot 2020-02-18 at 17 44 44](https://user-images.githubusercontent.com/12407134/74753551-f482fe00-5278-11ea-81ea-e96f4dd23b89.png)

### 🔨 Steps to reproduce

1. 
2. 
3. 

### 📦 Additional info
Logs with [this case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3724360/conversations/25817385430).

**Comment by NghiaTranUIT** [comment]
Thank for the comprehensive report. I will look on it in this milestone 🤚
