### ISSUE TITLE
New Mac App Update Replaces Key Command

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#3831]
### 💻 Environment

Platform: macOS 
OS Version: Latest
Toggl Version: 7.5.42

### 🐞 Actual behavior
The key command CMND+Left Arrow/CMND+Right Arrow previously allowed the user the chance to move between fields. Now, the command switches from the Timer to Timeline. 

### 💯 Expected behavior
CMND+Left (or right) should continue to toggle between fields. 

### 📦 Additional info
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/25820311663)

**Comment by NghiaTranUIT** [comment]
It's already fixed in https://github.com/toggl-open-source/toggldesktop/pull/3798 and it's in the latest DEV 7.5.49 build.

I will push the BETA today 🙌

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25992533559)

**Comment by TheSoloJake** [comment]
@NghiaTranUIT Possible regression shared by user: [case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/26214344350)
