### ISSUE TITLE
Do not use hardcoded database and logs file paths

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3855]
### 💻 Environment
Platform: Windows

### 📒 Description
Our app currently uses a hardcoded database file path `%LOCALAPPDATA%/TogglDesktop/toggldesktop.db` regardless of the directory it is running from. Same for log files.
This means that all our installations and debug runs will share the same database and logs files. This works due to the fact that only one instance of the app can run at the same time, but it has downsides, especially during development. For example, the logs are intermixed betweens production builds and debug builds, running integration tests messes up the local database, etc.

**Comment by IndrekV** [comment]
Maybe have a prefix in database filename for dev version `dev_toggldesktop.db`

**Comment by skel35** [comment]
Thanks, it is a good idea.
I've come to the conclusion that the database and logs have to be in the `%LOCALAPPDATA%` and the only issue it causes is the production/development/testing database file sharing, so renaming the file would solve that.

**Comment by skel35** [comment]
Implemented in #3964.
