### ISSUE TITLE
Toggl Desktop app doesn't let you click on Menu button after being launched

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#3873]
### 💻 Environment

Platform: MacOS
OS Version: 10.15.3
Toggl Version: 7.5.42

### 🐞 Actual behavior

If you open Toggl desktop  (after it was shut down) and then try to click on menu buttons at the top, you cannot.  They do not respond. Clicking outside the Toggl Desktop window, then back on it, and then clicking menu items works.

### 💯 Expected behavior

The menu should work. 

### 🔨 Steps to reproduce

1. Quit Toggle Desktop  
2. Open it back up 
3. While the focus is still on the app, click Menu buttons. 
4.  Click out of the desktop app
5. Click on the desktop app
6. Now try the menu. 

### 📦 Additional info

[Slack](https://toggl.slack.com/archives/C029WCX0T/p1583304296076200)

**Comment by IndrekV** [comment]
Seems like the same issue as #1612

**Comment by IndrekV** [comment]
Possible solution https://stackoverflow.com/questions/33345686/cocoa-application-menu-bar-not-clickable/37958805
