### ISSUE TITLE
[BUG] Github Action doesn't update release.json

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3884]
### 📦 Description
Github Action for DEV release (macOS) does:
- Archive build successfully with notarization 
- Upload source and dmg to Github Release
- Bump version correctly
- Update dev AppCast file 

but doesn't update the `release.json` at https://github.com/toggl-open-source/toggldesktop/commit/37b9c41865d95d9bdd01accd2b15760aab4f7940

It should update like Mini Bot - https://github.com/toggl-open-source/toggldesktop/commit/253f176f16bc6c291763ae872e369f4ff21c6935

### 💻 Environment
Platform: macOS

### 🐞 Actual behavior
- `release.json` and `update.json` and `download` folder in gh-pages is not updated.

### 💯 Expected behavior
- release.json in gh-pages should be updated.

### 🔨 Steps to reproduce
1. Merge any PR to master to trigger the DEV release Github Action

**Comment by skel35** [comment]
The public links in gh-pages are also not getting updated

**Comment by NghiaTranUIT** [comment]
sorry, but can you elaborate @skel35? I checked that it's the same with what Mini Bot does

**Comment by skel35** [comment]
I just mean that public links located in `download` folder in `gh-pages` branch (e.g. `download/mac-beta.html`) should also be updated like the Mini Bot does: https://github.com/toggl-open-source/toggldesktop/commit/f57ac2c0c3ee42ed3f7d21aad37f0f27d036eb45#diff-9af8e9d3f71bdb8a32438277c6c6663b

**Comment by NghiaTranUIT** [comment]
I see, the download files is missing from the description, but the PR is actually done 👍

**Comment by skel35** [comment]
Fixed by https://github.com/toggl-open-source/toggldesktop/pull/3885.
Example commit: https://github.com/toggl-open-source/toggldesktop/commit/844f65803fd0eafaa0462def35b92464b1c7c551
