### ISSUE TITLE
Reports filter problem on project created via Desktop app 

### ISSUE THREAD

**Issue by TuxVisual92** [toggl-open-source/toggldesktop#3901]
### 💻 Environment

Platform: Windows
OS Version: Windows 10 buid 1909
Toggl Version: 7.5.46 (64-bit)

### 🐞 Actual behavior
I always created projects on Desktop app, but lately I realized that on web reports if I search a project created on Desktop app I don't find it.

### 💯 Expected behavior
Find all the projects in reports filter.

### 🔨 Steps to reproduce

1.  Create a project on Desktop app (public and with a client)
2.  Wait for syncing or force sync
3.  Go to reports on web app and search for the project just created in the filters list.
4.  Check in the projects list and see if there is my project. (Yes, always present but non searchable)

### 📦 Additional info
My workaroud is to modify project title directly in the web app. For example add a space or .
Save project and the came back to the original name.
Now I can find project also in the reports filters.

**Comment by vedr4n** [comment]
I tried creating a new project from the Windows app (also Win 10) and it immediately showed up in both Reports and the Project page. 

Once you create the project, do you assign the time entry to the created project or do you assign it to something else? In other words, is there at least one time entry that's connected to the project you just created?

**Comment by TuxVisual92** [comment]
Here a small video to show you the beahavior.
[2020-03-17 08-10-09_Trim.zip](https://github.com/toggl-open-source/toggldesktop/files/4342167/2020-03-17.08-10-09_Trim.zip)

**Comment by skel35** [comment]
Hi @TuxVisual92, thanks for the video!
Can you please try the same but Refresh the web page after you've created the project?
Please also note that the Project name filter on the Projects page does not have the autocompletion, only search results on the page itself; but the autocompletion has to work properly on the Projects filter on the Reports page.

**Comment by TuxVisual92** [comment]
Hi @skel35, thanks for your reply.

> Can you please try the same but Refresh the web page after you've created the project?

Yes, I try to refresh and also to clean my browser cache. I try to search for the project on the Projects filter on the Reports page after some days and same result. No project found.

> Please also note that the Project name filter on the Projects page does not have the autocompletion,

Yes, I understand this, in the video I press Enter key in the Projects page and wait to autocompletion in the Reports page.

**Comment by skel35** [comment]
@TuxVisual92 The frontend team has investigated the issue and admitted it exists, although it shouldn't be happening after the page refresh. In fact, none of us was able to reproduce the issue if we refresh the page. There were some similar issues fixed earlier this year, so it's possible that it's already been fixed. If you can still reproduce it, please contact support@toggl.com so that we can conduct a deeper investigation into why this is happening for you. Thanks!
