### ISSUE TITLE
Taskbar icon does not get gray when timer is inactive (taskbar buttons are not combined)

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#3940]
### 💻 Environment
Platform: Windows
Toggl Version: 7.5.92

### 🐞 Actual behavior
Taskbar icon does not get gray when the timer is inactive and "combine taskbar buttons" setting is off

### 💯 Expected behavior
Taskbar icon does not get gray when the timer is inactive and "combine taskbar buttons" setting is off

### 🔨 Steps to reproduce
1. Taskbar settings -> Combine taskbar buttons -> Never
2. Open TogglDesktop, make sure the timer is inactive

### 📦 Additional info
![image](https://user-images.githubusercontent.com/16451391/77887355-19549300-7273-11ea-9246-2e47d38fdfcc.png)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26381120152)
