### ISSUE TITLE
Windows App: Not Respecting Default Project

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#3948]
### 💻 Environment

Platform: Windows
OS Version: N/A
Toggl Version: 7.5.92 (beta)

### 🐞 Actual behavior
App will not respect "default project" setting. App will use last-used project. 

### 💯 Expected behavior
If/when default project setting is enabled, app should respect feature. 

### 📦 Additional info
User [report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/26424696982). User reports that reverting to stable channel resolved issue, so "bug" resides in beta channel atm (7.5.92)

**Comment by VeljkoTN** [comment]
Another user reached out with a similar issue, only this time they do not have a default project selected but when they create time entries using the mini timer it always allocates them to the same project. **[Case link 🔗](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/26422945112)**
