### ISSUE TITLE
[Onboarding] Grey out / Highlight Hint area

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#3953]
### 📒 Description
This ticket would implement the grey out / highlight area when a Hint Popover is presented 

### 💻 Environment
Platform: macOS

### ⭐️ Acceptance Criteria
- Add grey out / highlight area properly, which relies on what is the type of hint

**Comment by skel35** [comment]
implemented in #3997 (except corner rounding)
