### ISSUE TITLE
"Invalid e-mail or password!" message although they are 100% correct

### ISSUE THREAD

**Issue by thomasmoors** [toggl-open-source/toggldesktop#3963]
### 💻 Environment

Platform: Windows
OS Version: 10 Pro [v1909 | build 18363.752]
Toggl Version: 7.5.46 (installed with chocolatey)

### 🐞 Actual behavior
I try to login with the credentials I copy pasted from my password manager. I verified they are correct by using them on the website. (https://plan.toggl.com/#signin). This is why I believe them to be correct. As the password is randomly generated I'm not (too) affraid to tell which special characters might be the cause: `#&*` are included in the generated password. 

### 💯 Expected behavior
That I would be logged in

### 🔨 Steps to reproduce
1. Try to log in with a password that contains  these characters somewhere:  `#&*`

### 📦 Additional info

Suddenly the message changed to "Login failed. Are you online?"
![image](https://user-images.githubusercontent.com/486765/78231689-7cdcfb80-74d3-11ea-89e7-2ece9a16d6e3.png)

**Comment by skel35** [comment]
Hi @thomasmoors!
We're experiencing server load issues that caused us to temporarily take mobile and desktop apps offline. We're working on resolving the issues and get our apps back online as soon as possible.
The web app is currently operational so you can track your time there meanwhile. 
Our twitter https://twitter.com/toggl will post the updates when everything is back to normal.
Apologies for the inconvenience.

**Comment by thomasmoors** [comment]
Thank you for the quick response
