### ISSUE TITLE
Show a notification when an update has been downloaded in the background

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#4001]
### 💻 Environment
Platform: Windows

### 📒 Description
We should show a notification when an update has finished downloading.
Clicking on the notification would restart the app and install the update.

**Text in the notification**

Title: `A new version of Toggl Desktop is ready!`
Content: `Click here to restart and install`

Same as MacOs issue #3988

**Comment by JoernBerkefeld** [comment]
An update-via-restart recommended / urgent icon like in Chrome would be the better UX here. The typical toggl user is likely getting lots of system notifications for all kinds of other things already and will potentially ignore this.

**Comment by skel35** [comment]
will do in-app update button instead: https://github.com/toggl-open-source/toggldesktop/projects/20
