### ISSUE TITLE
Crash with UriFormatException when setting proxy credentials

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4008]
### 💻 Environment
Platform: Windows
Toggl Version: 7.5.92

### 🐞 Actual behavior
Crash with UriFormatException when setting proxy credentials

### 💯 Expected behavior
No crash

### 🔨 Steps to reproduce
Unknown, but stack trace should be enough to fix the error:
>System.UriFormatException Invalid URI: Invalid port specified. 
    unknown System.Uri.CreateThis(string uri, bool dontEscape, UriKind uriKind)
    unknown System.Net.WebProxy.CreateProxyUri(string address)
    unknown TogglDesktop.ViewModels.LoginViewModel.HttpClientFactoryFromProxySettings(TogglSettingsView settings)
    unknown TogglDesktop.ViewModels.LoginViewModel.OnSettings(bool open, TogglSettingsView settings)
    unknown TogglDesktop.Toggl+DisplaySettings.Invoke(bool open, TogglSettingsView settings)

### 📦 Additional info
[Bugsnag link](https://app.bugsnag.com/toggldesktop/toggldesktop/errors/5d7e085477f4d100182d24ab?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[release.seen_in][0][type]=eq&filters[release.seen_in][0][value]=7.5.92&filters[event.severity][0][type]=eq&filters[event.severity][0][value]=error)

**Comment by wmorellato** [comment]
I stumbled upon this issue a couple days ago. May I take a look at the code and submit a PR?

**Comment by skel35** [comment]
@wmorellato Feel free to do so 👍

**Comment by wmorellato** [comment]
Here it goes. Forgot to include the gif on the PR, this is how the error notification is displayed.

![ezgif com-resize](https://user-images.githubusercontent.com/58891430/83406815-d4b9b500-a3e5-11ea-8ce0-f2d0da5483eb.gif)
