### ISSUE TITLE
Memory leak still happening in macOS Mojave

### ISSUE THREAD

**Issue by astrochun** [toggl-open-source/toggldesktop#4012]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14.6
Toggl Version: 7.5.85

### 🐞 Actual behavior
Computer was constantly running hot and checked my Activity Monitor to find that Toggl was using nearly 19GB of memory!

### 💯 Expected behavior
Memory usage of 100-200 MB

### 🔨 Steps to reproduce
Just launch Toggl and leave it running

### 📦 Additional info

See screenshot.  Note that this was after attempting to terminate it.  It was at 18.95GB before killing the application.

<img width="800" alt="Screen Shot 2020-04-19 at 5 18 00 PM" src="https://user-images.githubusercontent.com/20305734/79704590-fbbd8c80-8266-11ea-8309-0765f8ca2657.png">

**Comment by NghiaTranUIT** [comment]
Hi, we're investigating and fixing it on https://github.com/toggl-open-source/toggldesktop/pull/3984

It gonna be merged and release to the stable channel soon 🙌

**Comment by barspi** [comment]
Same here
macOS Mojave 10.14.6
TogglDesktop 7.5.85

It starts  with "Memory" ~ 50MB  and "Real Mem"  ~87MB
After a few hours, it's using gigabytes upon gigabytes  (yesterday I killed it upwards 12 GB, today it's already a 3.04 GB)

**Comment by Cybernisk** [comment]
Same for MacOS 10.11.6

**Comment by NghiaTranUIT** [comment]
We just release the BETA 7.5.115, which fixes the memory leaking. Please update it 🙌

**Comment by barspi** [comment]
Not really, as shown in #4019  :-)
