### ISSUE TITLE
Use repo to distribute toggl for Debian based systems

### ISSUE THREAD

**Issue by NedkoHristov** [toggl-open-source/toggldesktop#4014]
### 💻 Environment
Debian/Ubuntu

### 📒 Description
I'm using toggl daily and it's fantastic. Still, I don't feel comfortable to download the compiled `.deb` every time there's a new version. I believe it would be a great idea to introduce a repo for Debian based systems.

### ⭐️ Why do you want this?
Getting latest as fast as I can, improved security, UI, bugfixes, etc.

**Comment by MartinBriza** [comment]
We're aiming to provide a Flatpak package as the best way to get the Toggl Desktop application. Providing a repository for each distribution has a huge maintenance overhead so Flatpak seems like a good option. 
You can find us here: https://flathub.org/apps/details/com.toggl.TogglDesktop and please keep in mind we're using the beta channel as well. We didn't make any Linux releases lately but more are coming soon-ish.
I'm closing this issue but please feel free to ask any followup questions here, open a new issue or you can talk to our support through the app.
