### ISSUE TITLE
Memory leak in macOS

### ISSUE THREAD

**Issue by emersonf** [toggl-open-source/toggldesktop#4019]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.15.3
Toggl Version: 7.5.85

### 🐞 Actual behavior
Memory usage is at 2.78GB and climbing.

### 💯 Expected behavior
Reasonable memory usage. 😄  

### 🔨 Steps to reproduce
I'm just using Toggl normally, AutoTracker is off, pretty much on default settings.

**Comment by barspi** [comment]
same here
+1
if you leave it running it will consume over 12 GB of virtual memory

**Comment by NghiaTranUIT** [comment]
Hi guys, please update to the BETA 7.5.115, which fixes the memory leaking issue (https://toggl.github.io/toggldesktop/#mac) 🙌

**Comment by barspi** [comment]
let's see :-)

**Comment by lhedger** [comment]
Hi,
This is still an issue with BETA 7.5.115.
See screenshot.
Thanks for all your work on this!
![Screen Shot 2020-04-27 at 9 31 10 am](https://user-images.githubusercontent.com/12403209/80322782-a555dc80-886a-11ea-9def-6f945cb91c52.png)

**Comment by barspi** [comment]
@NghiaTranUIT 
Same as @lhedger 

<img width="399" alt="Screen Shot 2020-04-27 at 00 34 48" src="https://user-images.githubusercontent.com/1316018/80331738-47e86e00-881f-11ea-940f-80bf9a1a780d.png">

Mine has been running for al little over 50hs, but I haven't really used it during the weekend. Basically no interaction, just running in the background

So, it's not fixed

**Comment by NghiaTranUIT** [comment]
Thanks for reporting. We will keep investigating 👍

**Comment by ksilz** [comment]
I also have the memory leak with beta 7.5.115:

![Toggl Mac memory leak still there 2](https://user-images.githubusercontent.com/1061209/80335955-bfcd8d00-884d-11ea-89c0-a1c4806afaac.gif)

**Comment by NghiaTranUIT** [comment]
Hey guys, the leaking is finally fixed in the stable build 7.5.123. 

Let check it out and thank for reporting this bug 🙌
