### ISSUE TITLE
Sending Feedback From App Duplicates Feedback Emails

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#4025]
### 💻 Environment

Platform: macOS
OS Version: Latest
Toggl Version: 7.5.115

### 🐞 Actual behavior
When choosing the Send Feedback option, 2-3 emails are sent to Support with the same feedback message. 

### 💯 Expected behavior
When clicking on Send Feedback, one email should be sent. 

### 📦 Additional info
Cannot replicate in 7.5.85

**Comment by ApocalypticFish** [comment]
Actually turns out it did replicate in 7.5.85 there was just a delay.

**Comment by dianetoggl** [comment]
Happening in 7.5.109 Windows as well 😊

**Comment by skel35** [comment]
Looks like it's been fixed by the backend
