### ISSUE TITLE
Sending feedback from app doesn't attach logs

### ISSUE THREAD

**Issue by dianetoggl** [toggl-open-source/toggldesktop#4026]
### 💻 Environment

Platform: Windows & Mac

### 🐞 Actual behavior
When a user sends a bug report from within the desktop app the logs are no longer sent with the feedback.

### 💯 Expected behavior
Logs would be sent with the report.

### 🔨 Steps to reproduce

1. Submit feedback from within the app
2. Support team will receive an [email like this ](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26816063579) or [this](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/search/conversations/26813988827?assigneeIdentifier=all&q=toggl%20desktop%20feedback)

**Comment by skel35** [comment]
This looks like a backend bug. I've submitted them a ticket.

**Comment by dianetoggl** [comment]
Thanks @skel35 😀

**Comment by skel35** [comment]
Fixed by the backend
