### ISSUE TITLE
Improve the flow when "Required Fields" is on

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4027]
### 💻 Environment
Platform: macOS/Windows/Linux
Toggl Version: 7.5.119

### 🐞 Actual behavior
The user is seeing an error:
> Data that you are sending is not valid/acceptable

The error doesn't disappear after the user fills in the required fields.

### 💯 Expected behavior
The user can clearly see which time entry lacks which fields.
The error goes away when the user fills in the required fields

### 🔨 Steps to reproduce
1. Turn on the Required Fields feature (available in the Premium plan)
2. Create a time entry with the empty required fields.

### 📦 Additional info

Possible solution (s)
1. Set the error to be local to the unsynced entry. This way it will be shown in the unsynced entry icon tooltip. Consider also showing the entry in the Edit view for this entry.
2. Make sure the error message clearly tells which field is required and not filled in (as it previously had been).

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/26820702265)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/26814563490)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/26820557728)
