### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by patricknick** [toggl-open-source/toggldesktop#4033]
### 💻 Environment

Platform: macOS 
OS Version: 10.15.4 
Toggl Version: 7.5.85 

### 🐞 Actual behavior

When Toggl Desktop is running, memory consumption gradually increases up to multiple gigabytes (it takes a while though). It doesn't seem to make a difference whether the timer is running or not. 
It looks like starting / stopping the timer increases the memory growth.

### 💯 Expected behavior

Keep a small memory footprint.

### 🔨 Steps to reproduce

1. Open Toggl Desktop.
2. Let it run for a while. 
3. Start / Stop timer.

### 📦 Additional info

Let me know if you want some specifics. I'll continue keeping an eye on it to see a pattern.

**Comment by skel35** [comment]
Hi @patricknick!
We've fixed the issue in our latest beta version (7.5.123) and will soon push this out to all users.
Please check it out by switching to the beta channel in the About window or by downloading it manually https://toggl.github.io/toggldesktop/download/macos-beta/ and let us know if you still see any noticeable memory leaks, thanks!
