### ISSUE TITLE
Memory Leak macOS

### ISSUE THREAD

**Issue by SpiritOfLogic** [toggl-open-source/toggldesktop#4043]
### 💻 Environment

Platform: macOS
OS Version: 10.15.4
Toggl Version: 7.5.123

### 🐞 Actual behavior
TogglDesktop process consumes more and more memory - up to 20GB

### 💯 Expected behavior
TogglDesktop consumes a limited amount of memory

### 🔨 Steps to reproduce
1. Run TogglDesktop on macOS
2. Possibly run TogglDesktop on a second logged in user on same Mac with same Toggl account
3. Wait for memory pressure to build

### 📦 Additional info
What kind of logs would be helpful here? Let me know

**Comment by alichtman** [comment]
![image2](https://user-images.githubusercontent.com/20600565/81397856-c1207480-90ed-11ea-917c-0d7f9ad6b8ae.png)

```bash
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G3020
```

Same issue here.

**Comment by NghiaTranUIT** [comment]
Thanks for the report. I will keep continue investigating the memory issue 👍

**Comment by skel35** [comment]
Most users who were contacted by Support have confirmed that 7.5.123 resolved the issue, while none so far have replied the issue still exists.
@SpiritOfLogic, @alichtman or others: Could you please verify that you're using 7.5.123 or newer, clear cache (Account->Clear Cache), and confirm that the issue persists?

**Comment by darrenfurr** [comment]
I'm using Toggl 7.5.123 and just Force Quit the application because it was taking 12.55GB on my Mac.

**Comment by insipidlight** [comment]
Mine was using 22.30 GB in the background, and my /private/var/VM folder contains 11.8 GB of swap files. version 7.5.85

**Comment by darrenfurr** [comment]
> I'm using Toggl 7.5.123 and just Force Quit the application because it was taking 12.55GB on my Mac.

I never quit Toggl. I just leave it running in the background. I've noticed since posting this; that on first run the app runs ~40MB. I'm on Day 4 & running ~100MB. Close/Reopen back to ~40MB

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481302466895)

**Comment by dianetoggl** [comment]
Case above - the user has got back in touch:
> the app has been going 24 hours and its at 860m Version 7.5.277

**Comment by nicktoggl** [comment]
Update from user, left on over weekend 1.56GB 

[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481302466895)

**Comment by dianetoggl** [comment]
[This user](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481302466895) has got in touch again. They checked today and the app is using 4.85GB of memory.

**Comment by skel35** [comment]
22 GB of memory and 190 GB of virtual memory, reported by the user https://twitter.com/PaulvdDool/status/1323904160752902144
