### ISSUE TITLE
[Security] Password strength feature

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#4044]
### 📒 Description
It's time to implement the password strength feature on Sign Up screen

Design: https://toggl.invisionapp.com/d/main#/console/19637314/411588053/preview

### 💻 Environment
Platform: macOS

### ⭐️ Acceptance Criteria
- Popover view with no arrow that contains the Password Strength UI
- Match the behavior in the Security proposal in Notion
- Analyze the criteria and show the UI properly

**Comment by skel35** [comment]
Moved the Windows part to #4065
