### ISSUE TITLE
Support undoing multiple actions

### ISSUE THREAD

**Issue by Leland** [toggl-open-source/toggldesktop#4058]
### 💻 Environment
Platform: macOS
OS Version: 10.15.4 (19E287)
Toggl Version: 7.5.135

### 🐞 Actual behavior
Selecting a single timer entry and pressing <kbd>Del</kbd> (or pressing the "Delete" button in the timer details) removes a time entry. After #3658, an Undo functionality was added, and <kbd>⌘</kbd>+<kbd>Z</kbd> will restore that deleted entry. 🚀 This is _awesome_! 

However, per that PR's details, this was a half-measure.

If I delete one entry ("foo"), and then delete a second entry ("bar"), I can only Undo back to "bar." I know of no other app like this on macOS, and this unintuitive behavior is not expressed to the user either.

I should be able to restore a _lot_ of entries. I typically see apps with a stack of ~10+ actions. 

An aside: restoring multiple deleted items is still unimplemented. If you delete one item ("foo") and then delete two items in bulk ("bar" and "foobar") you will be unable to Undo _at all_. Further, Redo – <kbd>Shift</kbd>+<kbd>⌘</kbd>+<kbd>Z</kbd> – is likewise still unimplemented. I'm curious why these caveats listed in the #3658 PR were not followed up on.

### 💯 Expected behavior
1. Create two time entries - "foo" and "bar"
2. Delete "foo"  
3. Delete "bar"
4. Undo to restore "bar"
5. Undo to restore "foo"

### 🔨 Steps to reproduce

1. Create two time entries - "foo" and "bar"
2. Delete "foo"  
3. Delete "bar"
4. Undo to restore "bar"
5. Attempt to undo to restore "foo." Are unable.

**Comment by IndrekV** [comment]
Thank you for reporting. We really appreciate it. I agree that we shouldn't limit the history of deleted items to 1. We will look into this.

**Comment by skel35** [comment]
Hey @Leland!
To answer your first point, deleting time entries produces no warning dialog only if the time entry's duration is less than 15 seconds. Let us know whether it causes any issues for you.

The undo functionality supporting multiple items simply hasn't been implemented yet, so thanks for showing the interest!

**Comment by Leland** [comment]
> deleting time entries produces no warning dialog only if the time entry's duration is less than 15 seconds

Oh, interesting. Once the Undo command supports a larger stack of undos (and bulk editing etc doesn't wipe out the stack) I'd be all for making this not show a warning at all. 

Gmail and other apps' tactic of totally removing the permanence and user stress of deletion is a wonderful UX pattern IMO!

**Comment by NghiaTranUIT** [comment]
Thanks for reporting @Leland. This issue is addressed in #4072 . I review the codebase and support Undo/Redo with multiple times as other apps do 👍
