### ISSUE TITLE
[Project-Color] Update default color on the Project color wheel 

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#4060]
### 📒 Description
As a discussion on the Color Project feature, we decide to unify the default color on the Color Wheel to the blue #3177BE

Ref: https://toggl.slack.com/archives/CR5AUMKUK/p1589266824181400?thread_ts=1589205367.167200&cid=CR5AUMKUK 

### 💻 Environment
Platform: macOS

**Comment by skel35** [comment]
Windows app does not have the color wheel yet, so nothing to do on the Windows side
