### ISSUE TITLE
Couldn't build master on Win10

### ISSUE THREAD

**Issue by Hellaren** [toggl-open-source/toggldesktop#4081]
### 💻 Environment
Platform: Windows

### 📒 Description
I've tried to build the master branch (2a52600503fc4bd315168d17fe1a910446569da1) on windows according to the corresponding instruction.

After running 'make deps' from the root folder I get the error

> D:\Projects\Private\toggldesktop>make deps
> The syntax of the command is incorrect.
> cd third_party/poco && (make clean || true)
> make[1]: Entering directory 'D:/Projects/Private/toggldesktop/third_party/poco'
> tr: extra operand `_'
> Try `tr --help' for more information.
> Makefile:51: /Users/nghiatran/Documents/Work/Toggl/toggldesktop/third_party/poco/build/config/Darwin64-clang-libc++: No such file or directory
> make[1]: *** No rule to make target '/Users/nghiatran/Documents/Work/Toggl/toggldesktop/third_party/poco/build/config/Darwin64-clang-libc++'.  Stop.
> make[1]: Leaving directory 'D:/Projects/Private/toggldesktop/third_party/poco'
> rm -rf third_party/poco/**/.dep
> rm: cannot lstat `third_party/poco/**/.dep': Invalid argument
> make: *** [Makefile:181: clean_deps] Error 1

I had a couple more errors before but was able to resolve them after installing GnuWin32 and adding the path variables to GnuWin32/bin.

What did I do wrong?
Thank you!

**Comment by skel35** [comment]
Hi!
Please refer to platform-specific instructions for building a Windows app:
https://github.com/toggl-open-source/toggldesktop/blob/master/README.md#windows-1
Basically, you just need to open a `TogglDesktop.sln` solution file and build a `Debug` configuration.

Sorry for the confusing readme page.

**Comment by Hellaren** [comment]
@skel35, thank you for your help.
It partly resolved the issue.

But I have another one right now.
When I try to build TogglDesktop solution, I get the errors:

Severity	Code	Description	Project	File	Line	Suppression State

> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\PocoData64.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\PocoDataSQLite64.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\src\ui\windows\TogglDesktop\TogglDesktop\bin\x64\Debug.Broken\TogglDesktopDLL.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\PocoXML64.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\PocoUtil64.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\libssl.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\PocoJSON64.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\PocoNetSSL64.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\PocoFoundation64.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\libcrypto.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\PocoCrypto64.dll" because it was not found.	TogglDesktop			
> Error		Could not copy the file "D:\Projects\Private\toggldesktop\third_party\poco\bin64\PocoNet64.dll" because it was not found.	TogglDesktop			

I used cleaned the repository to get it to the initial state and run it again to confirm that it is reproducible.
In the toggldesktop\third_party\poco\bin64\ folder I have all necessary DLLs but they have the "d" suffix like "PocoDataSQLite64d.dll" or "PocoJSON64d.dll".

Did I miss something?
Thank you

**Comment by skel35** [comment]
@Hellaren Please make sure you have a proper configuration selected. It should be `Debug`.
I believe you have a broken config selected (which we were going to fix, but should probably just remove).
