### ISSUE TITLE
"Submit Feedback" Option Available When Logged Out

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#4088]
### 💻 Environment

Platform: macOS 
OS Version: macOS 10.15.4
Toggl Version: 7.5.123 (downloaded from App Store) 

### 🐞 Actual behavior
While logged out from the app, the Help menubar still contains an active "Send Feedback" option. One can type information, attach an image, click "Send", and receive a confirmation popup that a message was sent, but no message is actually sent to Toggl. 

### 💯 Expected behavior
"Send Feedback" should not be available until after login

**Comment by IndrekV** [comment]
The issue is that the menu item is under the "Help" menu and macOs adds a search field to help menu automatically and thanks to that it does not trigger the check that other menus do to check if user is logged in or not.

**Comment by IndrekV** [comment]
It turned out that the menu item tags were not aligned so that's why the check didn't work.
