### ISSUE TITLE
Unable to track time on Windows app

### ISSUE THREAD

**Issue by jongc** [toggl-open-source/toggldesktop#4089]
This just happened today:

The header part of the Windows app looks broken now. Clicking "+ Add time entry" will add a new row in my time tracking log.
![image](https://user-images.githubusercontent.com/17031019/82743203-00210d80-9d1d-11ea-804a-5794d967d85d.png)

When I press play on a previous record to resume tracking time for that, a new row is added, but the timer doesn't start and the time tracked is always 0.

**Comment by jongc** [comment]
Bugs above resolved. What I did was go to the web app and tracked my time there. That seems to have triggered the desktop app to track the same item, syncing and restoring the app's look and settings.

**Comment by IndrekV** [comment]
The screenshot shows manual mode. You can switch to timer mode in the cogwheel menu.

Check out the "Add Time Manually" section in our knowledge base for more details. https://support.toggl.com/en/articles/3836325-toggl-desktop-for-windows-beta
