### ISSUE TITLE
Mini timer not aligning with top edge of screen

### ISSUE THREAD

**Issue by nicktoggl** [toggl-open-source/toggldesktop#4122]
### 💻 Environment
Windows v7.5.162

Platform: Windows Desktop 64bit
OS Version: Windows 10
Toggl Version: 7.5.162

### 🐞 Actual behavior
From the user
"New mini timer (7.5.162 64-bit) on Windows Desktop won't sit at top of screen. It snaps into position about 17px below the top edge. Interestingly when taking a screenshot, ShareX recognises the mini timer window as being the size of the displayed window plus this same ~17px margin on each side. That doesn't stop me from positioning the mini timer against any other edge of my screen - only the top edge is bounced down."

### 💯 Expected behavior
It should allow the mini timer to be aligned along the top of the screen.

### 🔨 Steps to reproduce
1. Try dragging mini-timer to top of screen
2. Check if it aligns with the top of if there is a gap between the top and the mini timer

### 📦 Additional info
Screenshot from user 
![screenshot](https://user-images.githubusercontent.com/17441860/83383852-4ff08a80-a429-11ea-8492-38e2985d31d7.png)

[Case link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/27310418073)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/27288627822)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/27322695156)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/27321311238)

**Comment by VeljkoTN** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/27334291427)
