### ISSUE TITLE
Details popup window is offset below the top of the regular Toggl window

### ISSUE THREAD

**Issue by jasonmansfieldcf** [toggl-open-source/toggldesktop#4143]
### 💻 Environment
Platform: Windows
OS Version: Windows 10
Toggl Version: 7.5.162

### 🐞 Actual behavior
When expanding the details of a time entry, the expanded window is offset from the main window downward by a handful of pixels. This makes the first "Details" input when the timer is placed at the bottom edge of the screen.

### 💯 Expected behavior
Popup is aligned with the main window such that the first Details textbox is fully visible, even when the toggl timer is at the bottom of the screen.

### 🔨 Steps to reproduce

1. With a timer running, click the name of the time entry to open the details popup window
2. See the offset of the popup window

### 📦 Additional info

Keeping the timer in a reserved section of the taskbar is a hugely useful workflow, as it allows it to not obstruct **any** other windows while still always being visible on screen. Previously, the only time the window needed to be moved out from the corner is to edit a time entry, or view past time entries. Now, editing the title of the current time entry is impossible without moving the entire window up.

(An even better fix would be to always place the Details popup window fully on screen, rather than at a fixed position next to the main window, but just fixing this new offset would solve the immediate issue.)

Screenshot showing the offset

![image](https://user-images.githubusercontent.com/26147936/83665039-dd062180-a598-11ea-8048-7cfcd2ebfb2f.png)

Screenshot showing the Toggl timer positioned flush to the bottom of the screen. Note that the first Details textbox is cut off, making it inacessible.

![image](https://user-images.githubusercontent.com/26147936/83665182-1343a100-a599-11ea-862e-fc857adedcd4.png)

**Comment by skel35** [comment]
Fixed in #4634
