### ISSUE TITLE
Clients don't show under "Recent Time Entries"

### ISSUE THREAD

**Issue by dianetoggl** [toggl-open-source/toggldesktop#4150]
### 💻 Environment

Platform: Windows
OS Version: 10
Toggl Version: 7.5.162

### 🐞 Actual behavior
Clients fdon't show under "Recent Time Entries". This is problematic when users have the same project name and time entry description for multiple clients as they are unable to choose the correct time entry from that section.

### 💯 Expected behavior
Client would show along with project and description.

### 🔨 Steps to reproduce

1. Have multiple projects with the same name across different clients (with time entries against them)
2. Type the project name into the description box
3. You will see all projects appear with no idae which client they are associated with

### 📦 Additional info
My own screenshot:
![image](https://user-images.githubusercontent.com/56566095/83980669-b155b380-a96b-11ea-9091-5dd203c1671a.png)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/27369973454)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/27365280198)

**Comment by skel35** [comment]
Proposed solution - show client name in the same way as it's being shown on the time entry details view:
![image](https://user-images.githubusercontent.com/16451391/84122894-c7ce3e80-aa41-11ea-9688-52bda7258725.png)

**Comment by nicktoggl** [comment]
any update on this? We noticed it was listed as a test week tasks, but wanted to check in again. Thanks
