### ISSUE TITLE
Windows desktop - press enter twice to start timer

### ISSUE THREAD

**Issue by nicktoggl** [toggl-open-source/toggldesktop#4158]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.5.162

### 🐞 Actual behavior
From Diane "Looks like Windows Desktop users now have to press enter twice if they are starting a time entry using the keyboard. The first enter closes the drop down suggestion menu and the second starts the time entry. Mac seems to only have to be pressed once."

### 💯 Expected behavior
Pressing enter once should achieve the same outcome

### 🔨 Steps to reproduce
from user

1. For some reason since the last update the first enter hit often doesn't work and I need to hit enter twice. 
2. I'm so used to just typing and hitting enter though I frequently go back and find the timer not running. So frustrating

### 📦 Additional info
[Example case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/27435393952)

**Comment by nicktoggl** [comment]
@dianetoggl for reference :)

**Comment by VeljkoTN** [comment]
I can reproduce this. The problem is that they type a client name, get suggestions but instead of selecting a suggestion they press enter which closes the list of suggestions and another entry is needed to then start the timer with what they typed.
