### ISSUE TITLE
Add "Open TogglDesktop" in the contextual menu of "mini timer".

### ISSUE THREAD

**Issue by rifton007** [toggl-open-source/toggldesktop#4174]
### 💻 Environment
Platform: Windows 10 - 1909

### 📒 Description
In the previous versions, we could open TogglDesktop from the contextual menu of "mini timer".
But in the current version, this item is removed from contextual menu.

### ⭐️ Why do you want this?
It's more user-friendly, we can show quickly the main window of TogglDesktop from the "mini timer".

**Comment by atsvirchkova** [comment]
We have one cogwheel menu, that is used in many different places, including mini timer. And so it would be the easiest solution to add the menu item "Show Toggl Track" everywhere, but make it disabled if the main windows is active. This, of course, means that it will always be disabled, when the menu is opened in main window. Is this OK?
There is also an option to make a checkmark from this item (like it's done for "Use mini timer") and it would be called "Show/Hide Toggl Track", so it would be clickable from main window and wrap it to Windows panel.

**Comment by skel35** [comment]
If the "Show Toggl Track" menu item is invisible instead of disabled then it's fine. Making it disabled clutters the UI.
