### ISSUE TITLE
Project field is being cleared while in Edit view

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4209]
### 💻 Environment
Platform: Linux
OS Version: Linux (Ubuntu 20.04)
Toggl Version: 7.5.205

### 🐞 Actual behavior
The project field becomes empty. If the user clicks Done without doing anything the project is still there, but if the user focuses the project field again and clicks Done afterward the TE's project is cleared.

### 💯 Expected behavior
The project field does not change by itself.

### 🔨 Steps to reproduce
1. Open Edit view
2. Select a project
3. Move focus to another field (e.g. simply press Tab)
4. Wait a couple of seconds

**Comment by wizonesolutions** [comment]
I think https://github.com/toggl-open-source/toggldesktop/issues/3714 fixed this, but they haven't made a new release yet :( I'm going to try the prerelease.

**Comment by wizonesolutions** [comment]
This looks to be fixed in prereleases after June 26, so we just have to wait for a new release.

**Comment by MartinBriza** [comment]
Yes, I think this is fixed now. Of course be sure to reopen if I'm wrong.
