### ISSUE TITLE
Time entry description is cleared whilst user is typing

### ISSUE THREAD

**Issue by dianetoggl** [toggl-open-source/toggldesktop#4217]
### 💻 Environment

Platform: Mac
OS Version: 10.15
Toggl Version: 7.5.192

### 🐞 Actual behavior
When the user types a description into the time entry description field the description is cleared every few seconds. 

### 💯 Expected behavior
Time entry description would stay as is with no overwriting.

### 📦 Additional info
[Intercom link with video ](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481300020285)
User ID: 2304460

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300018739) There's a video in this case too.

**Comment by zdericnina** [comment]
similar issue, [case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300023722) with a video

**Comment by skel35** [comment]
I suspect this is the issue we've had for a long time, but it's been made much worse due to a #4223 slowdown.

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300025674)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300026376)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300026671)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/2759100/conversations/106481300028453)

**Comment by iansltx** [comment]
The text reverting is a pretty serious issue in .210 on macOS as well.

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300030970)
