### ISSUE TITLE
Performance slowdown in windows desktop app

### ISSUE THREAD

**Issue by atsvirchkova** [toggl-open-source/toggldesktop#4223]
### 💻 Environment

Platform: Windows
OS Version: Windows 10.1
Toggl Version: 7.5.208

### 🐞 Actual behavior
A slowdown appeared after commit 2084403d4be0f163702095bd78aa0744298db7e5. The lib function Toggl.Start() now takes about 700-900 ms, while before it used to take about 150-200 ms. After some investigation of c++ code I found that this call
`error err = db()->SaveUser(user_, true, &changes);` takes a lot longer than before.

### 💯 Expected behavior
No lags in application work.

### 🔨 Steps to reproduce

1. Just click the Start button.

### 📦 Additional info
Lags appear not only on Start button, but also on any action that makes saving to database, e. g. setting a project on running entry, a tag and so on.

**Comment by dularion** [comment]
Not sure if a similar method is used & is now slower for mac as well, but I can equally report that the start button, typing an entry, deleting an entry, etc is very slow and takes about a second of freeze before any user interactivity is allowed or the action is performed.

**Comment by vandermerwed** [comment]
I am also experiencing significant delays as described above since a few days ago. I am, however, using version 7.5.193 (Stable).

Platform: Windows
OS Version: Windows 10 Pro
Toggl Version: 7.5.193

**Comment by iamweird** [comment]
I'm experiencing this issue too. I confirm that downgrading app to version 7.5.156 built on May 28th (one day before commit 2084403) solved the issue for me.

Platform: Windows
OS Versions: Windows 10 Pro build 19041
Toggl Version: 7.5.193 through 7.5.203

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/27069426638)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481300017115)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481300017646)

**Comment by skel35** [comment]
The issue was addressed in the latest beta 7.5.213
[macOS](https://github.com/toggl-open-source/toggldesktop/releases/download/v7.5.213/TogglDesktop-7_5_213.dmg)
[Windows 64-bit](https://github.com/toggl-open-source/toggldesktop/releases/download/v7.5.213/TogglDesktopInstaller-x64-7.5.213.exe)

Please let us know if you still experience a significant slowdown on this version

**Comment by nidarasheed** [comment]
Thanks @skel35 ! :)

**Comment by iamweird** [comment]
I don't experience slowdown on 7.5.213. Thanks!
