### ISSUE TITLE
Timeline Zoom buttons showing inconsistently 

### ISSUE THREAD

**Issue by edtamayo** [toggl-open-source/toggldesktop#4226]
### 💻 Environment

Platform: MacOS
OS Version: macOS 10.15
Toggl Version: osx_native_app/7.5.192

### 🐞 Actual behavior
The + and - buttons on timeline show on and off inconsistently not allowing users to click on them

### 💯 Expected behavior
The buttons should always be displayed when the cursor is moved to their location

### 🔨 Steps to reproduce

1. Highlight a TE while on Timeline View
2. Try to click either Zoom Button and it disappears

### 📦 Additional info
The following user has attached a video of the behavior on their end.
[Case link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481300024783)

**Comment by skel35** [comment]
reported internally as well https://toggl.slack.com/archives/C0146DE6SG6/p1594019958171100?thread_ts=1594019929.171000&cid=C0146DE6SG6

**Comment by skel35** [comment]
related to #4138

**Comment by zdericnina** [comment]
[case reference with video](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481304665377)

**Comment by skel35** [comment]
Another internal report of this issue.

I suggest a solution - to simply show zoom buttons at all times.

**Comment by skel35** [comment]
A user mentioned the bug might have appeared after they plugged in a second screen (non-retina), wasn't able to replicate, though.
