### ISSUE TITLE
SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by Vitexus** [toggl-open-source/toggldesktop#4241]
Reports target not shown in Firefox Nightly

https://toggl.space/api/v8/desktop_login

![obrazek](https://user-images.githubusercontent.com/2621130/87474770-f1235100-c623-11ea-8b09-5dcecc87a803.png)

**Comment by skel35** [comment]
@Vitexus I can see your app is connected to the Staging environment, which can happen if you're running the Debug configuration of the app or using the `--staging` cmd line parameter.
If this happens in a production app, please provide proper steps to reproduce according to our bug report template.

**Comment by Vitexus** [comment]
Hi, @skel35 , this is not problem iside app. Problem is certificatate on https://toggl.space/api 
The new browsers deny directly show content without explicit confirmation of accepting risk of ugly certificate.
I think, this is way how to let know your api server admin to install proper certificate.
Have nice day.

**Comment by skel35** [comment]
@Vitexus why do you need to access toggl.space? It's our staging environment. Our production web app is located at toggl.com and the desktop app should connect to that when e.g. clicking the Reports link.

**Comment by Vitexus** [comment]
@skel35 i see it is no problem for you. Thank for explaining.
