### ISSUE TITLE
Windows app starts permanently crashing on Windows 7 when running it while updates are applied

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4247]
### 💻 Environment
Platform: Windows
OS Version: Windows 7
Toggl Version: 7.5.193, 7.5.213

### 🐞 Actual behavior
Either
Windows app starts permanently crashing on startup.
Or
Windows app process hangs together with the updater process.

### 💯 Expected behavior
Windows app should run successfully.

### 🔨 Steps to reproduce
1. Run the older version of the app to make sure the update is being downloaded.
2. Wait for the update to download.
3. Quit the app.

Either

4. Try to quickly launch the app multiple times.

Or

4. Restart the PC.

### 📦 Additional info
Doesn't seem to reproduce on Windows 10.

[Case 1](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481300030303)
[Case 2](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481300030252)
[Case 3](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481300030260)

**Comment by atsvirchkova** [comment]
Here is the error message from Windows event viewer:
`Faulting application name: TogglDesktop.exe, version: 7.5.228.0, time stamp: 0x5f183ab4
Faulting module name: ucrtbase.DLL, version: 10.0.10586.1171, time stamp: 0x59ae5010
Exception code: 0x40000015
Fault offset: 0x00000000000699df
Faulting process id: 0xbe8
Faulting application start time: 0x01d66194cc36db03
Faulting application path: C:\Users\Anna\AppData\Local\TogglDesktop\TogglDesktop.exe
Faulting module path: C:\Windows\system32\ucrtbase.DLL
Report Id: 0c6a1cba-cd88-11ea-bcf0-080027f67187`

**Comment by TheSoloJake** [comment]
User [report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481300001096)

**Comment by skel35** [comment]
Updated steps to reproduce:
1. Run the older version of the app to make sure the update is being downloaded.
2. Wait for the update to download.
3. Quit the app.
4. Restart the PC.
5. Run the app.
