### ISSUE TITLE
"Total today" on mouse hover over menu icon shows running TE instead. 

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#4255]
### 💻 Environment

Platform:  macOS
OS Version:  10.15.4
Toggl Version:  7.5.213

### 🐞 Actual behavior
When you hover over Toggl menu icon, it shows running TE 
![image](https://user-images.githubusercontent.com/49634673/88164214-49161500-cc2d-11ea-9b37-edf2c31abe9b.png)

### 💯 Expected behavior
The hover should show total hours. 

### 📦 Additional info
[Case reference
](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300034139)
[Slack](https://toggl.slack.com/archives/C029WCX0T/p1595409709053500)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300037768)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481303561961)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481305897297)
