### ISSUE TITLE
Incorrect workspace name on Time Entry Edit Popup

### ISSUE THREAD

**Issue by AndrewVebster** [toggl-open-source/toggldesktop#4258]
### 💻 Environment
Platform: macOS
OS Version: Any
Toggl Version: 7.5.228

### 🐞 Actual behavior
Time Entry Edit Popup displays a workspace name at the bottom.
When workspace name has a word in Caps (like an acronym) it will be converted - the first letter is capitalized and rest is lowercase.
E.g. "Team IBM" will be shown as "Team Ibm"

### 💯 Expected behavior
Show the correct workspace name.

### 🔨 Steps to reproduce
1. Find workspace with the name that has acronym or any other word written in caps.
2. Open Time Entry Edit Popup for the TE from this workspace.
3. See workspace label

### 📦 Additional info
<img width="755" alt="Screenshot 2020-07-21 at 20 29 19" src="https://user-images.githubusercontent.com/3470113/88190207-af596280-cc42-11ea-8710-9c687f7f59b4.png">

**Comment by AndrewVebster** [comment]
@skel35 I found that we've introduces capitalisation in https://github.com/toggl-open-source/toggldesktop/pull/3657
Is it okay if I remove it?

**Comment by skel35** [comment]
Yes, it's fine. As you can see, the workspace name has never been displayed verbatim for some reason, and the main point of #3657 was to fix the library.
