### ISSUE TITLE
Click and drag to create entries

### ISSUE THREAD

**Issue by fredcallaway** [toggl-open-source/toggldesktop#4286]
### 💻 Environment

Platform: macOS

### 📒 Description
I think it's self-explanatory. Mouse-down marks the start time, mouse-down marks the end time. Basically, the same functionality as you get in calendar applications.

### ⭐️ Why do you want this?
With the activity guides, it _could_ be easy to retroactively track time by clicking and dragging to create entries that match up with the guides. Currently, you have to double click at the start time, try to guess what time the activity guide ends, enter that as an end time, and then drag to adjust it. It would be much faster (and more intuitive) if this was a single drag and drop action.

**Comment by skel35** [comment]
Hi @fredcallaway !
This feature has already been implemented in https://github.com/toggl-open-source/toggldesktop/pull/4257.
You can try it out in the beta version by downloading it https://github.com/toggl-open-source/toggldesktop/releases/download/v7.5.239/TogglDesktop-7_5_239.dmg or switching to `beta` channel in the About view, or just wait until later this week when it's out in the `stable` channel and the App Store.

Thanks for the interest and have a good day!
