### ISSUE TITLE
Binary sometimes breaks when updating underlying libraries like jsoncpp

### ISSUE THREAD

**Issue by wizonesolutions** [toggl-open-source/toggldesktop#4287]
### 💻 Environment

Platform:  Linux
OS Version:  Manjaro 20.0.3
Toggl Version:  7.5.50

### 🐞 Actual behavior

When running:

`TogglDesktop: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory`

### 💯 Expected behavior

TogglDesktop runs.

### 🔨 Steps to reproduce

1. Upgrade system, including jsoncpp
2. Try to launch TogglDesktop

### 📦 Additional info

Current version of jsoncpp: 1.9.3-1

I'm not sure what I upgraded from--whatever was in an earlier release.

**Comment by MartinBriza** [comment]
Hi, first off: sorry for replying so late. Second: Sorry for being the bearer of bad news. The package in Manjaro is very possibly a third party package over which we have no control. There's a reason we're stuck on an old jsoncpp package and it is that upgrading it causes crashes that we didn't have the time to investigate yet. Overall, if you want a stable experience, I recommend using our Flatpak from flathub.org .
However, from looking at it (and the fact it actually works for me in Fedora with a newer version of jsonccp) it may be a packaging error. Try contacting the maintainer.
To conclude, from my position, there's little I can do to fix this (except of course updating our embedded jsonccp, which will happen in the future), sorry. You can watch this issue to be notified of future updates to jsonccp on our side: #4463

**Comment by wizonesolutions** [comment]
That makes sense. If I hit issues again, I'll look into the Flatpak. For now, simply clean-installing TogglDesktop worked.
