### ISSUE TITLE
Icon Missing from TogglDesktop app in Status Bar

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#4293]
### 💻 Environment

Platform: Linux 
OS Version: Xubuntu 16.04 (xfce4 as desktop environment)
Toggl Version: 7.4.122

### 🐞 Actual behavior
After opening app, a red circle with cross through it appears in lieu of app icon. 

### 💯 Expected behavior
Icon should appear in status bar 

### 📦 Additional info
Intercom [case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481300042509)

**Comment by MartinBriza** [comment]
The version in the report is ancient and many errors similar to this one should be fixed now.
