### ISSUE TITLE
Idle time popup needs better contrast for the Green button in dark mode

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#4295]
### 💻 Environment

Platform: macOS

### 📒 Description

The green button has white text in dark mode, and it's not super easy to read. 
![image](https://user-images.githubusercontent.com/49634673/89519407-c2993000-d7f5-11ea-9f15-2fd9ee861549.png)

### ⭐️ Why do you want this?

To make it easier for users to see the text.

**Comment by skel35** [comment]
adding this to Rebranding project, we should make sure we address this when updating the app colors

**Comment by AndrewVebster** [comment]
Fixed in #4339
