### ISSUE TITLE
Update colors and icons in the macOS app

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4301]
### 💻 Environment
Platform: macOS

### 📒 Description
Update colors and icons in the macOS app according to the upcoming rebranding.

Designs:
https://toggl.invisionapp.com/d/main#/projects/prototypes/20343116
Higher-res icons for the dock:
[MacOS–Icons.zip](https://github.com/toggl-open-source/toggldesktop/files/5041545/MacOS.Icons.zip)

Note: Should not be included in the public release until September 7th.

**Comment by AndrewVebster** [comment]
Closed in #4349
