### ISSUE TITLE
Deprecate 7.4.X macOS versions

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4307]
### 💻 Environment
Platform: macOS

### 📒 Description
7.4.X macOS app versions are outdated now and should be deprecated (i.e. "teapotted").

Reasons to update:
1. The users will get the update UI, various new features like the Timeline UI, and bug fixes.
2. We're getting better analytics tracking.
3. [16K out of 150K reported monthly Bugsnag errors](https://app.bugsnag.com/toggldesktop/toggldesktop/timeline?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[release.seen_in][0][type]=eq&filters[release.seen_in][0][value]=7.4.330&pivot_tab=event&sort=last_seen) are produced by the 7.4.330 macOS app version.
4. We're trying to establish the practice of deprecating the app versions if a newer stable one has been out for a few months for reasons like 1, 2, and others.

To deprecate the apps we should:
1. Get the number of users still using the versions which are to be deprecated.
2. Notify the Support team a week in advance about the upcoming deprecation, mentioning the affected number of users. Discuss with the Support team whether doing any other notification is necessary.
3. File the issue to operations repo, similar to https://github.com/toggl/operations/issues/1477 https://github.com/toggl/operations/issues/1076

**Comment by AndrewVebster** [comment]
Metabase shows that last month we had 2300 users on this version.

**Comment by AndrewVebster** [comment]
Tested on dev environment - v7.4.* is deprecated.
Also found an issue with the current app version not showing the error message - #4487

**Comment by skel35** [comment]
done

**Comment by skel35** [comment]
There's already a drop in Bugsnag errors caused by 7.4.330:

Sep 24th - Oct 1st: [2608 errors, 71 users](https://app.bugsnag.com/toggldesktop/toggldesktop/errors/5c1f32ecb7cf87001a678822?filters[event.since][0]=2020-09-24T13%3A43%3A00.000Z&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[event.before][0]=2020-10-01T13%3A43%3A00.000Z)
Oct 1st - Oct 8th: [421 errors, 43 users](https://app.bugsnag.com/toggldesktop/toggldesktop/errors/5c1f32ecb7cf87001a678822?filters[event.since][0]=2020-10-01T13%3A45%3A00.000Z&filters[error.status][0][type]=eq&filters[error.status][0][value]=open)
