### ISSUE TITLE
Pressing ↓ down arrow key causes suggestion widget to blackout the application when user has yet to input text

### ISSUE THREAD

**Issue by austintraver** [toggl-open-source/toggldesktop#4313]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.15.6
Toggl Version: 7.5.213

### 🐞 Actual behavior

1. User opens the Toggl desktop application
2. User focuses cursor on "What are you doing?" placeholder text
3. User presses the ↓ down arrow key
4. **Application presents matching autocomplete suggestions widget**
5. **Empty widget with no matching results covers entire application**

### 💯 Expected behavior
1. User opens the Toggl desktop application
2. User focuses cursor on "What are you doing?" placeholder text
3. User presses the ↓ down arrow key
4. ~Application presents matching autocomplete suggestions widget~
5. ~Empty widget with no matching results covers entire application~

### 🔨 Steps to reproduce

1. Open the Toggl desktop application
2. Focus cursor on "What are you doing?" placeholder text
3. Press the ↓ down arrow key
4. Witness the empty widget cover the entire application

**Comment by skel35** [comment]
Hi @austintraver !
Thanks for the bug reports, we're appreciating it!

Regarding this particular one, we cannot reproduce it on our side.
Would you mind sharing the feedback through the application (Menu -> Help -> Send Feedback or menubar icon -> Send Feedback)? This way we can have a look at your log files and try to figure out what's going on.

**Comment by austintraver** [comment]
I gave that a shot just now @skel35 and... well... I can't seem to replicate it on my end either. I guess this bug must have been fixed by either my upgrade from Toggl v. `7.5.213` to v. `7.5.254` or by my upgrade to macOS 11.0

I'm going to leave this closed, if another dev ever discovers this bug, feel free to reopen 🌟
