### ISSUE TITLE
App stops working completely unless re-installed

### ISSUE THREAD

**Issue by jspickering** [toggl-open-source/toggldesktop#4317]
### 💻 Environment

Platform: Windows
OS Version: Windows 7
Toggl Version: 7.5.213 (and previously 7.5.162)

### 🐞 Actual behavior

The app is set to run at start-up, but after a couple of weeks usage I can no longer interact with it or manually launch the app, even though the icon remains in the taskbar.

### 💯 Expected behavior

Right clicking on the icon in the taskbar should bring up a menu, and left clicking should open the app interface. Launching the app directly from the Start menu should also open the app.

### 🔨 Steps to reproduce

There are no real clear steps to reproduce it
1. Install TogglDesktop
2. Wait 2-3 weeks
3. App stops opening

### 📦 Additional info

When I had the issue originally with v7.5.162 I tried ending the process with task manager but it didn't help and the problem persisted for maybe a week or two (with numerous PC restarts) before I gave up, uninstalled it, and instead installed v7.5.213. This fixed the issue in the short-term but eventually it stopped working again in exactly the same way yesterday. I don't have this issue with any other software.

I've now repeated the same process of uninstalling and this time installing v7.5.242 which, again, fixed the immediate issue but there may still be an underlying bug which breaks it again.

**Comment by skel35** [comment]
same issue as #4247
