### ISSUE TITLE
Timeline item tooltip is jumping between items after editing running TE

### ISSUE THREAD

**Issue by AndrewVebster** [toggl-open-source/toggldesktop#4326]
### 💻 Environment
Platform: macOS
OS Version: macOS 10.15.5
Toggl Version: 7.5.245

### 🐞 Actual behavior
Editing running TE causes strange behaviour with timeline item tooltip - it jumps from item to item, changing position.

### 💯 Expected behavior
Tooltip doesn't move when editing running TE or at least is closed automatically.

### 🔨 Steps to reproduce
1. Start time entry
1. Open Timeline
1. Hover mouse over some time entry so tooltip is shown
1. Open Edit view for running time entry (but tooltip still should be visible)
1. Edit description

### 📦 Additional info
![Screen Recording 2020-08-16 at 18 11 51](https://user-images.githubusercontent.com/3470113/90337615-4b7d4c00-dfec-11ea-82d4-4eb8c98bd988.gif)

**Comment by skel35** [comment]
The behavior of the timeline item tooltip has been improved, and this bug can't be reproduced since.
