### ISSUE TITLE
Missing callback message appears after updating the app

### ISSUE THREAD

**Issue by atsvirchkova** [toggl-open-source/toggldesktop#4329]
### 💻 Environment

Platform: Windows
OS Version:  Windows 10.1
Toggl Version: 7.5.242

### 🐞 Actual behavior
![image](https://user-images.githubusercontent.com/11901598/90371708-a73ce900-e06f-11ea-904b-218fd09e578b.png)
This message appears after starting the app, when update is pending.

### 💯 Expected behavior
The app starts normally updated to the latest version.

### 🔨 Steps to reproduce

1. Install app version 7.5.242
2. Go to "About" window and choose Dev channel, wait for version 7.5.245 to download but don't click "Update"
3. Quit the app and start it again.
4. See this window

### 📦 Additional info
This bug was very often reproducible and then suddenly it stopped appearing. This might be related to Windows update.

**Comment by skel35** [comment]
This happened when the local database was downgraded. We used to have the same file for the development and production versions of the app, so this happened more frequently. Now it shouldn't be an issue.
