### ISSUE TITLE
Automatically fill in project that was created from project dropdown from Timer UI

### ISSUE THREAD

**Issue by AndrewVebster** [toggl-open-source/toggldesktop#4334]
### 💻 Environment
Platform: macOS

### 📒 Description
It is possible to add a new project from project dropdown on a Timer. But currently when you do so it is not automatically set for the time entry you're creating (or running TE) - dropdown is just closed.
As a user I expect new project to be automatically set for current TE.

**Comment by skel35** [comment]
this also applies to `@` shortcut (#4436)
