### ISSUE TITLE
No notification sound after pomodoro timer

### ISSUE THREAD

**Issue by Alpakash** [toggl-open-source/toggldesktop#4356]
### 💻 Environment
Platform: Windows 10 Home

### 📒 Description
I tried to set a notification sound after the Pomodoro break, I can't find the option somewhere. I found the threat for mac (https://github.com/toggl-open-source/toggldesktop/issues/3369), but not for windows.

**Comment by HangrySensei** [comment]
it's not implemented on windows yet i don't think

i would love to have any sound notifications on windows for pomodoro

**Comment by krasa** [comment]
bump, pomodoro without a sound alarm just sucks.

**Comment by Alpakash** [comment]
Not solved; but closed because the issue wasn't picked up.
