### ISSUE TITLE
Pomodoro overwrites current TE with pomodoro duration when period ends. 

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#4358]
### 💻 Environment

Platform: macOS
OS Version: 10.15.6 (19G2021)
Toggl Version:   7.5.254 beta

### 🐞 Actual behavior

When pomodoro stops, it changes the current running TE (if it is longer) to Pomodoro duration.  

### 💯 Expected behavior

I think it should keep duration intact but stop timer. 

### 🔨 Steps to reproduce
[video here
](https://toggl.slack.com/files/UHVETTGTW/F019LKC5Y3D/screen_recording_2020-08-27_at_1.09.25_pm.mov)
### 📦 Additional info
[Slack](https://toggl.slack.com/archives/C029WCX0T/p1598514949043900)

**Comment by skel35** [comment]
Fixed by #4380
