### ISSUE TITLE
Issues caused by updating the Win app to the latest version

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#4362]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.5.249

### 🐞 Actual behavior

The user initially reached out saying that after upgrading to 7.5.249 64-bit for Windows, the app became extremely slow and frozen up when they click a time entry. They then downgraded it to 7.5.242 and it worked fine again.

I suggested clearing local data and doing a fresh new install of the latest stable version. After they did that they are no longer able to log into the app getting the "login failed, are you online?" error. 

Then they completely removed the latest version (7.5.249) and installed the older version (7.5.242) again and things worked fine with the older version. They confirmed that they are not connected behind any proxy or firewall and that they used the Win app for a while and never had issues before this latest update.

### 💯 Expected behavior
The user should be able to log in normally using the latest version of the Windows app, there should be no performance issues and clearing cache should not result in the inability to log in.

### 🔨 Steps to reproduce
I was not able to reproduce the issue after updating my own desktop app from 7.5.242 to 7.5.249

### 📦 Additional info
[Intercom thread has the logs file](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481301369204) 🔗 

[Slack discussion](https://toggl.slack.com/archives/C029WCX0T/p1598509868038600) 🔗

**Comment by MartinBriza** [comment]
I'm fairly sure this is fixed now.
