### ISSUE TITLE
User unable to save tags on macOS desktop app

### ISSUE THREAD

**Issue by zdericnina** [toggl-open-source/toggldesktop#4366]
### 💻 Environment
Platform: macOS/Windows/Linux
OS Version: Any
Toggl Version: 7.5.245

### 🐞 Actual behavior

Choosing a tag and clicking anywhere on the popup, or pressing enter doesn't allow the tag to save

### 💯 Expected behavior

Tags should be saved by pressing enter or clicking anywhere on the popup

### 🔨 Steps to reproduce

I haven't been able to reproduce it but I believe Diane has.

### 📦 Additional info

User shared a couple of videos showing this behavior, [case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481301370114)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481301373233)
