### ISSUE TITLE
MacOS Pomodoro problems

### ISSUE THREAD

**Issue by nicktoggl** [toggl-open-source/toggldesktop#4371]
### 💻 Environment

Platform: MacOS
OS Version: MacOS - getting more information
Toggl Version: 7.5.254 BETA

### 🐞 Actual behavior
From user 

With the newest version if the clock stops due to the Pomodoro timer it doesn’t reset to 0 and starting a new timer will add a new time entry with the value stuck in the timer.

### 💯 Expected behavior
Normal pomodoro behaviour, resetting to 0 and new timer from 0 duration without a new entry getting created.

### 🔨 Steps to reproduce
I was able to reproduce one, have failed since a [User video available here](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481301371318) 

1. Sert pomodoro to 1 minute
2. starter timer and let run for 1 minute
3. see behaviour when timer stops, check what happens when continuing or stopping through Pomodoro popup and when starting new entry

### 📦 Additional info
[Case reference and user provided video](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481301371318) 

Potential link to https://github.com/toggl-open-source/toggldesktop/issues/4358

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481301373843)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481301368065)

**Comment by edtamayo** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481302466416)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481302468333) Video included

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481302468333) video included

**Comment by edtamayo** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481302469791)
