### ISSUE TITLE
Idle Detection feature keeps time when adding a new entry after being triggered

### ISSUE THREAD

**Issue by edtamayo** [toggl-open-source/toggldesktop#4375]
### 💻 Environment

Platform: MacOS
OS Version: macOS 10.15.6
Toggl Version: 7.5.254 and 7.5.258

### 🐞 Actual behavior
Notice how after selecting "Discard Idle time", the timer field to create a new timer remains at whatever amount the timer was stopped at and starts tracking at that time, clearing cache did not resolve the issue

### 💯 Expected behavior
The timer should start at 00:00 after discarding idle ti,e

### 🔨 Steps to reproduce

1.  Activate the idle notification feature
2. Choose to "Discard idle time" once the feature triggers
3. The timer will look as in the image below, where starting to track a new activity will start at 3:01.

![image](https://user-images.githubusercontent.com/61245582/92042070-44657600-ed2e-11ea-943c-7fb4d2bf63e9.png)

**Comment by edtamayo** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481302466508)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481302468619)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481301380457)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481302470096)

**Comment by nicktoggl** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481301380457)

**Comment by skel35** [comment]
fixed by #4380
