### ISSUE TITLE
Time entries Project and Tag fields are not being updated when continuing a different entry.

### ISSUE THREAD

**Issue by edtamayo** [toggl-open-source/toggldesktop#4377]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.15.6
Toggl Version: 7.4.254 and 7.4.258

### 🐞 Actual behavior
While a time entry is running, switching to a different time entry by pressing Play might not update all the fields on the Time Entry

### 💯 Expected behavior
All time entry fields should change when selecting to continue a different entry

### 🔨 Steps to reproduce

1. Start tracking time on a time entry with a specific project & tag
2. While the first entry is running, click "Play" on a different entry

### 📦 Additional info
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481302467734)
See image for example of reproduction
![image](https://user-images.githubusercontent.com/61245582/92150311-15a1db00-edd4-11ea-9136-bd41b59f5252.png)

**Comment by edtamayo** [comment]
This behavior is sort of difficult to replicate, but I have managed to do it 3 times already, every time I can replicate it is by using brand new time entries, see this other example

![image](https://user-images.githubusercontent.com/61245582/92151217-9b725600-edd5-11ea-9d15-dbd30720e50b.png)

**Comment by skel35** [comment]
Fixed by #4380
