### ISSUE TITLE
sleeping and waking up mac doubles the logged time after continuing

### ISSUE THREAD

**Issue by praveen4463** [toggl-open-source/toggldesktop#4378]
### 💻 Environment
Platform: macOS
OS Version: Mac catalina 10.15.6 (19G2021)
Toggl Version: 7.5.254

### 🐞 Actual behavior
start the timer, let sometime to pass or manually change time, lock the macbook or close the lid so that timer stops. unlock or
open the lid, start the timer, it picks up the last elapsed time and doesn't make it 0 before starting.
So, imagine i've worked for 2 hours, closed my mac, opened mac and continue the timer, it will begin from 2 hours thus
making total elapsed time 2+2 = 4 rather than 2 which is the actual time.

### 💯 Expected behavior
continuing after start shouldn't add last elapsed time into the time mac was closed, this is the same behaviour as if i stop togggle without closing mac and starts it, it start from 0

**Comment by AndrewVebster** [comment]
Hey @praveen4463 
Thanks for the reported issue.

**Comment by skel35** [comment]
fixed by #4380

**Comment by praveen4463** [comment]
Is there any estimated date when will this be released? this is continue to be a problem and pretty confusing, recorded times are getting messed up after every wake up.

**Comment by AndrewVebster** [comment]
hey @praveen4463 
Fix is now released - v7.5.268
Thank you
