### ISSUE TITLE
Time entry suggestions field and dropdown width is too small

### ISSUE THREAD

**Issue by edtamayo** [toggl-open-source/toggldesktop#4395]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.15.6
Toggl Version: 7.4.260

### 🐞 Actual behavior
A user has brought up that while the MacOS app is smaller, the time entry suggestions drop down is too small and unreadable, see this image for reference.

### 💯 Expected behavior
The dropdown should show limited yet readable information

### 🔨 Steps to reproduce

1.  Minimize the width of your app window
2. Begin typing a time entry to show suggestions

### 📦 Additional info

![image](https://user-images.githubusercontent.com/61245582/92537534-2ba70580-f1f1-11ea-92fa-703d2f6c26f9.png)

**Comment by edtamayo** [comment]
[Case Link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481302469493)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481302472214)
