### ISSUE TITLE
Reset to original colors in buttons and Dock icon

### ISSUE THREAD

**Issue by emersonf** [toggl-open-source/toggldesktop#4407]
### 💻 Environment
Platform: macOS

### 📒 Description
The rebrand changed the colours of various buttons and the Dock icon. The new colours don't indicate whether timers are running or not.

The Dock icon and the timer icon colors don't even match anymore. Instead we have four different colors for two states.

Tracking:
<img width="224" alt="Screenshot 2020-09-10 at 19 13 49" src="https://user-images.githubusercontent.com/834831/92770074-df4af980-f399-11ea-8595-45f6f86f7b6b.png">

Not tracking:
<img width="191" alt="Screenshot 2020-09-10 at 19 14 03" src="https://user-images.githubusercontent.com/834831/92770107-e5d97100-f399-11ea-9dd6-591596f23861.png">

### ⭐️ Why do you want this?
UX has been seriously hindered by this IMO. It's no longer crystal clear whether time is currently being tracked, which is Toggl's core feature. It's one thing to go from red to pink in branding. But red means on and gray means off and pinks don't carry that kind of information. To go from red to pink and gray to another pink in functional UI elements is bizarre and counter-productive.

**Comment by sterid** [comment]
New release isn't good enough. So many color issues. With buttons. With pink dark in dark mode. and so on. 

I hope they will be fixed soon.

**Comment by skel35** [comment]
icons have been tweaked in #4480, "not running" means gray again
