### ISSUE TITLE
Some tags are not loaded correctly

### ISSUE THREAD

**Issue by dkoerner85** [toggl-open-source/toggldesktop#4414]
### 💻 Environment
Platform: macOS
OS Version: 10.15.5 Catalina
Toggl Version: 7.5.268

### 🐞 Actual behavior
Some entries are loaded from the server without tags, which affects grouping of the entry. It is also very confusing.

### 💯 Expected behavior
There should be no difference w.r.t. tags between entries viewed in the web App and the desktop App.

### 🔨 Steps to reproduce
1. Create a new entry in the desktop App.
2. Add a project.
3. Add a tag. The tag is visible both in the web App and Desktop App.
4. Restart toggl Desktop.
5. The tag is no longer visible in the Desktop App, but still visible in the web App.

### 📦 Additional info
Web App entries:
![Bildschirmfoto 2020-09-14 um 11 28 14](https://user-images.githubusercontent.com/32361860/93071122-01859580-f680-11ea-94eb-923cf8dbe269.png)

Desktop App entries:
![Bildschirmfoto 2020-09-14 um 11 28 24](https://user-images.githubusercontent.com/32361860/93071140-09ddd080-f680-11ea-8419-82bf40807102.png)

I am happy to provide further information as required.

**Comment by Nikkelmann** [comment]
Same, but for windows.
Can also reproduce just by starting an empty entry and selecting a previous entry from the description drop-down (no restart of the app needed).

💻 Environment
Platform: Windows 10 Pro
OS Version: 2004 build 19041.508
Toggl Version: 7.5.260 (64-bit)

**Comment by AndrewVebster** [comment]
Thanks for filling in the issue!
Fixed in PR https://github.com/toggl-open-source/toggldesktop/pull/4412 
Will be available in the next app update

**Comment by dkoerner85** [comment]
I can confirm that the issue was resolved with the latest update (7.5.279), but only for entries not in the cache. So after the update, I had to manually clear the cache using the menu entry 

Account -> Clear Cache

Otherwise, tags would not be applied correctly when resuming old entries.
