### ISSUE TITLE
Microsoft Store version of the app doesn't handle togglauth:// redirect (SSO)

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4420]
### 💻 Environment
Platform: Windows
Toggl Version: 7.5.260

### 🐞 Actual behavior
Redirect from SSO sign-in into the Windows desktop app does not work.

### 💯 Expected behavior
Redirect from SSO sign-in into the Windows desktop app should work.

### 🔨 Steps to reproduce
1. Run Microsoft Store app
2. Try to log in with SSO

**Comment by kadrihvl** [comment]
[Case]([url](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3724360/conversations/106481301374612))
