### ISSUE TITLE
Change icons for Windows app

### ISSUE THREAD

**Issue by atsvirchkova** [toggl-open-source/toggldesktop#4429]
### 💻 Environment

Platform: Windows

### 📒 Description
New icons are here: https://toggl.invisionapp.com/console/Unified-Icons-ckf2nz18d1lno01am3mz94alp/ckf88skdu00nl013dbp1m6nx4/play

**Comment by skel35** [comment]
Note that the tray icon, the app shortcut, and the taskbar icon (the main app icon basically) should use the "favicon" type of icon (without purple borders)
![image](https://user-images.githubusercontent.com/16451391/94229547-87b79c80-ff08-11ea-8a55-97d2876c8413.png)
