### ISSUE TITLE
Add analytics to track description shortcuts usage

### ISSUE THREAD

**Issue by AndrewVebster** [toggl-open-source/toggldesktop#4439]
### 💻 Environment
Platform: macOS

### 📒 Description
Track the usage of shortcuts feature.
We should be able to see how many users are using this feature weekly.

- [ ] TBD: what should be counted as a "feature usage" in this case? Opening the dropdown, choosing something from the dropdown, or other?

**Comment by skel35** [comment]
Opening the dropdown can be accidental, so I would consider choosing something from the dropdown as a "feature usage".

Events can be tracked as:
Category: `timer-shortcut`
Event Names: `project-select`, `tag-select`, `project-create`, `tag-create`.
