### ISSUE TITLE
Time entries being marked as non-billable even when attached to a billable Project

### ISSUE THREAD

**Issue by zdericnina** [toggl-open-source/toggldesktop#4466]
### 💻 Environment

Platform:  macOS
OS Version:  10.15.6
Toggl Version:  7.5.286

### 🐞 Actual behavior

Time-entries are marked as non-billable even when Project is billable by default 

### 💯 Expected behavior

If Project is marked as billable, all associated time entries should be billable as well (unless user manually changes it)

### 🔨 Steps to reproduce

1. Start a blank timer
2. Enter a new TE description and switch to another window (with alt-tab)
3. After a few seconds click on the TE description, delete it, and select a previously-used description from the list that has a billable project
4. The description and project are assigned but the billable state remains OFF.

### 📦 Additional info

[Case reference with video attached](https://app.intercom.com/a/apps/ayixs927/inbox/conversations/106481304659936)

**Comment by skel35** [comment]
I believe this requires the default project to belong to a non-premium workspace.
If the default project is empty, it should mean the default workspace is used (need to re-check our logic here).
