### ISSUE TITLE
Copy iCal option ins't working 

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#4468]
### 💻 Environment

Platform: 
OS Version: 
Toggl Version: 

### 🐞 Actual behavior
The copy ical option is not working. When you click Copy, it does not copy anything. 

### 💯 Expected behavior

The copy iCal option should copy the iCal link 

### 🔨 Steps to reproduce

1. Open Settings
2. Click 3 dot control 
3. Click Copy

Nothing will be copied. 

### 📦 Additional info

[Case reference
](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481304660860)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481304660825)

**Comment by skel35** [comment]
The desktop app doesn't have an iCal integration, this has to be filed elsewhere (FE presumably)
