### ISSUE TITLE
Dismiss the timeline popup when the item is not being hovered over

### ISSUE THREAD

**Issue by zdericnina** [toggl-open-source/toggldesktop#4482]
### 💻 Environment

Platform:  macOS

### 📒 Description

When using macOS app in timeline view, hovering over activity or time entry, displays a popup that lingers until you click on the time entry or switch the view. We should make the popup disappear when it’s not in focus, i.e. moving cursor away from the activity.
<img width="448" alt="Screenshot 2020-09-21 at 10 37 13" src="https://user-images.githubusercontent.com/19727123/94682623-841b7f80-0325-11eb-8ad0-b63de8bb63b8.png">

### ⭐️ Why do you want this?

Users reported the lingering popup is disrupting, [case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481303558689)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481304662225)
