### ISSUE TITLE
mini timer not stays on top of taskbar

### ISSUE THREAD

**Issue by dkern** [toggl-open-source/toggldesktop#4497]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.5.282

### 🐞 Actual behavior
When the mini timer is placed over the taskbar and something else on the taskbar is clicked, the mini timer gets behind the taskbar.

### 💯 Expected behavior
If the option "keep on top" is activated in settings, it should stay on top of the taskbar too.

**Comment by skel35** [comment]
Hey @dkern! Thanks for reporting the issue.
We're aware of this usage scenario. Unfortunately, it's practically impossible to maintain any window on top of the taskbar when the taskbar gets focused.
To solve this issue, we're considering embedding the mini timer into the taskbar itself https://github.com/toggl-open-source/toggldesktop/issues/3142, so hopefully, that would resolve the problems you're experiencing.
