### ISSUE TITLE
Upgrade to 7.5.296 does not work

### ISSUE THREAD

**Issue by lioman** [toggl-open-source/toggldesktop#4504]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14
Toggl Version: 7.5.286 

### 🐞 Actual behavior
Update is downloaded, restart is requested. After restart Ground-Hog-Day-Mode is activated and upgrade is downloaded...

### 💯 Expected behavior
It should download new version and restart once

### 🔨 Steps to reproduce

1. let app download upgrade
2. wait for restart request
3. restart toggl

### 📦 Additional info
Manual updating kind of works. App is renamed and perhaps this is the root cause why upgrade does not work in the first place.

**Comment by AndrewVebster** [comment]
hey 👋 
thanks for posting this! 
There is a new version on Beta channel - 7.5.298. If possible could you please approve that now it updates without problems?
Thanks in advance

**Comment by lioman** [comment]
Now it works

**Comment by AndrewVebster** [comment]
Thank you!
Closing this issue as fixed
