### ISSUE TITLE
"Home" and "End" keys don't act in a standard way

### ISSUE THREAD

**Issue by vanastassiou** [toggl-open-source/toggldesktop#4512]
### 💻 Environment

Platform: Linux
OS Version: Ubuntu 20.04
Toggl Version: 7.4.528

### 🐞 Actual behavior
"Home" and "End" keys do not work in a standard way when pressed with the cursor in the "What are you doing" and "Projects" fields. If there are entries in the drop-down, "Home" and "End" go to the first and last entries, respectively. If the drop-down is empty, the keys do nothing.

### 💯 Expected behavior
"Home" and "'End" should take the cursor to the beginning and end of a text field, respectively.

### 🔨 Steps to reproduce

1. In Toggl Desktop, click the `What are you doing?` field and enter text
2. Test "Home" and "End" key behaviour
3. Press Start, then Stop
4. Click the new log entry
5. With the cursor in the field containing the entry's name, test "Home" and "End" key behaviour
6. Repeat 5 in the Projects field below

### 📦 Additional info

This appears similar to the behaviour reported in https://github.com/toggl-open-source/toggldesktop/issues/3384, but doesn't seem to have been resolved.

**Comment by MartinBriza** [comment]
Hm, I was testing my version like crazy to find the behavior you're describing and writing a new solution for it only to see for me the behavior is actually reversed than what you describe. Then I realized you're on 7.4.528 which is a pretty old version, can you please upgrade to a newer one? 
You're right there was a small issue though: Home/End now only affected only the cursor in the edit field. It's probably better for it to affect it only when the dropdown is not visible so I'm changing that behavior in a PR that's coming in a few minutes.

**Comment by vanastassiou** [comment]
Hi Martin -- you're right, I just now updated to 7.5 and behaviour is in line with what's expected. I wasn't getting any update notices in the About window in 7.4 so I'd assumed that was it. Thanks for getting back to me.
