### ISSUE TITLE
Ambiguous layout error in Timeline view

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4520]
### 💻 Environment
Platform: macOS
Toggl Version: 7.5.286

### 🐞 Actual behavior
Ambiguous layout error (unusable app, a purple window behind the main window)

### 💯 Expected behavior
No errors

### 🔨 Steps to reproduce
1. Open the Timeline view
2. Create 2 overlapping TEs (e.g. 10:00-10:30, 10:15-10:45)
3. Click to the left of the second TE (e.g. around 10:40).

### 📦 Additional info
![image](https://user-images.githubusercontent.com/16451391/95719770-fc186c80-0c78-11eb-9663-b45cf8535ab5.png)

**Comment by AndrewVebster** [comment]
@skel35 this one seems like fixed, but don't know how and when 🤔. Could you please check, because now I cannot reproduce it?

**Comment by skel35** [comment]
@AndrewVebster It is still reproducible, but you have to click-drag instead of clicking (apparently because clicking was handled in #4470)
