### ISSUE TITLE
Tags list in the Timer tags dropdown is broken before Edit view is open

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4553]
### 💻 Environment
Platform: macOS
Toggl Version: `master` (7.5.329)

### 🐞 Actual behavior
Tags list is either partial or empty or containing tags from different workspaces.

### 💯 Expected behavior
Tags list contains all the tags from the default or the selected workspace.

### 🔨 Steps to reproduce
1. Start the app
2. Click the tags selection button in the timer

May not reproduce every time.

### 📦 Additional info
Example screenshot - the tags list is shown from the wrong workspace
![image](https://user-images.githubusercontent.com/16451391/96257541-38263700-0fc3-11eb-958d-8ef9d94fe2a8.png)

**Comment by AndrewVebster** [comment]
@skel35 I think it was closed in PR #4552. Could you please test when you'll have some time?

**Comment by skel35** [comment]
Sure, I actually remember I was testing this scenario. Just forgot about this open issue
