### ISSUE TITLE
Tags don't get synchronized to Mac client, when created via API

### ISSUE THREAD

**Issue by brtx** [toggl-open-source/toggldesktop#4554]
### No Duplicate

Check

### 💻 Environment

MacOS Catalina 10.15.6
Toggl Track 7.5.286

### 🔨 Steps to reproduce

1. Create one entry in Mac client (I use manual mode), having some description, project and time.
2. Add one tag via the API.

### 🐞 Actual behavior

- I am creating tags via the toggl API.
- Those tags are immediately reflected in the web client as expected.
- However **in the Mac client they do not appear**.
- When I restart the mac client they do not appear.
- When I manually sync they do not appear.
- When I clear the cache and log in again they do appear.
- When I manually create tags via the web client, they do appear.

- I also observed (but not consistently) those vie API created tags disappearing in general (not only in the Mac client) and I assume this may be a follow up issue, where the missing tag is synced back to the server from the Mac client, resulting in entirely lost tags.

### 💯 Expected behavior

- Tags should be synced successfully to the Mac client also when created via the API.

### 📦 Additional info

none

**Comment by skel35** [comment]
Thanks for the report.
We're aware of the issue #2513. We've implemented the updated syncing and planning to release it soon after we handle some technicalities (no ETA for now, unfortunately).
