### ISSUE TITLE
Edit view is only partly visible when main window is small and near the bottom of the screen

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#4555]
## 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.5.295

### 🐞 Actual behavior
When the app's main window is small and on the bottom of the screen, clicking on an entry to edit it presents a clipped-off edit popup

### 💯 Expected behavior
The edit popup should automatically adjust itself to show completely, no matter where the main app window may be.

### 🔨 Steps to reproduce

1. Make main app window small and place at bottom of screen near task bar 
2. Click on new entry or click on entry to edit it
3. View issue

### 📦 Additional info
User [report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/mentions/conversations/106481304716916) (contains screenshot)

**Comment by skel35** [comment]
related #4143
