### ISSUE TITLE
Display currently running time entry in the Timeline UI

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4577]
### 💻 Environment
Platform: Windows

### 📒 Description
Display currently running time entry in the Timeline UI. The time entry should not have rounded corners on the bottom and should be well aligned with the line showing the current time.
Already implemented in the macOS app in #3814

**Comment by GitMurf** [comment]
Not sure if this is the same thing, but while a timer is going on, it doesn't show it in timeline until after I stop the time entry.
