### ISSUE TITLE
macOS Timeline UI - Time entries going past midnight are shown only on the day they were started

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4598]
### 💻 Environment
Platform: macOS
Toggl Version: 7.5.348

### 🐞 Actual behavior
I started a timer at 10:17pm on Thursday October 22 and ended it at 1:31am on Friday October 23. It shows on the timeline for Thursday up until Midnight but on Friday, it doesn't show anything from 12am to 1:31am. See screenshots at bottom of issue.

### 💯 Expected behavior
Should show the time entry on the Friday timeline view from 12am to 1:31am as continuation from the previous night.

### 🔨 Steps to reproduce
1. Start a timer on a given night
2. Have the time go past midnight
3. Stop the timer

**Comment by AndrewVebster** [comment]
@atsvirchkova closed this in PR [#4638](https://github.com/toggl-open-source/toggldesktop/pull/4638)
