### ISSUE TITLE
New project autocompletion modal without user intention to create new one

### ISSUE THREAD

**Issue by dandaka** [toggl-open-source/toggldesktop#4604]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.15.7
Toggl Version: 7.5.72

### 🐞 Actual behavior

1. User starts the timer without selecting a project
2. User wants to select a project
3. User clicks on "+Add description"
4. Sees a modal
5. Enters the name of a task
6. Presses TAB
7. Enters two letters of an existing project (in my case "Ar")
8. Sees another modal "Create new project" with filled another existing project (no letters in both names are related)

<img width="148" alt="existing-project" src="https://user-images.githubusercontent.com/2384694/97325688-ee1f3a00-187b-11eb-8378-7c5c53328f55.png">

### 💯 Expected behavior

1. User starts the timer without selecting a project
2. User wants to select a project
3. User clicks on "+Add description"
4. Sees a modal
5. Enters the name of a task
6. Presses TAB
7. Enters two letters of an existing project (in my case "Ar")
8. Sees autocompletion with existing project
9. Doesn't see modal to create a new project

**Comment by skel35** [comment]
Hi @dandaka!
I wasn't able to reproduce the bug based on your steps.

Could you please
1. Update your app to the latest stable version (from within the app, via store, or by downloading https://toggl.github.io/toggldesktop/download/macos-stable/ )
2. In case it can still be reproduced, send us a short screen recording.

Thanks!

**Comment by dandaka** [comment]
Not reproducible on the new version
