### ISSUE TITLE
Add analytics to track Duration Dropdown usage

### ISSUE THREAD

**Issue by AndrewVebster** [toggl-open-source/toggldesktop#4612]
### 💻 Environment
Platform: macOS

### 📒 Description
Category: `timer-duration-dropdown`
Event Names:
- `start-time-change` - user changed text in Start Time field (reported after field loses focus)
- `date-change` - user changed TE day via a calendar, arrow buttons, or date picker (reported on every click)

**Comment by AndrewVebster** [comment]
Propose:
Category: `timer-duration-dropdown`
Event Names: 
- `start-time-change` - user changed text in Start Time field (reported after field loses focus)
- `date-change` - user changed TE day via a calendar, arrow buttons, or date picker (reported on every click)

@skel35 what do you think?

**Comment by skel35** [comment]
@AndrewVebster sounds good 👍
