### ISSUE TITLE
Remove the ability to open Edit popover for running entry from Timer

### ISSUE THREAD

**Issue by AndrewVebster** [toggl-open-source/toggldesktop#4619]
### 💻 Environment

Platform: macOS

### 📒 Description
When duration dropdown is implemented there is no need in Edit popover for running TE. It should be removed, so when TE is running and the user clicks on Timer background it's not shown.

**Comment by skel35** [comment]
Here we need to also decide on these:
1. Are we removing the "Open edit view when starting a time entry" setting?
2. Are we keeping the Cmd+E shortcut to open an Edit view for a running time entry?

**Comment by JanikaMandel** [comment]
Hi, thank you @AndrewVebster for bringing my attention here :)
1. Yes, there is no need for the pop-up in the timer now as all actions can be done using the timer itself.
Note! Create a new project functionality should also be added before we do this.
2. Ideally, also this can be removed for the same reason as above... but we can also wait and leave it as back-up for 2 weeks after removing the edit pop-up so if there are any troubles then this is the way to access edit pop-up. Then if no problems arise we can also remove this functionality

**Comment by skel35** [comment]
Note: when removing  "Open edit view when starting a time entry" we need to verify that it's convenient to edit the TE with a keyboard (e.g. keyboard focus does not get lost), especially in cases where the user is starting a time entry using a keyboard shortcut

**Comment by AndrewVebster** [comment]
@skel35 @JanikaMandel how about we leave both options as they are? It shouldn't harm any users, but removing those could break some workflows.
As Taras said in the last comment, right now it's impossible to start new TE with ⌘N shortcut and fill in the info after that, without touching a mouse.
So for now I propose to just remove the clickable area on Timer that opens the Edit screen. 
What do you think?

**Comment by skel35** [comment]
leaving both options sounds reasonable to me
