### ISSUE TITLE
Windows Timeline - Click and drag right side dashed line next to "Activity"

### ISSUE THREAD

**Issue by GitMurf** [toggl-open-source/toggldesktop#4628]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.5.348

### 🐞 Actual behavior

The dashed vertical line between time entries and the Activity bars allows click and drag to extend or shrink but it doesn't do anything other than shrink the width of the time entries themselves.

### 💯 Expected behavior

Not sure what the expected behavior is or should be. Just weird bug. Preferably I'd love to be able to make wider the activity column to show maybe details of the activity without having to hover over the pink activity items?

### 🔨 Steps to reproduce

See the GIF below

### 📦 Additional info

![Click drag issue](https://user-images.githubusercontent.com/64155612/97750377-e3e48200-1aad-11eb-9c0f-2c52a58b83ed.gif)

**Comment by skel35** [comment]
Proposed solution:
1. Disable the dragging until we implement something better.

2. a) Make the actual line draggable, fix the dragging direction
2. b) Implement the wide-view of the activity block, and enable it if the width of the section is > X px
