### ISSUE TITLE
Windows Timeline - Add the "+" sign for new entry from the last time entry until current time

### ISSUE THREAD

**Issue by GitMurf** [toggl-open-source/toggldesktop#4630]
### 💻 Environment

Platform: Windows

### 📒 Description

I want to be able to have available the "+" sign on the left that allows for a quick new entry from the end time of the previous entry until now (current time).

Two Use Cases / Options from this

1. I just finished doing a task and I go "oh i forgot to start the timer". So I want to just easily be able to go create a new entry that went up until just now and started from the time the last entry ended.
2. A variation to 1... I am in a meeting 20 minutes in and I go "oh i forgot to start my timer". I want to press the "+" sign that creates a time entry with a "start time" of the time my last entry finished BUT keep the timer still running as I am still in the meeting.

Ultimately to cover both use cases I would be fine with and good with # 2 being the implemented choice as I could cover # 1 easily by clicking the "+", the timer is still running but then just simply have to stop the timer because the task is done. So it would allow me to do both use cases!

See screenshot below.

### ⭐️ Why do you want this?

![image](https://user-images.githubusercontent.com/64155612/97751724-0a0b2180-1ab0-11eb-9094-bb05d7d589b9.png)

**Comment by skel35** [comment]
Thanks for the report and for describing the use case. 
We'll think about adding this feature (probably Option 2) as it seems reasonable.
