### ISSUE TITLE
Bad color contrast on time entries on MacOS Timeline

### ISSUE THREAD

**Issue by edtamayo** [toggl-open-source/toggldesktop#4664]
### 💻 Environment

Platform: macOS
OS Version: macos 10.15.1
Toggl Version 7.5.363
 

### 🐞 Actual behavior
When changing from Light to Dark display setting on MacOS, the Toggl Track desktop app will switch display a bad contrast on time entries

See image for reference 
![image](https://user-images.githubusercontent.com/61245582/98990382-3d51a580-24df-11eb-888a-22ef55919d21.png)

! This can be fixed by just closing and re-opening the app

### 💯 Expected behavior
The contrast of text on time entries should change properly without restarting the app

### 🔨 Steps to reproduce

1. Open the app in timeline view
2. Change the Light/Dark display setting from the MacOS general preferences

Related to case: [Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481305867861)

**Comment by skel35** [comment]
Related to #3160
