### ISSUE TITLE
Context menu for TEs in Timeline view (Windows)

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4670]
### 💻 Environment
Platform: Windows

### 📒 Description
Introduce a context menu for time entries in the Timeline view.

Context menu items:
- "Continue this entry"
- "Start entry from the end of this entry" if the selected day is today, or "Create entry from the end of this entry" if the selected day is different (will create a 1h time entry and open the Edit view).
- "Delete"
-------------------------------- (separator)
- "Change first entry stop time" (enabled only if a time entry is intersecting with another time entry)
- "Change last entry start time" (enabled only if a time entry is intersecting with another time entry)

**Comment by atsvirchkova** [comment]
This is size-L as a whole task. I suggest it to be split into 2 tasks:
1. Menu without resolving overlaps.
2. Resolving overlaps (both logic and UI).

**Comment by skel35** [comment]
Please create separate issues then and estimate them separately 👍

**Comment by skel35** [comment]
split into #4684, #4685
