### ISSUE TITLE
TEs are displayed as overlapped when they are actually not

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4673]
### 💻 Environment
Platform: Windows
Toggl Version: 7.5.382

### 🐞 Actual behavior
TEs are shown as overlapped.

### 💯 Expected behavior
TEs should not be shown as overlapped

### 🔨 Steps to reproduce
1. TE #1: 10:28:18 -> 10:30:28
2. TE #2: 10:30:30 -> 10:43:44
3. Zoom out to the last or second last zoom level.

### 📦 Additional info
![image](https://user-images.githubusercontent.com/16451391/99284314-c732a300-283e-11eb-93b8-ecb6e7fbdca5.png)

macOS:
![image](https://user-images.githubusercontent.com/16451391/99284402-e29dae00-283e-11eb-97e5-eb521f900120.png)

Note: It's better to show overlaps correctly instead of making sure the TE is fully visible, so it's fine if the TE is rendered partially on top of the previous one.

**Comment by atsvirchkova** [comment]
This is a bug. The TEs are placed using their start and end times according current overlapping algorithm. The reason why this happens is the logic that was introduced specifically for resizing - start/end time became dependent on vertical offset/height. There is an easy way to fix this: just using the start/end times of original TogglTimeEntryView for algorithm.
