### ISSUE TITLE
Error message is compressed when app is built on Big Sur

### ISSUE THREAD

**Issue by AndrewVebster** [toggl-open-source/toggldesktop#4674]
### 💻 Environment

Platform: macOS
OS Version: macOS 11 Big Sur
Toggl Version: 7.4.283 if built on Big Sur with Xcode 12

### 🐞 Actual behavior

Error view is compressed when shown on Timeline tab.

### 💯 Expected behavior

Error view should be displayed correctly.

### 🔨 Steps to reproduce

1. Open Timeline
2. Do something to trigger the error dialog. E.g. create TE on expired workspace
3. Error is shown
4. In 80% it's layout is broken/compressed/cropped

### 📦 Additional info

<img width="503" alt="Screenshot 2020-11-16 at 19 46 57" src="https://user-images.githubusercontent.com/3470113/99290440-f64d1280-2846-11eb-96b0-b0c6b660f09d.png">

**Comment by skel35** [comment]
@AndrewVebster Do you know why this occurs on the Timeline view but does not occur on the Login view (tested using the same error messages)?
