### ISSUE TITLE
Application doesn't launch on Windows 7

### ISSUE THREAD

**Issue by atsvirchkova** [toggl-open-source/toggldesktop#4682]
### 💻 Environment

Platform: Windows
OS Version: Windows 7
Toggl Version: 7.5.383

### 🐞 Actual behavior
Toggl process stays in Task Manager after app quit.

### 💯 Expected behavior
No Toggl processed must stay alive after app quit.

### 🔨 Steps to reproduce

1. Start Windows 7 and run Toggl Track.
2. Quit Toggl Track and see that its process stays in Task manager.
3. It's impossible to start Toggl Track again until the process is killed in Task manager.

### 📦 Additional info
It's reproducible ONLY after Windows 7 restart, so to reproduce it once more it's necessary to reboot Windows.

**Comment by skel35** [comment]
Looks like the https://github.com/toggl-open-source/toggldesktop/pull/4331 solution was applied only when the updater was launched and simply did not cover this scenario. This should be an easy fix then.
Executing the process kill should probably be done only on Windows 7, or under some sort of timeout.
