### ISSUE TITLE
Check time entry list performance degradation after Timer UI update (macOS)

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4706]
### 💻 Environment
Platform: macOS

### 📒 Description
Check if the time entry list and/or timer start/stop performance degraded after Timer UI update was introduced on macOS.
If the performance degradation has been introduced - open an issue to fix it.

**Comment by AndrewVebster** [comment]
Created 500+ time entries for two days. 
Tested two app versions:
- v7.5.245 - without Time UI update
- v7.5.409 - latest stable

Both of them behave similarly but the old version is a lot worse with the Timeline:
- Switching from List to Timeline on the old version took ~10 sec and the app was stuck, when with a new app it was ~1-2 sec.
- Drag-creating new TE was also harder with the old version but actually, both of them don't perform well here. But of course, Timeline had around 300 time entries to display.

So the conclusion is that app performers were not affected by the latest updates.
