### ISSUE TITLE
Update duration when user editing start time and closing duration dropdown by clicking outside

### ISSUE THREAD

**Issue by AndrewVebster** [toggl-open-source/toggldesktop#4741]
### 💻 Environment

Platform: macOS
OS Version: Any
Toggl Version: 7.5.386

### 🐞 Actual behavior

When the user edits the start time and the popup is closed in response to the user clicking outside the popup (as opposed to pressing Esc, for example), the start time is not updated.

### 💯 Expected behavior

To ensure consistency with the web app behavior and because it makes more sense, when the Duration dropdown is closed when a user is editing the start time, the time should be updated.
If a user is closing the dropdown with Esc key, the time should stay the same.

### 🔨 Steps to reproduce

1. Click on duration field to open dropdown
1. Click on start time field
1. Edit start time
1. Click outside to close the dropdown
1. Observe that duration not changed 

### 📦 Additional info

Discussion on [Slack](https://toggl.slack.com/archives/C029WCX0T/p1607429374433000?thread_ts=1607426881.432600&cid=C029WCX0T).

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481306016104)
