### ISSUE TITLE
Add setting to opt-out of analytics tracking

### ISSUE THREAD

**Issue by nikitalita** [toggl-open-source/toggldesktop#4782]
### 💻 Environment

Platform: macOS/Windows/Linux

### 📒 Description

Add the ability to opt-out of analytics tracking.

### ⭐️ Why do you want this?

I like my privacy, and I would prefer not to have my app usage tracked, especially when it's sent to a third-party for processing first, and ESPECIALLY when that third-party is Google. I'm loathe to use the app without this feature.

**Comment by nikitalita** [comment]
I took a crack at implementing it here, but it keeps throwing on the database selection here: https://github.com/nikitalita/toggldesktop/blob/analytics_opt_out/src/database/database.cc#L416 

I can't figure out why because I can't figure out how to compile POCO's sqlite driver with debug symbols.

**Comment by nikitalita** [comment]
Nvm, I figured it out, and it's working now. I'll submit a PR.

**Comment by nikitalita** [comment]
BTW, since I got analytics opt-out working, I've been using the app in earnest and it's really great!

**Comment by skel35** [comment]
Unfortunately, we won't be implementing this: https://github.com/toggl-open-source/toggldesktop/pull/4783#issuecomment-761037077
As our app is open-source, you're of course free to use your own fork of the app without analytics tracking.
