### ISSUE TITLE
Time format in Timeline view issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#4785]
### 💻 Environment

Platform: Windows
OS Version: Windows 10.1
Toggl Version: 7.5.418

### 🐞 Actual behavior
Your selected time format (profile settings page via the web app) is not reflected in the Timeline view, if you choose the 24-hour format the timeline view will remain in the AM/PM format. There's also an error for the stop time, as you can see in the following example, it shows an AM/PM start time and a 24h format stop time with PM added (15:17 PM): 

![image](https://user-images.githubusercontent.com/36152180/103545381-c5ca4200-4ea1-11eb-831c-c6c63316d446.png)

### 🔨 Steps to reproduce

1. Open the app
2. Go to Timeline view
3. Hover your mouse over a time entry and check the time format

[Intercom link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481306148188)

**Comment by atsvirchkova** [comment]
Same issue for macOS https://github.com/toggl-open-source/toggldesktop/issues/4110
