### ISSUE TITLE
Dual monitor setup - issues with edit window

### ISSUE THREAD

**Issue by nicktoggl** [toggl-open-source/toggldesktop#4802]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: windows_native_app/7.5.418

### 🐞 Actual behavior
"I use a multi-monitor setup. my main monitor is a 27 inch 4k monitor, and second is a 23 inch ips monitor. When the toggltrack app is open on the 2nd monitor, when clicking on the time entry, the pop out window does not display to edit details, but will appear if the app runs on the main monitor.

More steps and screenshots are included at [Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481306149135)

### 💯 Expected behavior
Clicking entry should reveal window to edit entries

### 🔨 Steps to reproduce
Please see intercom case, has step-by-step instructions on replicating with screenshots. Protecting user data by not posting those here

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481306149135)

### 📦 Additional info
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481306149135)
[Slack conversation ](https://toggl.slack.com/archives/C029WCX0T/p1609837934010200)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481307078360)

**Comment by nicktoggl** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307093063)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481307103085)
