### ISSUE TITLE
Crash when trying to run the auto-updater

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4814]
### 💻 Environment
Platform: Windows
Toggl Version: 7.5.442

### 🐞 Actual behavior
App crashes

### 💯 Expected behavior
App doesn't crash

### 🔨 Steps to reproduce
Unknown, but there are Bugsnag reports: [310 events in the past month](https://app.bugsnag.com/toggldesktop/toggldesktop/errors/5ced559b8fdb2e0018764a15?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[event.severity][0][type]=eq&filters[event.severity][0][value]=error&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=Win32Exception&filters[search][1][type]=eq&filters[search][1][value]=LaunchUpdater).

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481307074188)
