### ISSUE TITLE
Current entry editor is not showing

### ISSUE THREAD

**Issue by elipavlov** [toggl-open-source/toggldesktop#4843]
### 💻 Environment

Platform: macOS
OS Version: 10.15.7
Toggl Version: 7.5.441 

### 🐞 Actual behavior
Current entry editor is not showing, and instead of that I see the "Add Time Entry" button.
But a time entry, pushed from another application (e.g. from a mobile app) has appeared.

### 💯 Expected behavior
Current entry editor is showing.

### 🔨 Steps to reproduce
I did not notice anything special which led to this behavior.
I just track my time as usual, in different apps: web app, mobile app, desktop.

### 📦 Additional info
After pressing the "Add Time Entry" button a new time entry is created but with a short amount of time and as ended, and appearance stays the same.

It happened second time since this app version 7.5.441.
For the first time pressing the menu -> Account -> Clear Cache, was helped.
For the second (current) time such workaround did not help.

<img width="798" alt="Screenshot 2021-03-19 at 12 21 05" src="https://user-images.githubusercontent.com/7875287/116597144-e83f0a00-a92d-11eb-97dd-acd161968f79.png">

**Comment by AndrewVebster** [comment]
@elipavlov it looks like the app accidentally switched the timer to "Manual mode". 
You can switch back using the main app menu: Toggl Track -> Switch mode
or by pressing ⌘D
Sorry for the inconvenience.

**Comment by elipavlov** [comment]
@AndrewVebster, thanks a lot!

It works.

It definitely is not a bug, but my ignorance. Sorry for bothering.
