### ISSUE TITLE
Linux App: Error When Clicking on Reports Button

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#4863]
### 💻 Environment

Platform: Linux
OS Version: Ubuntu 18.04.5 LTS
Toggl Version: 7.4.528

### 🐞 Actual behavior
User notes in [convo](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481309623163) that attempting to click on the reports button within the app throws a "HTTP ERROR 418" message

### 💯 Expected behavior
Clicking on the report button should bring user to reports in webapp

**Comment by nicktoggl** [comment]
Reports page is opening a Chrome browser when the reports link is clicked, but doesn't progress. See convo link in OP for more details.

**Comment by skel35** [comment]
The latest stable version of the Linux app is 7.5.324, please tell the user to use that.

**Comment by nidarasheed** [comment]
Thanks!

**Comment by TheSoloJake** [comment]
@denismullaraj Wondering if we should just close this issue at this point, considering the current depreciated state of the Linux app. Doesn't make sense to leave it open in the repo

**Comment by TheSoloJake** [comment]
Closing due to Linux app's depreciated status
