### ISSUE TITLE
Can't add task to project from mini-timer on Windows

### ISSUE THREAD

**Issue by pablohs1986** [toggl-open-source/toggldesktop#4867]
### 💻 Environment
Toggl 7.5.445
Platform: Windows 10 Pro 64 bits 21H1

### 🐞 Actual behavior
Can't add task to project from mini-timer on Windows. The button to do it doesn't work, it doesn't do anything.

### 💯 Expected behavior
Allow adding task to project from mini-timer (as before).

Thanks!!

**Comment by skel35** [comment]
Hi @pablohs1986 !
Can you please share in more detail what exactly doesn't work?
Screenshots or a short screen recording would be appreciated, thanks!

**Comment by pablohs1986** [comment]
Sorry, I just realized that you have to double click on "add project" for add a project from mini timer... I was clicking just once . I close the issue. Sorry and thanks!!
