### ISSUE TITLE
Pomodoro alarm is broken or non-existent

### ISSUE THREAD

**Issue by bitshiftnetau** [toggl-open-source/toggldesktop#4893]
### 💻 Environment
Platform: macOS
OS Version: Monterey 12.3
Toggl Version: Track 7.5.441

### 🐞 Actual behavior
No alarm sounds when pomodoro is complete (across all apps, but reporting desktop here)

### 💯 Expected behavior
An alarm or even basic notification should sound at the end of a pomodoro.

### 🔨 Steps to reproduce

1. Start a pomodoro through the desktop app
2. Wait for it to finish
3. Witness the lack of notification

**Comment by mrsekut** [comment]
I have the same problem.
I haven't received any notifications since I updated my MacOS to Monterey.
My Mac's preferences notification settings have toggl notifications turned on.

**Comment by bitshiftnetau** [comment]
I've stopped using Toggl altogether, they're just not very good at what they do and/or don't have the resources to support their ecosystem. Their latest release also fixes non-priority bugs so I have very little trust in their abilities overall. Surprising given that they somehow managed to gain integration with the likes of monday.com et al.
