### ISSUE TITLE
Can't add "What are you working on" on MacOS Monterey (12.5)

### ISSUE THREAD

**Issue by leocob** [toggl-open-source/toggldesktop#4902]
### 💻 Environment
Platform: Macbook pro
OS Version: macOS 12.5
Toggl Version: 7.5.441

### 🐞 BUG
The upper bar doesn't show "What are you working on" anymore. I can't add an interactive time entry. I can only add time entries with start and end times by clicking on the button "Add Time Entry". This happened after updating macOS to 12.5.
I already tried to restart the laptop and to re-install the Toggl app but didn't solve the problem. I attach a screenshot of what I see

![Screenshot 2022-08-10 at 10 23 07](https://user-images.githubusercontent.com/58815060/183852568-49adc56b-626f-4da5-9487-e7f5b4e20773.png)

**Comment by leocob** [comment]
Never mind, I've just realized I was in Manual Mode, activated by mistake by clicking on the keyboard shortcut Command+D. Sorry for thinking it was a bug 😅

**Comment by AndrewVebster** [comment]
No problem 😄. Was just trying to explain it 👍. We'll work on it so it's less confusing.
