### ISSUE TITLE
Idle notification appears every 10 minutes

### ISSUE THREAD

**Issue by zd-dalibor** [toggl-open-source/toggldesktop#4905]
### 💻 Environment

Platform: 
Windows 11
![image](https://user-images.githubusercontent.com/226822/194267602-c1aa1aeb-c90d-4aea-aa6d-a08239f58c1c.png)

### 📒 Description

If you configure idle notification to 10 minutes and you are idle 60 minutes when you camoe back to you computer you will get six notification popups (on every 10 mins you will get a new popup).

I think we should have only one idle notification popup at the end of the first 10 minutes interval.
![image](https://user-images.githubusercontent.com/226822/194280148-f9b0e652-fb72-472d-98af-3d4aec6b5d8d.png)

**Comment by kornelijepetak** [comment]
Hey, thanks for reporting this. 

Given that this concerns our new app would you mind reposting this on our [new app's public feedback repository](https://github.com/toggl/track-windows-feedback/issues)?

**Comment by zd-dalibor** [comment]
@kornelijepetak 
Thanks for this information. I will do it.
Plese colse this if it is not relevant for this repository.

**Comment by kornelijepetak** [comment]
Closing as it refers to the new app.

* [ ] https://github.com/toggl/track-windows-feedback/issues/18
